### ISSUE TITLE
Support for resolutionStrategy per configruation

### ISSUE THREAD

**Issue by eric-isakson** [spring-gradle-plugins/dependency-management-plugin#100]
In my corporate environment, there are builds that make use of this plugin. I maintain an internal Gradle plugin that enforces several corporate policies related to third party dependencies. The rules governing the use of third party dependencies vary by configuration and other project properties such that I need the ability to apply component selection rules that are different between configurations we ship from versus configuration that are only used internally. For example there may be dependencies that our legal department has cleared for internal use that I may use in testCompile or testRuntime but I need to reject in the compile and runtime configurations of a project that produces artifacts that ship to our customers because those same dependencies are not allowed ot be shipped.

I want to be able to set the resolution strategy from my corporate policy plugins after the original build author has applied and configured the dependencyManagement block in the main build.gradle file. To do that, I need the ability for a DependencyManagementHandler to have a resolutionStrategy applied and the dependencyManagement extension to provide accessors to the handler (or some public interface thereof) rather than creating a new one if the propertyMissing method is called. So what I would like is in my corporate plugin to be able to say something like:

```groovy
if (project.plugins.hasPlugin('io.spring.dependency-management')) {
    project.dependencyManagement.compile.resolutionStrategy myStrategy
}
```

and/or for my build.gradle author to say:

```groovy
dependencyManagement {
     compile {
          resolutionStrategy {
               …
          }
     }
}
```

**Comment by wilkinsona** [comment]
Having looked at your workaround, this doesn't add as much complexity as I feared. Would you be interested in contributing something?

**Comment by eric-isakson** [comment]
I would love to contribute a fix for this but I do not have bandwidth to work on it at this time. I will circle back on this if I get time. Right now, the fork I'm using with the workaround is getting me by but I do not view it as a solid correct fix for this issue.

**Comment by wilkinsona** [comment]
Ok, thanks for following up. I'm going to close this for now then. If you get some time, please let me know and we can re-open this issue.

**Comment by eric-isakson** [comment]
Andy, can we just leave this open in case someone else in the community gets time to fix this before I find cycles? What is the driver to close it even though it isn't fixed?

**Comment by wilkinsona** [comment]
> What is the driver to close it even though it isn't fixed?

I use issues as a roadmap/todo list. AFAIK, you're the only person with this requirement so if you don't implement it I think it's unlikely that anyone else will. If it turns out that someone else does have the same requirement I don't think this issue being closed will make any difference.
