### ISSUE TITLE
SNAPSHOT dependencies listed in a Maven BOM are not updated

### ISSUE THREAD

**Issue by h4xmd** [spring-gradle-plugins/dependency-management-plugin#101]
I've been trying various plugins but they all seem to have the same problem in that Gradle doesn't check for newer versions of SNAPSHOT libraries that are referenced in a BOM.

What I can see working correctly is that Gradle is checking for a newer version of the BOM (which I have as a SNAPSHOT version) but the SNAPSHOT library versions the BOM specifies are not being checked and updated even with a --refresh-dependencies.

**Comment by wilkinsona** [comment]
If you've tried various plugin and they all have the same behaviour, why do you think it's a problem with this plugin rather than Gradle or user error? Can you please provide some more details? A sample that reproduces the problem would be ideal.

**Comment by h4xmd** [comment]
I'll try and get you some samples tonight.  I guess the difficulty is trying to determine if it's a plugin or Gradle issue.  My initial thoughts was the plugin since it's the one that implements the BOM feature but I don't know enough about how the plugin works with the Gradle dependency resolution to know any better.

**Comment by h4xmd** [comment]
So a bit of logging that I can see...

When running with --refresh-dependencies and --info, I can see the following:

`Cached resource Fri Feb 26 19:50:35 AEST 2016 is up-to-date (lastModified: http://nexus.oniqua.com:8081/content/groups/public/org/springframework/boot/spring-boot-starter-parent/1.3.3.RELEASE/spring-boot-starter-parent-1.3.3.RELEASE.pom).
Cached resource Wed Nov 04 15:26:14 AEST 2015 is up-to-date (lastModified: http://nexus.oniqua.com:8081/content/groups/public/com/oniqua/panorama/dependency-internal/1.0.0-SNAPSHOT/dependency-internal-1.0.0-20151104.052650-27.pom).
`
Inside the dependency-internal BOM, we have the following

`<dependency>
                <groupId>com.oniqua.panorama.lib</groupId>
                <artifactId>panorama-bootstrap</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>`

However all I see in the gradle logs is the following:

`Using version '1.0.0-SNAPSHOT' for dependency 'com.oniqua.panorama.lib:panorama-bootstrap:'`

There are no log entries that show gradle checking to see if the Cached resource is up-to-date

**Comment by h4xmd** [comment]
I forgot to add that my build.gradle looks like this:

`dependencyManagement {
    resolutionStrategy {
        cacheChangingModulesFor 0, 'seconds'
    }
    imports {
        mavenBom "com.oniqua.panorama:dependency-internal:1.0.0-SNAPSHOT"
        mavenBom "com.oniqua.panorama:dependency-external:1.0.0-SNAPSHOT"
    }
}`

**Comment by wilkinsona** [comment]
The bom is being checked because of the dependency management resolution strategy that you have configured. What happens if you do the same for the project's configurations?

**Comment by h4xmd** [comment]
No change unfortunately.

> configurations.all {
    resolutionStrategy {
        cacheDynamicVersionsFor 0, 'seconds'
        cacheChangingModulesFor 0, 'seconds'
    }
}

>

**Comment by wilkinsona** [comment]
It works for me with this `build.gradle`:

```groovy
buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath 'io.spring.gradle:dependency-management-plugin:0.6.0.RELEASE'
	}
}
apply plugin: 'java'
apply plugin: 'io.spring.dependency-management'

repositories {
	maven { url 'https://repo.spring.io/libs-snapshot' }
}

dependencies {
	compile 'org.springframework:spring-core:4.3.2.BUILD-SNAPSHOT'
}

configurations.all {
	resolutionStrategy {
		cacheDynamicVersionsFor 0, 'seconds'
		cacheChangingModulesFor 0, 'seconds'
	}
}

dependencyManagement {
	resolutionStrategy {
		cacheDynamicVersionsFor 0, 'seconds'
		cacheChangingModulesFor 0, 'seconds'
	}
}
```

Running `gradle dependencies --configuration compile --info` produces:

```
…
Using version '4.3.2.BUILD-SNAPSHOT' for dependency 'org.springframework:spring-core:4.3.2.BUILD-SNAPSHOT'
Cached resource https://repo.spring.io/libs-snapshot/org/springframework/spring-core/4.3.2.BUILD-SNAPSHOT/spring-core-4.3.2.BUILD-20160715.204924-12.pom is up-to-date (lastModified: Mon Jul 18 06:32:33 BST 2016).
…
Cached resource https://repo.spring.io/libs-snapshot/org/springframework/spring-core/4.3.2.BUILD-SNAPSHOT/spring-core-4.3.2.BUILD-20160715.204924-12.pom is up-to-date (lastModified: Mon Jul 18 06:32:33 BST 2016).
```

It'd checked (twice) that `spring-core` is up-to-date. Without a sample that reproduces the problem I'm unable to make any further progress on this. If you provide such a sample then we can re-open this issue and continue the investigation.
