### ISSUE TITLE
Incorrect documentation on maven exclusions not being honored?

### ISSUE THREAD

**Issue by kilokahn** [spring-gradle-plugins/dependency-management-plugin#104]
Hello guys!

Looking at the "Maven exclusions" section in the `README.md`, it seems to incorrectly note that Gradle doesn't honor the maven exclusions noted in the dependent POMs. I think this might have been the case with older versions of gradle, but I tried it with 2.14 and it seems to be working fine. I can share my sample setup to demonstrate this. If my guess is right, maybe we should add a note stating that this is applicable for older versions alone?

Thanks!

**Comment by wilkinsona** [comment]
AFAIK, Gradle's behaviour is still as it is described in the README. If you have a sample that demonstrates otherwise, I'd love to see it please.

**Comment by kilokahn** [comment]
I have tried to capture it here.
https://github.com/kilokahn/gradle-exclusion-tester. Feel free to point out
anything amiss there!

**Comment by wilkinsona** [comment]
Thanks for providing the sample, but it doesn't actually test the different exclusion behaviour. I've opened a pull request that updates the projects and demonstrates that the exclusions are still treated differently with Gradle 2.14.

**Comment by kilokahn** [comment]
Thanks @wilkinsona  for the explanation - the pull request exactly demonstrates the problem - sorry about the trouble!
