### ISSUE TITLE
Incorrect pom.xml generated when using dependency management and maven-publish?

### ISSUE THREAD

**Issue by wujek-srujek** [spring-gradle-plugins/dependency-management-plugin#108]
For an example build.gradle:

    buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath 'io.spring.gradle:dependency-management-plugin:0.6.0.RELEASE'
        }
    }

    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'maven-publish'

    repositories {
        jcenter()
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                from components.java
            }
        }
        repositories {
            maven {
                url "$buildDir/repo"
            }
        }
    }

    dependencyManagement {
        imports {
            mavenBom 'org.springframework.boot:spring-boot-dependencies:1.3.6.RELEASE'
        }

        dependencies {
            dependency 'org.projectlombok:lombok:1.16.10'
            dependency 'cglib:cglib-nodep:3.2.4'
            dependency 'org.objenesis:objenesis:2.4'
            dependency 'com.google.guava:guava:19.0'
        }
    }

    dependencies {
        compileOnly 'org.projectlombok:lombok'

        compile 'org.springframework:spring-core'
        compile 'org.slf4j:slf4j-api'
        compile 'com.google.guava:guava'

        testCompile 'org.codehaus.groovy:groovy-all'
        testCompile 'org.spockframework:spock-core'

        testRuntime 'cglib:cglib-nodep'
        testRuntime 'org.objenesis:objenesis'
        testRuntime 'org.slf4j:slf4j-simple'
    }

    defaultTasks = ['clean', 'build']

    task wrapper(type: Wrapper) {
        gradleVersion = '2.14.1'
    }

the pom.xml generated looks like this:

    <?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <modelVersion>4.0.0</modelVersion>
      <groupId>com.test</groupId>
      <artifactId>gradle-deps-maven</artifactId>
      <version>0.1.0-SNAPSHOT</version>
      <dependencies>
        <dependency>
          <groupId>org.springframework</groupId>
          <artifactId>spring-core</artifactId>
          <scope>runtime</scope>
        </dependency>
        <dependency>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-api</artifactId>
          <scope>runtime</scope>
        </dependency>
        <dependency>
          <groupId>com.google.guava</groupId>
          <artifactId>guava</artifactId>
          <scope>runtime</scope>
        </dependency>
      </dependencies>
      <dependencyManagement>
        <dependencies>
          <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-dependencies</artifactId>
            <version>1.3.6.RELEASE</version>
            <scope>import</scope>
            <type>pom</type>
          </dependency>
          <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.16.10</version>
          </dependency>
          <dependency>
            <groupId>cglib</groupId>
            <artifactId>cglib-nodep</artifactId>
            <version>3.2.4</version>
          </dependency>
          <dependency>
            <groupId>org.objenesis</groupId>
            <artifactId>objenesis</artifactId>
            <version>2.4</version>
          </dependency>
          <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>19.0</version>
          </dependency>
        </dependencies>
      </dependencyManagement>
    </project>

There seem to be some issues:
* all dependencies with scope other than 'compile' are ignored
* all dependencies with scope 'compile' are set to 'runtime'

Is this the expected behavior?

**Comment by wilkinsona** [comment]
I don't think this has anything to do with the dependency management plugin. If I remove the plugin, leaving this `build.gradle`:

```groovy
apply plugin: 'java'
apply plugin: 'maven-publish'

group 'com.test'

repositories {
    jcenter()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "$buildDir/repo"
        }
    }
}

dependencies {
    compileOnly 'org.projectlombok:lombok'

    compile 'org.springframework:spring-core'
    compile 'org.slf4j:slf4j-api'
    compile 'com.google.guava:guava'

    testCompile 'org.codehaus.groovy:groovy-all'
    testCompile 'org.spockframework:spock-core'

    testRuntime 'cglib:cglib-nodep'
    testRuntime 'org.objenesis:objenesis'
    testRuntime 'org.slf4j:slf4j-simple'
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.14.1'
}
```

It produces this pom:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.test</groupId>
  <artifactId>gh-108</artifactId>
  <version>unspecified</version>
  <dependencies>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-core</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>
```

The same two issues are there.

**Comment by wujek-srujek** [comment]
You are right, sorry for the bogus report.
Moreover, if I wrap the publishing configuration in

    model { ... }

it works.
