### ISSUE TITLE
pom.xml with only dependencyManagement element when used with maven-publish and submodules

### ISSUE THREAD

**Issue by wujek-srujek** [spring-gradle-plugins/dependency-management-plugin#109]
I have a project with two submodules. The root build.gradle uses the dependency-management-plugin, deines some common deps as well as import spring-boot BOM, and the submodules add their own. The main project also applies the maven-publish plugin. Here is the code:

build.gradle:

    buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath 'io.spring.gradle:dependency-management-plugin:0.6.0.RELEASE'
        }
    }

    allprojects {
        repositories {
            jcenter()
        }
    }

    subprojects {
        apply plugin: 'java'
        apply plugin: 'io.spring.dependency-management'
        apply plugin: 'maven-publish'

        publishing {
            publications {
                mavenJava(MavenPublication) {
                    from components.java
                }
            }
            repositories {
                maven {
                    url "$buildDir/repo"
                }
            }
        }

        archivesBaseName = "$group.$name"

        dependencyManagement {
            imports {
                mavenBom 'org.springframework.boot:spring-boot-dependencies:1.3.6.RELEASE'
            }

            dependencies {
                dependency 'com.google.guava:guava:19.0'

                dependency 'javax.ws.rs:javax.ws.rs-api:2.0.1'
                def jersey2Version = importedProperties['jersey.version']
                ['org.glassfish.jersey.core:jersey-client',
                 'org.glassfish.jersey.media:jersey-media-multipart'].each {
                    dependency "$it:$jersey2Version"
                }
            }
        }

        dependencies {
            compile 'org.slf4j:slf4j-api'
            compile 'com.google.guava:guava'
            compile 'com.fasterxml.jackson.core:jackson-databind'
        }
    }

    task wrapper(type: Wrapper) {
        description = 'Defines the common gradle distribution for this project.'
        gradleVersion = '2.14.1'
    }

core/build.gradle:

    dependencies {
        compile 'javax.ws.rs:javax.ws.rs-api'

        testRuntime 'org.glassfish.jersey.core:jersey-client'
    }

jaxrs2/build.gradle:

    dependencies {
        compile project(':core')
        compile 'org.glassfish.jersey.media:jersey-media-multipart'

        runtime 'org.glassfish.jersey.core:jersey-client'
        runtime 'org.glassfish.jersey.media:jersey-media-json-jackson'
    }

When I call `./gradlew clean publish`, the jars and poms are deployed to a 'repo' within the build directories of the modules (that's for testing). Here are the poms:

core:

    <?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <modelVersion>4.0.0</modelVersion>
      <groupId>com.test</groupId>
      <artifactId>core</artifactId>
      <version>0.1.0-SNAPSHOT</version>
      <dependencyManagement>
        <dependencies>
          <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-dependencies</artifactId>
            <version>1.3.6.RELEASE</version>
            <scope>import</scope>
            <type>pom</type>
          </dependency>
          <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>19.0</version>
          </dependency>
          <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
            <version>2.0.1</version>
          </dependency>
          <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-client</artifactId>
            <version>2.22.2</version>
          </dependency>
          <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-multipart</artifactId>
            <version>2.22.2</version>
          </dependency>
        </dependencies>
      </dependencyManagement>
    </project>

jaxrs2:

    <?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <modelVersion>4.0.0</modelVersion>
      <groupId>com.test</groupId>
      <artifactId>jaxrs2</artifactId>
      <version>0.1.0-SNAPSHOT</version>
      <dependencyManagement>
        <dependencies>
          <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-dependencies</artifactId>
            <version>1.3.6.RELEASE</version>
            <scope>import</scope>
            <type>pom</type>
          </dependency>
          <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>19.0</version>
          </dependency>
          <dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
            <version>2.0.1</version>
          </dependency>
          <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-client</artifactId>
            <version>2.22.2</version>
          </dependency>
          <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-multipart</artifactId>
            <version>2.22.2</version>
          </dependency>
        </dependencies>
      </dependencyManagement>
    </project>

As you can see, only \<dependencyManagement> is to be found, but this just defines the versions etc. There is no \<dependencies> element.

**Comment by wilkinsona** [comment]
Like #108, I don't think has anything to do with the dependency management plugin. If I remove it entirely the generated poms are empty (no `<dependencyManagement>` or `<dependencies>`). I suspect you need to wrap things in a `model` block again.
