### ISSUE TITLE
Drop support for Gradle 3

### ISSUE THREAD

**Issue by wilkinsona** [spring-gradle-plugins/dependency-management-plugin#115]
See #114

Background:

- https://discuss.gradle.org/t/cannot-apply-spring-boot-gradle-plugin-in-own-plugin-with-gradle-3-0/19516/2?u=andy_wilkinson
- https://discuss.gradle.org/t/missing-dependency-org-gradle-api-internal-dynamicobject-prevents-extending-plugin-task/19472
- https://discuss.gradle.org/t/existing-plugins-broken-by-leakage-of-org-gradle-api-internal-dynamicobject-into-bytecode/18209
- https://issues.gradle.org/browse/GRADLE-3493

The suggestion seems to be for plugin developers to maintain multiple versions, one that supports 3.0 and one that supports earlier versions. That's going to be a mess and isn't worth the effort until Gradle 3 has seen significant adoption.

**Comment by snicoll** [comment]
Duly noted. That means that start.spring.io is not going to upgrade to Gradle 3.

**Comment by vpavic** [comment]
> That's going to be a mess and isn't worth the effort until Gradle has seen significant adoption.

@wilkinsona Can you clarify this a bit? I assume you're referring to 3.x adoption?

**Comment by wilkinsona** [comment]
Oops. Thanks. Yes, I meant Gradle 3 specifically. I've edited my original comment.

**Comment by djablonski** [comment]
How is Gradle 3 to gain significant adoptions if common frameworks/toolchains do not support it? :(

**Comment by wilkinsona** [comment]
I don't know, but that's Gradle's problem. I do know that they are aware of the problem and are working hard to address it. See [this forum thread](https://discuss.gradle.org/t/implementing-a-custom-task-without-depending-on-gradles-internals/19530) for some details.

**Comment by lordofthejars** [comment]
I think I managed to work latest dependency-management-plugin in Gradle 3, is it possible or I am so confused now?

**Comment by wilkinsona** [comment]
It does work, but only some of the time. Unfortunately, I don't fully understand when it will and won't work, despite plenty of input from the Gradle team. It appears, in part at least, to be due to Gradle's automatic instrumentation of plugin code. Given the uncertainty of the situation, regrettably the safest option for now is to stop claiming support for Gradle 3.0.

**Comment by remmeier** [comment]
we are using gradle 3.1 and every thing seems to work fine. 

the issue linked https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/112 is fixed with that version.

if there is still anything to worry about, a hint would be appreciated.

**Comment by wilkinsona** [comment]
@remmeier Please see [my comment](https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/115#issuecomment-250696606) immediately before yours. The problem is that no one, not even the Gradle team, seems to fully understand what will and won't work.
