### ISSUE TITLE
Accessing importedProperties causes missing dependencies in pom

### ISSUE THREAD

**Issue by otrosien** [spring-gradle-plugins/dependency-management-plugin#117]
This might be related to issue #56, but I'm not sure, so I'm creating a new one. When I'm trying to use dependencyManagement.importedProperties within my dependencies section, everything is good until the generation of the pom file. There, all dependencies starting with the one that used importedProperties are missing.

Here's a sample project that demonstrates the issue: https://github.com/otrosien/spring-gradle-dependency-bug

That's how the pom looks like:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId/>
  <artifactId>spring-gradle-dependency-bug</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.4.1.RELEASE</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
```

This is how it should look like. Notice the extra dependencies for metrics-jetty9 and guava.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId/>
  <artifactId>spring-gradle-dependency-bug</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.dropwizard.metrics</groupId>
      <artifactId>metrics-jetty9</artifactId>
      <version>3.1.2</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>19.0</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.4.1.RELEASE</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
```

**Comment by wilkinsona** [comment]
For reasons that I don't fully understand, Gradle requires you to wrap anything that's publishing-related in a `model` block. For example:

```groovy
model {
	publishing {
		publications {
			mavenJava(MavenPublication) {
				from components.java
			}
		}
	}
}
```

This is described [in their documentation]() where it says:

> The “maven-publish” plugin leverages some experimental support for late plugin configuration, and any `GenerateMavenPom` tasks will not be constructed until the publishing extension is configured. The simplest way to ensure that the publishing plugin is configured when you attempt to access the `GenerateMavenPom` task is to place the access inside a model block, as the example above demonstrates.

> The same applies to any attempt to access publication-specific tasks like `PublishToMavenRepository`. These tasks should be referenced from within a `model` block.

I'm now wondering if the plugin could do this for you. While I investigate that, making the change above to you `build.gradle` should fix the problem for you.

**Comment by wilkinsona** [comment]
The plugin can't do this for you as it relies on internal APIs. In Gradle 1.12 it's only available via `org.gradle.api.internal.project.AbstractProject`:

```java
// Longer term it will not be available via Project, but be only available in a build script
public void model(Closure action) {
    new GroovyModelDsl(modelRules).configure(action);
}
```

It's still there in master, but it's still an internal API and it's on `org.gradle.api.internal.project.DefaultProject` now:

```
// Not part of the public API
public void model(Closure<?> modelRules) {
    ModelRegistry modelRegistry = getModelRegistry();
    if (TransformedModelDslBacking.isTransformedBlock(modelRules)) {
        ClosureBackedAction.execute(new TransformedModelDslBacking(modelRegistry, this.getRootProject().getFileResolver()), modelRules);
    } else {
        new NonTransformedModelDslBacking(modelRegistry).configure(modelRules);
    }
}
```

In short, there's no way to programatically make use of the `model` block without using unstable internal APIs. Unfortunately, that means you'll have to do it yourself.

**Comment by wilkinsona** [comment]
I've started [a thread](https://discuss.gradle.org/t/is-there-a-programmatic-equivalent-of-using-the-model-block-in-a-build-script/19680) on Gradle's forum to see if there's another way to do this. I'll re-open this issue if it turns out that it is possible after all.

**Comment by otrosien** [comment]
Thanks alot @wilkinsona! The solution works. Unfortunately the gradle documentation is rarely using that model block itself. :-(
