### ISSUE TITLE
Provide API access to iterate over the mavenBoms

### ISSUE THREAD

**Issue by dsyer** [spring-gradle-plugins/dependency-management-plugin#121]
Similarly to the way you can iterate over dependencies though the standard Gradle APIs, e.g. `configurations.runtime.dependencies.each {...}`, it would be handy to be able to iterate over the mavenBoms.

**Comment by wilkinsona** [comment]
@dsyer Do you need access to the actual bom coordinates? You can already get at all of the managed versions that come from the boms: https://github.com/spring-gradle-plugins/dependency-management-plugin#programmatic-access. What are you trying to do?

**Comment by dsyer** [comment]
I want to create a machine readable list of boms. I don't really follow what the existing API access is doing (docs are a bit thin), but it isn't providing any iterators, so I don't think it does what I need.

**Comment by wilkinsona** [comment]
Upon further investigation, this isn't needed.
