### ISSUE TITLE
Not support @ version suffix

### ISSUE THREAD

**Issue by warnyul** [spring-gradle-plugins/dependency-management-plugin#123]
I tried to set dependency type with gradle standard @ suffix, but the generated pom will be bad.

dependency 'com.github.lecho:hellocharts-library:1.5.8@aar'

Generated tags:
<dependency>
        <groupId>com.github.lecho</groupId>
        <artifactId>hellocharts-library</artifactId>
        <version>1.5.8@aar</version>
</dependency>

Good:
<dependency>
        <groupId>com.github.lecho</groupId>
        <artifactId>hellocharts-library</artifactId>
        <version>1.5.8</version>
        <type>aar</type>
</dependency>

Will be a solution for this problem?

**Comment by wilkinsona** [comment]
Unfortunately, classifiers are a second class citizen in Gradle. See [this issue](https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/67) for more details. That means that even if the pom generation could be corrected, the behaviour for managing a dependency with a classifier would not be. Your best bet is to remove the `@aar` from the dependency management and then customise the pom yourself.
