### ISSUE TITLE
"bom importing bom" is officially supported?

### ISSUE THREAD

**Issue by flozano** [spring-gradle-plugins/dependency-management-plugin#124]
Hi!

We're using this plugin (thank you, again, for it!) and were wary of having our own maven BOM import other external BOMs, because I didn't see any test in the plugin code that checks if it works. However, I just tried it and it works.

Is this use-case supported or intended to work?

**Comment by wilkinsona** [comment]
Yes, that's intended to work and is supported. We rely on it in Spring Boot's bom which, for example, imports Spring Framework's bom. The code that makes it work is actually part of the Maven code that the plugin embeds, but that doesn't mean that there's no need to add a test for it. We can use this issue to add one.

**Comment by wilkinsona** [comment]
Upon closer inspection, this is already covered. `DependencyManagementPluginSpec` has tests that use the Spring IO Platform's bom and that verify that Spring Framework modules are being managed. Their dependency management is provided by `spring-framework-bom` which is imported by an ancestor of the platform bom.
