### ISSUE TITLE
Accessing importedProperties map breaks POM generation

### ISSUE THREAD

**Issue by ryanflegel** [spring-gradle-plugins/dependency-management-plugin#125]
My scenario is that I want to use the `spring-boot-dependencies` BOM, which includes has `jersey-server` and other supporting Jersey libraries (eg, `jersey-media-json-jackson`). I want to include `jersey-client` in my project which is _not_ defined in `spring-boot-dependencies` and I'd like to use the same Jersey version.

I'm using `dependencyManagement.importedProperties['jersey.version']` to get the Jersey version from the `spring-boot-dependencies` BOM, like so:

    dependencyManagement {
        imports {
            mavenBom 'org.springframework.boot:spring-boot-dependencies:1.4.2.RELEASE'
        }

        dependencies {
            dependency "org.glassfish.jersey.core:jersey-client:${dependencyManagement.importedProperties['jersey.version']}"
        }
    }

And the dependency is resolved to the expected version (2.23.2):

    $ ./gradlew dependencyManagement | grep jersey-client | uniq
        org.glassfish.jersey.core:jersey-client 2.23.2

And `./gradlew clean build` runs just fine.

_But_, the POM file generated from the `maven-publish` plugin has some big issues. `groupId`, `artifactId` and `version` are all `null` and the `<dependencies />` section is missing.

    <?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <modelVersion>4.0.0</modelVersion>
      <groupId>null</groupId>
      <artifactId>null</artifactId>
      <version>null</version>
      <dependencyManagement>
        <dependencies>
          <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-dependencies</artifactId>
            <version>1.4.2.RELEASE</version>
            <scope>import</scope>
            <type>pom</type>
          </dependency>
          <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-client</artifactId>
            <version>2.23.2</version>
          </dependency>
        </dependencies>
      </dependencyManagement>
    </project>

If I hardcode the `jersey-client` version to ` 2.23.2` the POM generates as expected.

I'm not sure if `importedProperties[]` was meant to be used inside the `dependencyManagement` block, but I would find this handy.

**Comment by wilkinsona** [comment]
That's weird on a couple of counts:

1. I'm surprised that it "worked" at all (see #56)
2. I have no idea why it's messing up the pom's `groupId`, `artifactId` and `version`

**Comment by wilkinsona** [comment]
@ryanflegel I can't reproduce the broken pom. Here's what I tried:

```groovy
buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath 'io.spring.gradle:dependency-management-plugin:0.6.1.RELEASE'
	}
}

apply plugin: 'io.spring.dependency-management'
apply plugin: 'java'
apply plugin: 'maven-publish'

repositories {
	mavenCentral()
}

dependencyManagement {
	imports {
		mavenBom 'org.springframework.boot:spring-boot-dependencies:1.4.2.RELEASE'
	}

	dependencies {
		dependency "org.glassfish.jersey.core:jersey-client:${dependencyManagement.importedProperties['jersey.version']}"
	}
}

dependencies {
	compile "org.glassfish.jersey.core:jersey-client"
}

model {
	publishing {
		publications {
			mavenJava(MavenPublication) {
				from components.java
			}
		}
	}
}
```

Note the use of `model` around the configuration of the Maven publication. The need for it is mentioned at the bottom of [this page](https://docs.gradle.org/current/userguide/publishing_maven.html) in Gradle's documentation.

If you're already using `model` or adding it doesn't change the behaviour you are seeing, can you please provide a small `build.gradle` that reproduces your problem?

**Comment by ryanflegel** [comment]
Thanks! Using `model` fixes both issues. I guess the reason for the nulls was that they were being extracted from an extension.

That's an interesting way to manifest!
