### ISSUE TITLE
Multiproject build fails to resolve transitive dependency when dependent project applies dependency management

### ISSUE THREAD

**Issue by eric-isakson** [spring-gradle-plugins/dependency-management-plugin#126]
When I have a project that does not apply dependency managment and it makes a project dependency on another project that does, the transitive dependency does not resolve.

You can find an example test case here: https://github.com/eric-isakson/dependency-management-plugin/commit/cccc3434a2730c5d49cdf102de8e8d9514486147

**Comment by wilkinsona** [comment]
That's the way Gradle works. It's the same for any resolution strategy that controls dependency versions.
