### ISSUE TITLE
Building a Composite Build (Gradle 3.1+) fails when an included build uses the plugin

### ISSUE THREAD

**Issue by dorongold** [spring-gradle-plugins/dependency-management-plugin#127]
I have recently upgraded all my team's projects to gradle 3.2.1. Mainly because we wish to take advantage of the new composite build feature. We encountered a problem running composite builds along with dependency-management-plugin.

A simple example of the problem:

We have a "common" project which uses the dependency management plugin and an "app" project which depends on "common" and on its resolved dependencies (transitively).

Running a composite build on the "app" project fails:
```
user:/var/localwork/dependency-example/app$gradle build --include-build ../common
[composite-build] Configuring build: /var/localwork/dependency-example/common
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not find org.slf4j:slf4j-api:.
  Searched in the following locations:
      file:/home/user/.m2/repository/org/slf4j/slf4j-api//slf4j-api-.pom
      file:/home/user/.m2/repository/org/slf4j/slf4j-api//slf4j-api-.jar
      https://repo1.maven.org/maven2/org/slf4j/slf4j-api//slf4j-api-.pom
      https://repo1.maven.org/maven2/org/slf4j/slf4j-api//slf4j-api-.jar
  Required by:
      project : > project :common:

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.09 secs
```

**build.gradle of the "app" project:**
```
apply plugin: 'java'
apply plugin: 'maven'

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    compile 'deps:common:1.0'
}
```

**build.gradle of the "common" project:**
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:0.6.1.RELEASE"
    }
}

apply plugin: 'java'
apply plugin: 'maven'
apply plugin: "io.spring.dependency-management"

group = 'deps'
version = '1.0'

repositories {
    mavenCentral()
}

dependencyManagement {
    dependencies {
        dependency 'org.slf4j:slf4j-api:1.7.21'
    }
}

dependencies {
    compile 'org.slf4j:slf4j-api'
}
```
The same error happens also if *both* projects apply the dependency-mangement plugin.

So it seems that unless we stop using the dependency-mangement plugin (which is very useful for us and therefore we don't wish to stop using it), we can't use the composite build feature, which is the most anticipated feature in the new gradle release.

I realize that gradle 3.x is not yet officially supported by this plugin.
I just wanted to point out this problem so that it can be addressed in a future release of this plugin that supports gradle 3.x.

**Comment by wilkinsona** [comment]
Thanks for the advanced warning. Unfortunately, I don't think there's anything that a plugin can do about this. It appears to be a general limitation of how composite builds work: they don't seem to respect an included build's resolution strategy when calculating dependency versions.

You'll see the same problem if you replace the `build.gradle` for your `common` project with the following:

```groovy
apply plugin: 'java'

group = 'deps'
version = '1.0'

repositories {
	mavenCentral()
}

configurations.all {
	resolutionStrategy {
		force 'org.slf4j:slf4j-api:1.7.5'
	}
}

dependencies {
	compile 'org.slf4j:slf4j-api'
}
```

I think it'd be worth raising this with the Gradle team as it does detract from the usefulness of composite builds. If you do so, please link to the issue or forum thread here as I'd like to follow the discussion.

**Comment by dorongold** [comment]
I created an issue on Gradle: gradle/gradle#947
