### ISSUE TITLE
Trying to do an offline Build using a Local Repository -- Dependency issue.

### ISSUE THREAD

**Issue by mrdnewman** [spring-gradle-plugins/dependency-management-plugin#128]
Hi, I'm developing in an environment without internet access. I'm trying to configure the "build.gradle" to use a local repository. I have downloaded all the jar and pom files to my system local directories.
However, when I execute ./gradlew fetch I run into dependency issues...

Here is the Error output:
Starting a new Gradle Daemon for this build (subsequent builds will be faster).

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':runtime'.
> Could not find de.gesellix:gradle-docker-plugin:2016-05-05T13-15-11.
  Searched in the following locations:
      file:/home/radisys/cord/setup_dev/pkgrepo/mav2-repo/m2/de/gesellix/gradle-docker-plugin/2016-05-05T13-15-11/gradle-docker-plugin-2016-05-05T13-15-11.pom
      file:/home/radisys/cord/setup_dev/pkgrepo/mav2-repo/m2/de/gesellix/gradle-docker-plugin/2016-05-05T13-15-11/gradle-docker-plugin-2016-05-05T13-15-11.jar
  Required by:
      :buildSrc:unspecified
> Could not find org.yaml:snakeyaml:1.10.
  Searched in the following locations:
      file:/home/radisys/cord/setup_dev/pkgrepo/mav2-repo/m2/org/yaml/snakeyaml/1.10/snakeyaml-1.10.pom
      file:/home/radisys/cord/setup_dev/pkgrepo/mav2-repo/m2/org/yaml/snakeyaml/1.10/snakeyaml-1.10.jar
  Required by:
      :buildSrc:unspecified

Here is my build.gradle file:

apply plugin: 'groovy'

repositories {
      // maven { url 'https://repo.gradle.org/gradle/libs' }
      // maven { url 'https://plugins.gradle.org/m2/' }
      // mavenLocal()
      // mavenCentral()
      maven { url 'file://' + new File(System.getProperty("user.dir"), '/setup_dev/pkgrepo/mav2-repo/m2/').absolutePath }
      // maven { url uri('setup_dev/pkgrepo/mav2-repo/m2/')}
}

dependencies {
    compile gradleApi()
    compile localGroovy()
    compile 'de.gesellix:gradle-docker-plugin:2016-05-05T13-15-11'
    compile 'org.yaml:snakeyaml:1.10'
    //compile 'gradle.plugin.com.tmiyamon:gradle-config:0.2.1'
}

Could someone please shines some the light on the subject. I'm don't know to much about Gradle however it is something I really need to get pass as my project is coming due. 

Note:
I would able to download and store the Gradle Binary locally. It finds the binary just fine but the dependency issue is blocking me. Thanks.

**Comment by wilkinsona** [comment]
Looking at your build.gradle, you're not using the Dependency Management Plugin that's managed in this repository. If you need some general help with Gradle, I'd recommend asking a question on their forum.
