### ISSUE TITLE
resolutionStrategy.eachDependency not called anymore on custom configuration

### ISSUE THREAD

**Issue by kristofdepypere** [spring-gradle-plugins/dependency-management-plugin#130]
I created a custom configuration. In this configuration I want to replace some versions depending on a certain condition beforeResolve. After applying the dependency management plugin it seems that the closure after eachDependency is not executed anymore. I tried to get around this with dependencySubstitution but I didn't have any luck with this. I'm not sure what I have to do to make something like this possible again. Is it a bug in the plugin or do I need to do this differently in order to get this working ?

Here is my code:

```
Configuration myConfig = project.configurations.create('myConfig')
myConfig.incoming.beforeResolve {
            myConfig.resolutionStrategy.eachDependency { details ->
                if (details.requested.name == AGENT_DEPENDENCY_NAME) {
                    details.useTarget group: details.requested.group, name: details.requested.name, version: '1.0.0'
         }
     }
 }
```

I am using the latest gradle version 3.2.1. All plugin functionality seems to run file and nicely imports a BOM file setting all the versions of our dependencies. Only this problems blocks us from using it.

**Comment by wilkinsona** [comment]
The plugin uses some internal, detached configurations. You probably need to configure your resolution strategy on those too. You can do so like this: https://github.com/spring-gradle-plugins/dependency-management-plugin#configuring-the-dependency-management-resolution-strategy

**Comment by kristofdepypere** [comment]
I ended up with trying something like this:

```
project.dependencyManagement.resolutionStrategy {
      eachDependency { details ->
                if (details.requested.name == AGENT_DEPENDENCY_NAME) {
                    details.useTarget group: details.requested.group, name: details.requested.name, version: '1.0.0'
         }
    }
}
```

However got the following error in this case:

Cannot change strategy of configuration 'detachedConfiguration2' after it has been resolved.

I'm not sure if I'll get there this way. It feels like I should stay away from dynamically changing versions if I want to use this plugin.

**Comment by wilkinsona** [comment]
> However got the following error in this case:

> Cannot change strategy of configuration 'detachedConfiguration2' after it has been resolved.

That would suggest that something earlier in your build script has triggered resolution. Can you share a complete example?

> I'm not sure if I'll get there this way. It feels like I should stay away from dynamically changing versions if I want to use this plugin.

You can use dynamic versions with the plugin, although it perhaps doesn't make a huge amount of sense as the intention of this plugin is to manage versions so that know exactly what you're going to get.

**Comment by kristofdepypere** [comment]
Ok, I got it working thx for the help
