### ISSUE TITLE
Different behaviour from 0.6.1 to 1.0.0.RC1

### ISSUE THREAD

**Issue by Alvise88** [spring-gradle-plugins/dependency-management-plugin#134]
I' am trying to change to new version but i have a problem. For example if i put in my gradle file:

`project('my-dependencies') {

    apply plugin: 'java'

    apply plugin: "io.spring.dependency-management"

    def springCloudVersion = "Dalston.BUILD-SNAPSHOT"
    def springBootVersion = "1.5.0.BUILD-SNAPSHOT"

    def myVersion = "1.0.0.SNAPSHOT"

    dependencyManagement {

        imports {
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:$springCloudVersion"
            mavenBom "org.springframework.boot:spring-boot-parent:$springBootVersion"
        }

        dependencies {

            //My Framework
            dependency "mygroupid:myartifactid:$myVersion "}`

in the output with 0.6.1 there is:

```
<dependency>
    <groupId>mygroupid</groupId>
     <artifactId>myartifactid</artifactId>
     <version>1.0.0.SNAPSHOT</version>
</dependency>
```

instead in 1.0.0.RC1 the output is the following

```
<dependency>
    <groupId>mygroupid</groupId>
    <artifactId>myartifactid</artifactId>
    <version>1.0.0.SNAPSHOT</version>
    <type>null</type>
</dependency>
```

**Comment by wilkinsona** [comment]
This should be fixed in the latest 1.0.0.BUILD-SNAPSHOT available from https://repo.spring.io/plugins-snapshot. If you have a chance to try it out, please do so and let me know if your problem remains.
