### ISSUE TITLE
No LICENSE file in root directory

### ISSUE THREAD

**Issue by jvz** [spring-gradle-plugins/dependency-management-plugin#137]
Without a LICENSE file, it's not readily apparent that this project is Apache 2 licensed. In fact, without the file, it might not be properly licensed!

**Comment by jvalkeal** [comment]
@wilkinsona kinda valid point. Spring projects don't always have license in a root as it's usually baked into docs, i.e. framework has it in https://github.com/spring-projects/spring-framework/blob/master/src/dist/license.txt. We indeed don't have no license file in this project structure. Every project mentions it in readme, like we do here, but not sure if it's enough.

**Comment by wilkinsona** [comment]
This project just follows the pattern of the other Spring projects that has served us well for years and has been approved by legal. The licence is mentioned in the README and is included in the header of every source file.
