### ISSUE TITLE
io.spring.dependency-management then propdeps-maven omits optional dependencies

### ISSUE THREAD

**Issue by rwinch** [spring-gradle-plugins/dependency-management-plugin#149]
If the io.spring.dependency-management is applied before propdeps-maven then it prevents the optional dependencies from being added to the Maven pom.

Use the project https://github.com/rwinch/dependency-management-optional-order-bug

Run

```
./gradlew clean install
cat build/poms/pom-default.xml 
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId/>
  <artifactId>dependency-management-bug</artifactId>
  <version>unspecified</version>
  <dependencyManagement>
    <dependencies/>
  </dependencyManagement>
</project>
```

**Comment by wilkinsona** [comment]
This is proving to be a tricky one. Here's what's happening:

Applying the `maven` plugin (via the propdeps-maven` plugin creates a `DefaultConf2ScopeMappingContainer`. The `propdeps-maven` plugin adds mappings to this container for its `optional` and `provided` configurations.

Both plugins get hold of all of the `Upload` tasks and work their way down to the `MavenPom`. The first plugin to do this triggers the creation of a new `DefaultConf2ScopeMappingContainer`. This second mapping container is populated with a snapshot of the mappings from the container created by the `maven` plugin.

It the `propdeps-maven` plugin is applied first, then the first mapping container contains the mappings for `optional` and `provided` and these are copied over. If the `io.spring.dependency-management` plugin goes first then the `optional` and `provided` mappings do not exist at the time the copy is taken.

The absence of the `optional` and `provided` mappings in the mapping container that uses for pom generation means that any optional and provided dependencies are omitted from the generated pom.

To work reliably in combination with any plugin that may customise the configuration to scope mappings, it would appear that both plugins need to defer accessing the pom until a point where all plugins have had a chance to define their mappings. I'm not yet sure if that's possible.

**Comment by wilkinsona** [comment]
I've opened https://github.com/gradle/gradle/issues/1373 to see if anything can be done about this on the Gradle side.

After some experimentation, it appears the wrapping the logic that access the pom in an `afterEvaluate` block is sufficient to work around the problem. I'll hold off a little while on making that change in case the Gradle issue yields a better alternative. Even if a change is made in Gradle, a change is almost certainly going to be necessary to get things working reliably on all the currently available versions of Gradle.
