### ISSUE TITLE
Closure Param annotations in API

### ISSUE THREAD

**Issue by katoquro** [spring-gradle-plugins/dependency-management-plugin#152]
Just want to ask why plugin doesn't use annotations for closure params like `@DelegatesTo` or `@ClosureParams`. It can enhance syntax highlight  and code completion in IDEs.

F.e. additional to
```
/**
 * Configures the managed dependencies using the given {@code closure}. The closure is called with
 * {@link DependenciesHandler} as its delegate.
 *
 * @param closure the closure to execute to configure the dependencies
 * @see DependenciesHandler
 */
void dependencies(Closure closure);
```

use this 

```
/**...*/
void dependencies(@DelegatesTo(DependenciesHandler) Closure closure)
```

If there are no objections I can make PR with this feature

p.s.

- [additional info](http://melix.github.io/blog/2014/01/closure_param_inference.html)
- workaround is making a helper method with necessary annotations like 

```
dependencies hintDelegate(DependenciesHandler) {/*...*/}
```

**Comment by wilkinsona** [comment]
No reason. I just didn't know about them. Thanks for making me aware of them. I do wonder why Gradle doesn't make use of them in its own DSLs. I can't see how the extra information could cause any harm though. A PR would be most welcome.

**Comment by wilkinsona** [comment]
I'm going to close this one. The PR never transpired and Gradle has gone in the direction of embracing Kotlin for build scripts where users want improved code completion.
