### ISSUE TITLE
Intellij import of gradle extremely slow

### ISSUE THREAD

**Issue by arashbi** [spring-gradle-plugins/dependency-management-plugin#153]
I have a rather large project, which I recently moved to use this plugin.
When I try to import it to intellij it is very slow, compared to the previous non-bom version.
Also there are certain dependencies -specifically in my case solr-core- , which when I add to the gradle file, it makes intellij to crunch for a good 10-15 minutes and then ran out of memory. 

What could be the problem?

**Comment by wilkinsona** [comment]
No idea, but you haven't described the problem in much detail. What version of the plugin are you using? What version of IntelliJ are you using? Is a build on the command line also "extremely slow"?

**Comment by arashbi** [comment]
Plugin version is 1.0.0.RELEASE, 
Intellij is 
IntelliJ IDEA 2016.3.4
Build #IU-163.12024.16, built on January 31, 2017
Licensed to BiblioCommons / Arash Bizhan
Subscription is active until May 1, 2017
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Build on command line is a bit slower than previous build. Profiling gradle shows that the dependency resolution is significantly slower than the previous build, but it is not a show stopper. It takes about one minute to resolve the dependencies, in our ten minute build. I can post the profile files later for comparison.
But intellij doesn't like it at all. For some reason it cannot handle it. I don't know any way of debugging the process, so I am stuck.
When I try to create idea model from gradle by running `gradle idea`, gradle manages to create the project, but I still cannot open it in intellij, it just hangs.

**Comment by wilkinsona** [comment]
One thing you could try is to [disable the plugin's support for Maven-style exclusions](https://github.com/spring-gradle-plugins/dependency-management-plugin#disabling-maven-exclusions). It's significantly faster than it was, but it may still be a contributing factor.

Given the large difference in time taken on the command line and in IDEA I think you'll have to pursue this with JetBrains. I don't have any insight into what they do when importing a Gradle project any why it might be slow.

**Comment by arashbi** [comment]
Thanks a lot.
Disabling it did the trick! Now intellij is happy. I will report a bug to intellij.

**Comment by AlexCzar** [comment]
This is actually still an issue. Disabling exclusions makes our application's build fail because of conflicting dependencies. Specifically quartz depends on an old version of `com.zaxxer:HikariCP`, which I understand is excluded in the bom and is a non-issue when exclusions are enabled.
With exclusions project's refresh is orders of magnitude slower.

**Comment by wilkinsona** [comment]
@AlexCzar You may be interested in #252. A sample build that illustrates refresh being orders of magnitude slower would allow some progress to be made on that PR.

**Comment by AlexCzar** [comment]
@wilkinsona My bad, I missed that one. Thanks, I'll try to create a demo project which exhibits this. I'll share it a bit later today, if I can.
