### ISSUE TITLE
Dependency substitution by maven bom dependency version

### ISSUE THREAD

**Issue by KaRkY** [spring-gradle-plugins/dependency-management-plugin#154]
Hello,

is it alredy posible to substitute a dependency with this plugin managed dependency. Something similar to this:
```groovy
dependencyManagement` {
  imports {
    mavenBom "org.springframework.boot:spring-boot-dependencies:1.5.2.RELEASE"
  }

  resolutionStrategy {
     dependencySubstitution {
         substitute module("commons-logging:commons-logging") with module("org.slf4j:jcl-over-slf4j")
     }
  }
}
```

**Comment by wilkinsona** [comment]
It looks like you're using the wrong resolution strategy. The dependencyManagement resolution strategy is purely for controlling resolution that's internal to the plugin, for example downloading an boms that you've imported. If you want to substitute a dependency then you could use the project's main resolution strategy as you normally would.

**Comment by KaRkY** [comment]
Even if put resolutionStrategy on project level I get an error:

 Must specify version for target of dependency substitution

**Comment by wilkinsona** [comment]
Ah, sorry. I see what you mean now.

As [described in the README](https://github.com/spring-gradle-plugins/dependency-management-plugin#programmatic-access), you can use `dependencyManagement.managedVersion` to access the versions in the bom. You can then use this version when setting up the substitution rule.

Here's a complete example:

```groovy
plugins {
  id 'io.spring.dependency-management' version '1.0.0.RELEASE'
  id 'java'
}

repositories {
  mavenCentral()
}

dependencyManagement {
  imports {
    mavenBom "org.springframework.boot:spring-boot-dependencies:1.5.2.RELEASE"
  }
}

configurations.all {
  resolutionStrategy {
    dependencySubstitution {
      def slf4jVersion = dependencyManagement.managedVersions['org.slf4j:jcl-over-slf4j']
      substitute module("commons-logging:commons-logging") with module("org.slf4j:jcl-over-slf4j:$slf4jVersion")
    }
  }
}

dependencies {
  compile "org.springframework:spring-core"
}
```

**Comment by KaRkY** [comment]
Thank you I don't know why I didn't think of that.
