### ISSUE TITLE
Logger placeholders and arguments number do not match in DependencyManagementContainer::findManagedVersion method

### ISSUE THREAD

**Issue by bbelovic** [spring-gradle-plugins/dependency-management-plugin#156]
Logger statement in ```DependencyManagementContainer::findManagedVersion``` method declares four placeholders (```'{}'```) in logging message, but provides only three arguments. I think this results in situation when last placeholder is not resolved when logging message is issued to log file.

Example:
```[DEBUG] [io.spring.gradle.dependencymanagement.internal.DependencyManagementContainer] Found managed version '1.0-beta-2' for dependency 'org.apache.maven.wagon:wagon-webdav' in dependency management for configuration '{}'```

If this is recognized as an issue, can I open PR with fix?

**Comment by wilkinsona** [comment]
Well spotted. Thank you. A PR would be most welcome.

**Comment by wilkinsona** [comment]
Closing in favour of the PR (#157)
