### ISSUE TITLE
Add option for changing version resolution strategy for multiple boms

### ISSUE THREAD

**Issue by xvik** [spring-gradle-plugins/dependency-management-plugin#160]
Right now plugin follows maven convention and the latest declared bom will [override versions of artifacts declared in previous boms](https://github.com/spring-gradle-plugins/dependency-management-plugin#importing-multiple-boms).

Here is my situation: dropwizard and gradle boms used. Both depend on guava:

```groovy
imports {
        mavenBom "io.dropwizard:dropwizard-bom:1.1.0"
        mavenBom "com.google.inject:guice-bom:4.1.0"
}
```
Due to the order of definition, guice guava version (19) overrides dropwizard's one (21).
This is very confusing: I expect default gradle behavior here - select the most recent version. It took some time to understand why I have old guava.

It would be great to introduce an option to switch to gradle default behaviour and select the latest version instead of override. I understand that it would not be possible to enable this by default due to other projects requiring depending on current behavior.

Also, it would be better to add a warning about default maven-like behavior in the readme to attract attention and avoid confusing situations like mine.

**Comment by wilkinsona** [comment]
Superseded by #330.
