### ISSUE TITLE
Dependency-management-plugin has conflicts with ivy repo

### ISSUE THREAD

**Issue by eonezhang** [spring-gradle-plugins/dependency-management-plugin#161]
in my case, I need refer the dependencies in ivy repo, and also I want to use spring-boot to build my apps, unfortunately, when I integration them together, I found I could not fint the ivy dependencies. after invesitgation, I found its the dependency-management-plugin caused the problem.

here is my repo, https://github.com/eonezhang/pilot, if you try to run the command `gradle dependencies -i` in `inventory` directory you will get the detail error info. here is my error info 
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':inventory:dependencies'.
> Could not resolve all dependencies for configuration ':inventory:detachedConfiguration16'.
   > Project :inventory declares a dependency from configuration 'detachedConfiguration16' to configuration 'default' which is not declared in the descriptor for com.active.services:checkout-service:1.61.2.0.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.
```
is there any ways OR workaround to avoid it and make it works.

**Comment by wilkinsona** [comment]
The provided project doesn't reproduce the problem as nexus.dev.activenetwork.com is an unknown host. Can you provide a sample that reproduces the problem without relying on a private repository?

**Comment by eonezhang** [comment]
hi @wilkinsona , I'm trying to find public ivy repo, but I can't find any, it's all for maven.
but your suggestion can work for me, when I disable the maven-style exclusions, all things turn to be right, the problem is solved, thank you

**Comment by wilkinsona** [comment]
Ok, thanks anyway. Without a way to reproduce the problem, it's going to be rather hard to fix it. I'll close this one for now. It can be reopened if/when some more information becomes available.
