### ISSUE TITLE
Is it possible to have a project dependency within the dependencyManagement block?

### ISSUE THREAD

**Issue by jaa2261** [spring-gradle-plugins/dependency-management-plugin#162]
I'm in the process of migrating a multi-module project from maven to gradle. I'm using the plugin successfully for compile dependency management, but I haven't seen a way to manage a project dependency (as shown in the POM snippet below) within the dependencyManagement block.  
```
<dependencyManagement>
  <dependencies>
    <dependency>
     <groupId>group</groupId>
     <artifactId>proj1</artifactId>
     <version>${project.version}</version>
       <exclusions>
            <exclusion>
                 <artifactId>jgroups</artifactId>
                  <groupId>jgroups</groupId>
             </exclusion>
      </exclusion>
     </dependency>
  <dependencies>
<dependencyManagement>
```

I've tried
```
dependency project(":group:proj1") {
    exclude group: "jgroups", module: "jgroups"
}
```
but that doesn't work. Is there a way of doing this?

**Comment by wilkinsona** [comment]
There isn't. The plugin's focussed on dependencies that are coming from Maven repositories. If your goal is to configure an exclusion then you should do so using Gradle's standard mechanisms.
