### ISSUE TITLE
[Question/FeatureRequest] Can this plugin also be used to generate "mavenBom" equivalents using Gradle only? 

### ISSUE THREAD

**Issue by saljuama** [spring-gradle-plugins/dependency-management-plugin#168]
I'm trying to find a way to generate the equivalent of a Maven BOM with Gradle. 

The first option i thought of, was to create a separate project, and using other plugins in combination with the maven plugin, manage to actually publish an artifact in a maven repo, and then use this plugin to import that artifact as `mavenBom` inside the `imports` clause, but this approach is not very agile in development time.

The use case I'm facing is a multi-project setup, where have different sub-project that will create different artifacts, and also, there will be some dependencies among some sub-projects. What i want to achieve is to be able to create a sub-project, that can leverage dependencies inside the project, and also, be able to offer it as an artifact that can be imported for dependency management in other project. 

For example :
 
* projectA
  - project-bom
     - **build.gradle**   <--- This is where i want my custom BOM
  - subprojectA
     - src
     - **build.gradle**  <--- This is where i want to consume the custom BOM

* projectB
  - build.gradle <--- and here i want to consume it too (once projectA artifacts are published)

Actually, I think `spring-boot-dependencies` could be a very good example of it.

So the main question is, can this scenario be achieved using this plugin? If not, do you think it would be an interesting feature to add to the plugin?

Or am I being to delusional, and this could be easily achieved by other means?

**Comment by saljuama** [comment]
actually i found out that this is a duplicate of https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/164 sorry about my search fail

**Comment by wilkinsona** [comment]
No problem
