### ISSUE TITLE
<dependencyManagement> is not added to pom.xml when spring-io is applied

### ISSUE THREAD

**Issue by rwinch** [spring-gradle-plugins/dependency-management-plugin#169]
I'm not sure where the best place to log this is here or spring-io-plugin, but when spring-io plugin is applied to a project that also has the dependency management plugin, the `<dependencyManagement>` section of the pom is no longer added using Gradle 3.5. For example:

```groovy
buildscript {
	dependencies {
		classpath 'io.spring.gradle:spring-io-plugin:0.0.7.BUILD-SNAPSHOT'
		classpath 'io.spring.gradle:dependency-management-plugin:1.0.3.BUILD-SNAPSHOT'
	}
	repositories {
		maven { url 'https://repo.spring.io/plugins-release' }
		maven { url 'https://repo.spring.io/plugins-snapshot' }
	}
}

apply plugin: 'java'
// comment out spring-io plugin below and the <dependencyManagement> section is generated
apply plugin: 'spring-io'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'maven'

repositories {
	mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom 'io.spring.platform:platform-bom:1.1.1.RELEASE'
    }
}

dependencies {
	compile 'org.springframework:spring-core'
}
```

Run 

```bash
$ gradle install
$ cat build/poms/pom-default.xml                                          
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId/>
  <artifactId>gradle-dependency-management-bug</artifactId>
  <version>unspecified</version>
  <dependencies>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-core</artifactId>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

If you comment out the spring-io plugin the `<dependencyMangement>` section is rendered

**Comment by wilkinsona** [comment]
I suspect this is a duplicate of #145 and #141. The IO plugin uses 1.0.0.RC2 of the dependency management plugin. Gradle things that RC2 is a higher version than RELEASE so your configuration above will give you 1.0.0.RC2. Can you try doing something like [this](https://github.com/spring-projects/spring-restdocs/blob/master/build.gradle#L12) and see if it helps?

**Comment by rwinch** [comment]
Thanks for the fast reply @wilkinsona!

I tired using `configurations.classpath.resolutionStrategy` and it does not help.

For what its worth using a `resolutionStrategy` really should not be necessary in my example since I explicitly state the dependency-management-plugin version in the sample. When a dependency is explicitly provided it does not matter which one is "newer" because the explicitly listed version should win. I can demonstrate `dependency-management-plugin:1.0.3.BUILD-SNAPSHOT` is used in the original example by adding the following:

```groovy
println project.buildscript.configurations.classpath.asPath
```

which outputs

```bash
/home/rwinch/.gradle/caches/modules-2/files-2.1/io.spring.gradle/spring-io-plugin/0.0.7.BUILD-SNAPSHOT/b554a42ca800fbacd41c829f0d637fe8adcc2cc7/spring-io-plugin-0.0.7.BUILD-SNAPSHOT.jar
/home/rwinch/.gradle/caches/modules-2/files-2.1/io.spring.gradle/dependency-management-plugin/1.0.3.BUILD-SNAPSHOT/436766c577fe02be6df1bae3b4dd608129925c08/dependency-management-plugin-1.0.3.BUILD-SNAPSHOT.jar
```

This issue is actually an issue with the spring-io-plugin which [disables](https://github.com/spring-gradle-plugins/spring-io-plugin/blob/029d8757df6b8b09da3ea5bd1a1ca3e977d24a57/src/main/java/io/spring/gradle/springio/SpringIoPlugin.java#L55) `GeneratedPomCustomizationHandler`.

I created https://github.com/spring-gradle-plugins/spring-io-plugin/issues/5 to replace this issue
