### ISSUE TITLE
Local build project as external dependency problem

### ISSUE THREAD

**Issue by xjarkrof** [spring-gradle-plugins/dependency-management-plugin#178]
We are using multi-project gradle build and all sub projects are published and referenced as maven dependencies. We've met strange behavior. Dependency management in the log writes something like:
```
io.spring.gradle.dependencymanagement.internal.DependencyManagement] Preserving existing versions: {com.trusteca.game:lib-game-api=1.0.3-SNAPSHOT, com.trusteca.casino:core=1.0.0-SNAPSHOT, com.trusteca.game:card-deck-core=1.0.0-SNAPSHOT, com.trusteca.game:lib-game-core=1.0.3-SNAPSHOT, com.googlecode.libphonenumber:libphonenumber=8.5.0, com.trusteca.game:card-deck-api=1.0.0-SNAPSHOT, com.trusteca.game:lib-game-blackjack=1.0.3-SNAPSHOT, org.axonframework:axon-core=3.0.4, com.trusteca.casino:data=1.0.0-SNAPSHOT, com.esotericsoftware:kryo-shaded=4.0.0, org.springframework.statemachine:spring-statemachine-kryo=1.2.5.RELEASE, org.passay:passay=1.2.0, javax.inject:javax.inject=1, com.trusteca:base=1.0.0-SNAPSHOT, org.apache.commons:commons-lang3=3.5, com.trusteca.game:state-machine-core=1.0.3-SNAPSHOT, net.jcip:jcip-annotations=1.0, org.jetbrains:annotations=15.0, org.axonframework:axon-spring=3.0.4, org.eclipse.collections:eclipse-collections=8.1.0, org.hibernate.javax.persistence:hibernate-jpa-2.1-api=1.0.0.Final, com.trusteca:security=1.0.0-SNAPSHOT, org.springframework.statemachine:spring-statemachine-core=1.2.5.RELEASE, org.eclipse.collections:eclipse-collections-api=8.1.0, commons-validator:commons-validator=1.6, com.trusteca.casino:game-core=1.0.0-SNAPSHOT}
```
and later
```
[io.spring.gradle.dependencymanagement.internal.VersionConfiguringAction] Processing dependency 'com.trusteca.casino:game-core:'
11:57:14.922 [DEBUG] [io.spring.gradle.dependencymanagement.internal.VersionConfiguringAction] 'com.trusteca.casino:game-core:' is a local project dependency. Dependency management has not been applied
11:57:14.922 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Selecting new module version com.trusteca.casino:game-core:
11:57:14.922 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver] Attempting to resolve component for com.trusteca.casino:game-core: using repositories [maven, MavenRepo, MavenLocal]
11:57:14.922 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Detected non-existence of module 'com.trusteca.casino:game-core:' in resolver cache 'maven'
11:57:14.922 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Detected non-existence of module 'com.trusteca.casino:game-core:' in resolver cache 'MavenRepo'
11:57:14.922 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/xxxx/.m2/repository/com/trusteca/casino/game-core//game-core-.pom
11:57:14.923 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/xxxx/.m2/repository/com/trusteca/casino/game-core//game-core-.jar
11:57:14.923 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] No meta-data file or artifact found for module 'com.trusteca.casino:game-core:' in repository 'MavenLocal'.
```
It seems the version in this case for the sub project is undefined even the ``game-core`` sub project's build gradle contains:
```
version = '1.0.0-SNAPSHOT'
group = 'com.trusteca.casino'

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId 'com.trusteca.casino'
            artifactId jar.baseName

            from components.java

            artifact sourceJar

            pom.withXml {
                asNode().appendNode('description', "Trusteca casino game core package")
            }
        }
    }
}
```
And the dependency is not resolved...
Are we missing something ?

**Comment by wilkinsona** [comment]
I don't think you're missing anything. If I've understood your description correctly, it's a use-case that hasn't been considered. Just to confirm, you have a dependency on a project that's part of the same build, but that dependency is resolved via Maven rather than it being declared as a project dependency, correct?

**Comment by xjarkrof** [comment]
Yes, that's correct... We have sub project published to maven and used as external dependency (not project reference) in different sub project.

**Comment by wilkinsona** [comment]
This is a little bit tricky as Gradle doesn't provide any information about how a dependency was declared at the point when the plugin's deciding whether or not to apply dependency management. The means that there's no way to definitively distinguish between a project dependency and an external dependency. It would appear that the best that can be done is to look to see if the dependency has a version (project dependencies do) and only apply dependency management if it does not.

@xjarkrof Can you please provide a small sample that illustrates exactly how you're configuring things? I want to be certain that what I am considering will fix your problem. Once I know that I can decide if this is something that the plugin should support.

**Comment by xjarkrof** [comment]
@wilkinsona I've sent you an email with the sample you asked for. Did that help ?

**Comment by wilkinsona** [comment]
@xjarkrof A little, although there was quite a lot of it. One thing that I couldn't see is how you are ensuring that a project has been published before its consumed. When you use a project dependency, Gradle will take care of this for you. What are you doing to ensure that a project has been published before another project tries to consume it?

**Comment by xjarkrof** [comment]
@wilkinsona So far this is the first step to break monolith artifact to many smaller parts. Publishing has to be done manually and is done this way right now. One has to know the dependency tree (order of publishing of parts). It is not ideal, but working for now.

**Comment by wilkinsona** [comment]
Thanks for the explanation. As I said above, there's no way to distinguish between a project dependency and an external dependency, and inferring something from the presence or absence of a version comes with some risk. Unfortunately, given that your use case is rather unusual and only a temporary situation, it's rather hard to justify making a change to the plugin that will affect everyone.
