### ISSUE TITLE
Exclude does not work for transitive dependencies using Gradle 4

### ISSUE THREAD

**Issue by ewirch** [spring-gradle-plugins/dependency-management-plugin#180]
Gradle 3 handles this fine.

See [attached project](https://github.com/spring-gradle-plugins/dependency-management-plugin/files/1148675/trans-dep-fail.zip). Assemble with Gradle 4 (the included Gradle wrapper is 4). The WAR will contain `WEB-INF/lib/XmlSchema-1.1.jar`  (and duplicate file error), even though this dependency is excluded not print by `gradle dependencies`.

Build the same project using Gradle 3 and the WAR contents will be correct.

**Comment by wilkinsona** [comment]
Thanks for the sample project. This looks like a bug in Gradle to me. I can reproduce the different behaviour without using the dependency management plugin. Here's a script that's essentially doing what the dependency management plugin does under the covers:

```groovy
apply plugin: 'war'

repositories {
    jcenter()
}

configurations.all { configuration ->
    configuration.incoming.beforeResolve { resolvableDependencies ->
        resolvableDependencies.dependencies.each { dependency ->
            dependency.exclude module: 'XmlSchema'
        }
    }
}

dependencies {
    compile 'org.codehaus.xfire:xfire-jaxb2:1.2.6'
}
```

Can you please open a [Gradle](https://github.com/gradle/gradle) issue and reference this one so that it's easy for others to follow the trail?

**Comment by ewirch** [comment]
Thanks. Issue created.

**Comment by bigdaz** [comment]
Thanks for reporting this @ewirch and @wilkinsona. We are working to get a fix into 4.1-rc-1, which was scheduled for release today. Luckily, this report came in time for us to delay the RC and push in a quick-fix.

I'm don't fully understand how many users of the Spring DM plugin this affected: any functionality that changes the `excludes / transitive / changing` attributes of a `Dependency` from inside a `beforeResolve` hook could exhibit this issue.

**Comment by wilkinsona** [comment]
@bigdaz Thank you. I'm not sure how many users will be affected either but it could be quite widespread.

In addition to the explicit configuration of excludes in the original reproducer, the plugin will, by default, attempt to honour Maven exclusion semantics. With that functionality enabled, any dependency graph that has exclusions configured in the dependencies' poms will configure excludes in `beforeResolve`.

**Comment by tasneembohra** [comment]
I am facing this issue in `4.1-all`.

**Comment by anoopvalluthadam** [comment]
We also facing the same in 4.x

**Comment by wilkinsona** [comment]
@anoopvalluthadam This problem as caused by a bug in Gradle so commenting here isn't going to help.
