### ISSUE TITLE
Integrate with Ivy Publish plugin to apply managed versions to generated ivy.xml

### ISSUE THREAD

**Issue by iNikem** [spring-gradle-plugins/dependency-management-plugin#191]
Copy from https://github.com/gradle/gradle/issues/3451

Here is my build script:

```
plugins {
  id "org.springframework.boot" version "1.5.8.RELEASE"
}

apply plugin: 'ivy-publish'

group 'eu.plumbr'
version '1.0-SNAPSHOT'

repositories {
  jcenter()
}

dependencies {
  compile('org.springframework.boot:spring-boot-starter-web')
}

publishing {
  publications {
    'Main'(IvyPublication) {
      from components.java
    }
  }
}
```
The version for `org.springframework.boot:spring-boot-starter-web` dependency is not specified in the build file, it is provided by  `org.springframework.boot` plugin.

Now I generate ivy.xml for publishing with `generateDescriptorFileForMainPublication` task

The following ivy.xml is generated:
```
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0">
  <info organisation="eu.plumbr" module="test" revision="1.0-SNAPSHOT" status="integration" publication="20171110231740"/>
  <configurations>
    <conf name="compile" visibility="public"/>
    <conf name="default" visibility="public" extends="compile,runtime"/>
    <conf name="runtime" visibility="public"/>
  </configurations>
  <publications>
    <artifact name="test" type="jar" ext="jar" conf="compile"/>
  </publications>
  <dependencies>
    <dependency org="org.springframework.boot" name="spring-boot-starter-web" conf="compile-&gt;default"/>
  </dependencies>
</ivy-module>
```
### Expected Behavior
Dependency `spring-boot-starter-web` should have `rev` attribute with correct version, as required by Ivy file format.

### Current Behavior
There is no `rev` attribute so parsing this ivy file while consuming published dependency fails with `cvc-complex-type.4: Attribute 'rev' must appear on element 'dependency'`

**Comment by nyang** [comment]
May I know when this could be fixed? We ran into the same issue here.

**Comment by wilkinsona** [comment]
I have no plans to tackle this in the short to medium term as it's something of an edge case and I haven't seen sufficient demand for it to take priority over other work. If you'd like to change that, a pull request would be welcome.

**Comment by nyang** [comment]
Thanks, @wilkinsona

**Comment by wilkinsona** [comment]
It's more than 18 months since this enhancement was suggested and there's still been very little interest in it so I am going to close it. If there is an increased in demand in the future the issue can be re-opened and reconsidered.
