### ISSUE TITLE
Applying plugin unnecessarily forces dependency resolve

### ISSUE THREAD

**Issue by adrian-baker** [spring-gradle-plugins/dependency-management-plugin#194]
It appears that applying this plugin triggers resolution of dependencies even if no work is actually done by tasks, which is a performance issue (https://guides.gradle.org/performance/#don_t_resolve_dependencies_at_configuration_time).

Running incremental builds on even our moderately sized project (a composite build of two multi-project builds of 34 projects in total) results in several seconds of dependency resolution before any tasks start. Even when this is entirely hitting the gradle cache (no network requests) this becomes expensive, (I suspect it's not multi-threaded).

You can reproduce this on https://github.com/corneil/spring-data-demo by running an incremental build after a clean build. It correctly runs no tasks (I've excluded the ones that don't cache well below) yet still resolves all dependencies:

`gradle build -x test -x :spring-data-querydsl-demo:initQuerydslSourcesDir --info | grep Resolving`

**Comment by wilkinsona** [comment]
Can you please connect the dots between identifying that dependency resolution is happening unnecessarily and determining that it’s this plugin that’s causing it? Aside from when `dependencyManagement.managedVersions` is used, the plugin should only ever react to a configuration being resolved rather than initiating resolution.

**Comment by adrian-baker** [comment]
Well, I think https://github.com/corneil/spring-data-demo already shows the issue occurring, but [attached](https://github.com/spring-gradle-plugins/dependency-management-plugin/files/1526220/test.zip) is a simpler test case.

Compare:
`gradle build -Dorg.gradle.project.io.spring.dependency-management.enable=true --info | grep Resolving`
with 
`gradle build -Dorg.gradle.project.io.spring.dependency-management.enable=false --info | grep Resolving`

(after building once to fill the cache).

**Comment by adrian-baker** [comment]
( Ha, that's an interesting spot for the close button, right next to comment ! )

**Comment by adrian-baker** [comment]
...hmm, possibly I am mixing up the dependency resolving logged by this plugin with gradle's own dependency resolving.

**Comment by adrian-baker** [comment]
Ok so I think I'll close this, if there is an issue it's not the one I've described, as I've mistaken the logging from this plugin as gradle's.

If I use the --profile mode, the resulting report shows that the compileClasspath is resolved with or without this plugin, so it seems my hope that resolution would be skipped during a skipped compile task is wrong.

What I do notice is that there seems to be a lot of extra detached configurations added and resolved - possibly the cumulative number of these adds to resolve time ? I'd need a larger scale test case to compare, but is this something you'd expect?

**Comment by wilkinsona** [comment]
> What I do notice is that there seems to be a lot of extra detached configurations added and resolved (when using the plugin) - possibly the cumulative number of these adds to resolve time ? I'd need a larger scale test case to compare, but is this something you'd expect?

The plugin uses detached configurations for two things:

1. Resolving imported boms
2. Resolving dependencies' poms to apply Maven exclusions properly

Both of these will only happen if something else has already triggered the resolution of a configuration.

If you're happy to possibly need exclusions in your Gradle scripts that you wouldn't need with Maven, you can avoid the latter by telling the plugin not to apply Maven exclusions:

```
dependencyManagement {
    applyMavenExclusions = false
}
```

The former is missing a slight optimisation. A detached configuration will be created and resolved even if no boms have been imported. This is very quick as far as I can tell (it's reported as having 0s duration) but it's unnecessary nonetheless. I've opened https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/195.

**Comment by adrian-baker** [comment]
I just ran a quick test with `applyMavenExclusions = false`, and it made a significant difference. Full elapsed time for the build dropped from about 5.8s to about 4.2s. Time reported in dependency resolution using `--profile` dropped from 1.76s to 0.12s.

We only have a single bom import currently, it didn't seem to make any measureable difference with or without this.

I'll leave `applyMavenExclusions` disabled as I think this essentially solves my problem - thank you - however I do wonder if that means the default settings give rise to quite a performance overhead, possibly much larger than just the bom issue?

**Comment by adrian-baker** [comment]
Also, originally I had 1,288 total configurations reported in the gradle, which dropped to 388 after disabling `applyMavenExclusions`, so still around 10 extra detached configurations per project.

In my toy example above, `--profile` reports:
- plugin disabled => zero detached configurations
- plugin enabled,  applyMavenExclusions disabled => 5 detached configurations
- plugin enabled, applyMavenExclusions  enabled => 9 detached configurations

**Comment by wilkinsona** [comment]
> however I do wonder if that means the default settings give rise to quite a performance overhead, possibly much larger than just the bom issue?

There's definitely a performance overhead, although it should be lower than you're seeing. One of the main features of the plugin is for exclusions declared in Maven poms to behave as Maven intended, so I think it's right for the feature to be enabled by default.

The numbers from your toy project look right to me. I'd expect the calculation of Maven-style exclusions to create one detached configuration per normal configuration that's resolved. That doesn't match with a drop from 1288 to 388 in your proper project, though. Can you share an example that exhibits a drop of more than 50% in the total number of configurations as your proper projects is exhibiting?
