### ISSUE TITLE
Generating POM following gradle example outside of maven install fails to produce valid pom

### ISSUE THREAD

**Issue by jarheadjred** [spring-gradle-plugins/dependency-management-plugin#199]
Generated new project from initializr against boot 1.5.9.RELEASE, included a cloud dependency to generate a bom import in the dependencyManagement block.

Set bootRepackage.enabled = false (because project is building a library, not an executable fat jar)

added a task generatePom that uses pom{}.writeTo and made build depend on it.

Run `./gradlew build` and inspect the pom generated in the `build/libs` directory. It has no artifact versions. 

If you run `./gradlew install` and inspect the pom generated in the default location `build/pom` it has artifact versions as expected. 

I would expect the pom generated directly through pom task or through install to have been the same.

build.gradle to reproduce:

```
buildscript {
	ext {
		springBootVersion = '1.5.9.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'maven'
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'

group = 'com.broken.pom'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
}

ext {
	springCloudVersion = 'Edgware.RELEASE'
}

dependencies {
	compile('org.springframework.cloud:spring-cloud-starter')
	compile('org.springframework.boot:spring-boot-starter-web')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

// following gradlew docs for writing pom outside of publishing etc... https://docs.gradle.org/current/userguide/maven_plugin.html#sec:maven_convention_methods
task generatePom {
    doLast {
        pom().writeTo("$buildDir/libs/${project.name}-${project.version}.pom")
    }
}
build.dependsOn(generatePom)

bootRepackage.enabled = false
```

**Comment by wilkinsona** [comment]
> I would expect the pom generated directly through pom task or through install to have been the same.

As would I. It looks like you've found a bug. Thanks for the report and the script that reproduces the problem.

The following build script will also reproduce the problem, but in a slightly simpler way as it doesn't use Spring Boot's Gradle plugin:

```groovy
buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("io.spring.gradle:dependency-management-plugin:1.0.4.RELEASE")
	}
}

apply plugin: 'maven'
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'io.spring.dependency-management'

group = 'com.broken.pom'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
}

dependencies {
	compile('org.springframework.boot:spring-boot-starter-web')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.boot:spring-boot-dependencies:1.5.9.RELEASE"
	}
}

task generatePom {
	doLast {
		pom().writeTo("$buildDir/libs/${project.name}-${project.version}.pom")
	}
}

build.dependsOn(generatePom)
```

**Comment by wilkinsona** [comment]
I was mistaken when I commented on this earlier. I'd failed to spot that there's no explicit customisation being attempted. As [described in the README](https://github.com/spring-gradle-plugins/dependency-management-plugin#configuring-your-own-pom), if you're generating a pom outside of the mechanisms provided by Gradle's `maven` and `maven-publish` plugins you'll need to customise it. In the case of the original example, you can do so like this:

```groovy
task generatePom {
	doLast {
		pom().withXml(dependencyManagement.pomConfigurer)
			.writeTo("$buildDir/libs/${project.name}-${project.version}.pom")
	}
}
```
