### ISSUE TITLE
Honour Maven exclusions

### ISSUE THREAD

**Issue by wilkinsona** [spring-gradle-plugins/dependency-management-plugin#2]
A Maven bom may contain exclusions in its dependency management, as shown in this snippet taken from [Maven's documentation](http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management):

```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>group-a</groupId>
            <artifactId>artifact-a</artifactId>
            <version>1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>group-c</groupId>
                    <artifactId>excluded-artifact</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        …
    </dependencies>
</dependencyManagement>
```

The exclusion of `group-c:excluded-artifact` from `group-a:artifact-a`'s dependencies should be honoured by the plugin. A direct or transitive dependency on `group-a:artifact-a` should never cause `group-c:excluded-artifact` to be on the classpath.

**Comment by stangls** [comment]
Is there another way to achieve automatic exclusion of transitive artifacts?

**Comment by wilkinsona** [comment]
This issue is closed and has been implemented. Why do you need "another way"?
