### ISSUE TITLE
Plugin together with Exceltion JET Gradle plugin causes OOM

### ISSUE THREAD

**Issue by Crazyjavahacking** [spring-gradle-plugins/dependency-management-plugin#201]
Hi,

on our build this plugin together with Excelsior JET's plugin causes OOM on second run of Gradle. It's hard to understand why, but it looks like for some reason Excelsior JET Gradle plugin somehow stores references to objects of Spring dependency plugin.

I was wondering if you can help analyze the [heap dump](https://drive.google.com/file/d/1FPMMCXFbucyTzHaK578AFBAwM-e2pJyY/view).

[JET plugin issue](https://github.com/excelsior-oss/excelsior-jet-gradle-plugin/issues/39)

**Comment by wilkinsona** [comment]
There's no need for a separate issue (at this stage at least), please just mention me on the JET issue.

**Comment by Crazyjavahacking** [comment]
Done, thanks.
