### ISSUE TITLE
Is it possible to use this with android?

### ISSUE THREAD

**Issue by robbypond** [spring-gradle-plugins/dependency-management-plugin#202]
This plugin doesn't seem to work with Android applications/libraries. It doesn't appear to recognize the configurations that android uses (implementation instead of compile, etc).

**Comment by wilkinsona** [comment]
Yes, it should be possible. The plugin doesn't care about the names of the configurations. What, precisely, does "doesn't seem to work" mean? What did you expect to happen and what actually happened? Can you provide an example that reproduces the behaviour you're seeing?

**Comment by robbypond** [comment]
It appears to be trying to resolve dependencies via the configured maven repos when it is omitting the versions specified in the dependencyManagement extension.  

Example output below:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:androidDependencies'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not find com.android.support:appcompat-v7:.
     Searched in the following locations:

A sample project is attached.

[testapp.tar.gz](https://github.com/spring-gradle-plugins/dependency-management-plugin/files/1675915/testapp.tar.gz)

**Comment by wilkinsona** [comment]
Dependency management isn't inherited and you have only configured it on the root project. As a result, your app project has no dependency management so its dependencies fail to resolve. If you want the app project to use dependency management, you could move the dependency management configuration into `allprojects` or declare it in a new `subprojects` block.
