### ISSUE TITLE
Add flag to exclude local dependency check

### ISSUE THREAD

**Issue by Alexuy** [spring-gradle-plugins/dependency-management-plugin#203]
Hi, guys!

First of all, I would like to thank you for the your work. Your plugin is really very convenient and it helps us a lot.

Now about the problem I faced:

I have created several projects:

```groovy
bm-utils
bm-test
```

All of them have their own build-scripts and can be collected independently.

The bm-test has a dependence on bm-utils, i.e. he is registered with:

```groovy
dependencies "com.bm.common:bm-utils"
```

The version automatically substitutes your plugin from the BOM-file. In my case, it's 'latest.release'.

Because modules are not very large, I wrapped them with a root build file and marked them as submodules in the GIT. received the following structure:
```groovy
common
  - bm-utils
  - bm-test
```

What happened in the end:

When I start the gradle build from the root project, I get an error:

```groovy
Could not resolve all files for configuration ': bm-test: compileClasspath'.
Could not find com.bm.common: bm-utils :.
Required by:
project: bm-test
```

After reviewing the logs, I saw this line:
```groovy
15: 18: 45.289 [DEBUG] [io.spring.gradle.dependencymanagement.internal.VersionConfiguringAction] 'com.bm.common: bm-utils:' is a local project dependency. Dependency management has not been applied
```

Please, make it possible to disable this check

**Comment by wilkinsona** [comment]
Before we consider introducing a way to disable that check, I'd like to understand the problem in a bit more detail. Right now, I don't think I understand why you'd want to run a build that builds the `bm-utils` project but use a different version of `bm-utils` that's resolved from a repository. Can you explain a bit more about what you're trying to achieve with your build's configuration?

**Comment by Alexuy** [comment]
Now, if i want to use bm-utils in bm-test, i must write:

```groovy
compile "com.bcs.bm.common:bm-utils:latest.release"
```

But i want to write:

```groovy
compile "com.bcs.bm.common:bm-utils"
```

but in this case I have a error

```groovy
Could not resolve all files for configuration ': bm-test: compileClasspath'.
Could not find com.bm.common: bm-utils :.
Required by:
project: bm-test
```

I want to get rid of specifying specific versions in build-scripts and that the versions of all libraries are contained in one BOM file.

Again: bm-utils and bm-test can have different versions, but i work with them by aggregation root project (just for convenience).

**Comment by Alexuy** [comment]
More details about my case.

1. I have 2 different modules - bm-utils and bm-test. Each of them has its own repository and its own version.

2. Both modules import bm-dependencies into the BOM file:
```groovy
dependencyManagement {
    imports {
        mavenBom "com.bm.common:bm-dependencies:$ver.bmDependencies"
    }
    resolutionStrategy {
        cacheDynamicVersionsFor 5, 'minutes'
        cacheChangingModulesFor 0, 'minutes'
    }
}
```

3. In bm-dependencies BOM-file i set dynamic version for bm-utils:

```groovy
dependency "com.bm.common:bm-utils:latest.release"
```

4. bm-test module has dependecy to bm-utils module without version:

```groovy
dependency "com.bm.common:bm-utils"
```

4. When I open these modules separately from each other - all works fine and dependencyManagement-plugin works perfect!

And what i want to do and about my problem:

1. I create aggregation GIT-repository with name common and link bm-utils and bm-test as submodules in that repository.

2. I create build.gradle file in that common repository and set in gradle.settings file:

```groovy
include 'bm-utils'
include 'bm-test'
```

3. I open common project as Intellij IDEA and all works perfect - i have root-project with name 'common' and 2 modules - bm-utils and bm-test.

But now i have one problem: your plugin found in my workspace module with name "com.bm.common:bm-utils" and tell me, that he skip it:

```groovy
15: 18: 45.289 [DEBUG] [io.spring.gradle.dependencymanagement.internal.VersionConfiguringAction] 'com.bm.common:bm-utils:' is a local project dependency. Dependency management has not been applied
```
and i don't want to set local project dependency, because somebody from my team can clone module bm-test without a root repo (common).

I hope you understand what I'm talking about.

If you need to provide something else - tell me.

**Comment by wilkinsona** [comment]
Thanks. My feeling at the moment is that this is too much of an edge case to warrant the extra complexity that a flag will introduce. I'm a little sceptical at the moment that the configuration you've described is working as exactly as described. My suspicion is that you'd need to be using a `project` dependency. Can you please provide a small sample that reproduces the behaviour you're seeing. It may be possible to make the plugin's logic that determines that a dependency is local a little more sophisticated. That may allow your use case to be accommodated without the complexity of a configuration flag.

**Comment by Alexuy** [comment]
Hi!

That's my project structure with scripts:

├── bm-test
│   └── build.gradle
├── bm-utils
│   └── build.gradle
├── build.gradle
└── settings.gradle

Files:

1. bm-test/build.gradle:

```groovy
apply plugin: 'java'

group = 'com.bm.common'
version = '1.0.0'

buildscript {
    ext {
        ver = [
                bmDependencies      : 'latest.release',
                dependencyManagement: '1.0.4.RELEASE'
        ]
    }

    repositories {
        maven { url LOCAL_REPO}
    }

    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:$ver.dependencyManagement"
    }
}

apply plugin: 'io.spring.dependency-management'
apply plugin: 'maven-publish'

dependencyManagement {
    imports {
        mavenBom "com.bm.common:bm-dependencies:$ver.bmDependencies"
    }
    resolutionStrategy {
        cacheDynamicVersionsFor 5, 'minutes'
        cacheChangingModulesFor 0, 'minutes'
    }
}

repositories {
    rootProject.buildscript.repositories.each {
        repositories.add(it)
    }
}

dependencies {

    // version must be set, before not fix https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/203
    compile "com.bm.common:bm-utils"

}

publishing {

    repositories {
        maven {
            url LOCAL_UPLOAD_REPO
            credentials {
                username LOCAL_USER
                password LOCAL_PASSWORD
            }
        }
    }

    publications {
        mavenJava(MavenPublication) {

            groupId rootProject.group
            artifactId archivesBaseName
            version rootProject.version

            from components.java
        }
    }
}
```

2. bm-utils/build.gradle
```groovy
apply plugin: 'java'

group = 'com.bm.common'
version = '1.0.0'

buildscript {
    ext {
        ver = [
                bmDependencies      : 'latest.release',
                dependencyManagement: '1.0.4.RELEASE'
        ]
    }

    repositories {
        maven { url LOCAL_REPO }
    }

    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:$ver.dependencyManagement"
    }
}

apply plugin: 'io.spring.dependency-management'
apply plugin: 'maven-publish'

dependencyManagement {
    imports {
        mavenBom "com.bm.common:bm-dependencies:$ver.bmDependencies"
    }
    resolutionStrategy {
        cacheDynamicVersionsFor 5, 'minutes'
        cacheChangingModulesFor 0, 'minutes'
    }
}

repositories {
    rootProject.buildscript.repositories.each {
        repositories.add(it)
    }
}

task sourceJar(type: Jar) {
    from sourceSets.main.allJava
}

publishing {

    repositories {
        maven {
            url LOCAL_UPLOAD_REPO
            credentials {
                username LOCAL_USER
                password LOCAL_PASSWORD
            }
        }
    }

    publications {
        mavenJava(MavenPublication) {

            groupId rootProject.group
            artifactId archivesBaseName
            version rootProject.version

            from components.java
        }
    }
}
```

3. root/build.gradle

```groovy
group = 'com.bm.common'

buildscript {
    repositories {
        maven {
            url { LOCAL_REPO }
        }
    }
}

version = '1.0.0'

allprojects {
    repositories {
        rootProject.buildscript.repositories.each {
            repositories.add(it)
        }
    }
}
```
4. settings.gradle
```groovy
include 'bm-utils'
include 'bm-test'
```
bm-dependecnies BOM known version bm-utils

Cases for reproduce (before you must set BOM artifact and artifactory):

**Case 1. ** In directory bm-test try run 'gradle build'. Result:
```bash
$ gradle build
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':bm-test:compileClasspath'.
> Could not find com.bm.common:bm-utils:.
  Required by:
      project :bm-test

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
15 actionable tasks: 15 executed
Could not find com.bm.common:bm-utils:.
Required by:
    project :bm-test

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Case 2.** copy bm-test to another dir and again try run 'gradle build'. Result:
```bash
$ gradle build

BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed
```

**Case 3:** if i replace dependency to
```groovy
compile "com.bm.common:bm-utils:latest.release"
``` 
all works fine

**Comment by wilkinsona** [comment]
Thanks. I've managed to piece something together from the above that reproduced the problem.

> But I need jar artifact dependecy from artifactory.

This is what I suspect when I said the following:

> I'm a little sceptical at the moment that the configuration you've described is working as exactly as described. My suspicion is that you'd need to be using a project dependency.

Combining multiple projects into a single build and yet expecting the dependency to be resolved from a repository rather than the project in the build is definitely an edge case. FWIW, if I was working on a project with this build structure I'd find it confusing and would want to change it to be more conventional.

I wondered above if it would be possible to make the plugin's local project detection more sophisticated. Unfortunately, that doesn't appear to be the case as the `DependencyResolveDetails` that is available when the determination is being made doesn't provide enough information. That leaves the option of adding a flag.

Any flag would have to be described in the documentation. A description would need to explain when it's needed and, as far as I can tell, that would only be for your unusual build arrangement. I think the arrangement is too unusual to warrant a user-facing configuration option so I am not going to add a flag for this.
