### ISSUE TITLE
When multiple imported boms manage the same version, dependency management in the generated pom may provide different versions

### ISSUE THREAD

**Issue by Alvise88** [spring-gradle-plugins/dependency-management-plugin#204]
Before you can start you have to publish override-bom on maven local (otherwise you don't have the bom installed).
After you are able to see the strange Behavior deleting one of the following comment:

            //mavenBom("dm-issue:override-bom:1.0-SNAPSHOT") //pom output 23.6 guava (idea use 18 version)
            mavenBom 'org.springframework.cloud:spring-cloud-dependencies:Edgware.SR2'
            //mavenBom("dm-issue:override-bom:1.0-SNAPSHOT") //pom output 18 guava (idea use 23.6 version)
[dm-issue.zip](https://github.com/spring-gradle-plugins/dependency-management-plugin/files/1759135/dm-issue.zip)

**Comment by wilkinsona** [comment]
What do you mean by "pom output"? When multiple boms manage the same dependency, the last bom should win. In this case that means that I'd expect Guava's version to be 23.6 when the override bom goes last and to be 18.0 when the Spring Cloud bom goes last. That's the behaviour that I see in Gradle's dependencies output.

**Comment by Alvise88** [comment]
In the following case:
            mavenBom 'org.springframework.cloud:spring-cloud-dependencies:Edgware.SR2'
            mavenBom("dm-issue:override-bom:1.0-SNAPSHOT") //pom output 18 guava (idea use 23.6 version)

my expectation was guava 23.6 in the pom; instead i see the following output:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>dm-issue</groupId>
  <artifactId>use-override-bom</artifactId>
  <version>1.0-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <scope>compile</scope>
    </dependency>
  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>18.0</version>
      </dependency>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>1.5.10.RELEASE</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>Edgware.SR2</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
      <dependency>
        <groupId>dm-issue</groupId>
        <artifactId>override-bom</artifactId>
        <version>1.0-SNAPSHOT</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>


```

**Comment by wilkinsona** [comment]
Aah, it's the generated pom that contains the problem. Thanks, I've got you now.
