### ISSUE TITLE
[Help Request] Build unable to resolve dependency version

### ISSUE THREAD

**Issue by boonware** [spring-gradle-plugins/dependency-management-plugin#209]
I have a project, let's call it Project A, which using the Spring IO Platform BOM for dependency management. I've published the artifact using the Maven Publish plugin. Its POM looks like so:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.some.company</groupId>
  <artifactId>artifact-a</artifactId>
  <version>1.2.3</version>
  <dependencies>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-collections4</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.spring.platform</groupId>
        <artifactId>platform-bom</artifactId>
        <version>Athens-SR6</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
  </dependencyManagement>
</project>

```

I have another project, let's call this one Project B, which uses Artifact A as a dependency. Project A also defines some additional dependencies. B's dependencies look like so:

```
dependencyManagement {
        dependencies {
            dependency "commons-io:commons-io:${LIB_COMMONS_IO}"
            dependency "org.apache.commons:commons-collections4:${LIB_COMMONS_COLLECTIONS}"
            dependency "com.google.guava:guava:${LIB_GOOGLE_GUAVA}"
        }
    }

    dependencies {
        compile 'commons-io:commons-io'
        compile 'org.apache.commons:commons-collections4'
        compile 'com.google.guava:guava'
        compile 'org.some.company:artifact-a:1.2.3
    }
```

Note that the variables for the versions are indeed defined and valid. Both projects A and B apply the Spring Dependency Management Plugin. When running my build, Gradle complains:
```
Unable to resolve version for dependency 'org.apache.commons:commons-collections4:jar'
```
Note that this error occurs while the build is resolving the POM for Artifact A, even though the dependency's version is defined in the Spring IO Platform BOM, which is a transitive dependency under the `dependencyManagement` section of the POM.

What's going on here? If I remove the BOM from Project A and instead add the dependency versions directly to Project A's build then the build for Project B _is_ able to find the version for `commons-collections4`. It seems that the build is not using the Spring IO Platform BOM to resolve the transitive dependency versions for Artifact A.

I'm wondering if I'm also seeing https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/164, but not totally sure. If that is the case, the question becomes: how can a Gradle project resolve the transitive dependency versions for a dependency that uses a BOM to manage its transitive dependency versions?

**Comment by wilkinsona** [comment]
It's been 4 weeks with no feedback. Closing.
