### ISSUE TITLE
Transitive dependencies overridden by bom

### ISSUE THREAD

**Issue by pmendelski** [spring-gradle-plugins/dependency-management-plugin#210]
Hi,

Transitive dependencies of a dependency defined in `build.gradle` are overridden by dependencies declared in the imported bom.

## Dependencies without the dependency-management-plugin

**build.gradle**
```
plugins {
  id 'java'
}

repositories {
  mavenCentral()
}

dependencies {
  compile 'org.elasticsearch.client:transport:6.1.3'
}

task wrapper(type: Wrapper) {
  gradleVersion = '4.7'
}
```

**Result**
```
./gradlew dependencyInsight --configuration compile --dependency transport-netty4-client

> Task :dependencyInsight
org.elasticsearch.plugin:transport-netty4-client:6.1.3
\--- org.elasticsearch.client:transport:6.1.3
     \--- compile
```

Transitive dependency `transport-netty4-client` is in `6.1.3` version as expected.

## Dependencies with the dependency-management-plugin

**build.gradle**
```
plugins {
  id 'java'
  id 'io.spring.dependency-management' version '1.0.5.RELEASE'
}

repositories {
  mavenCentral()
}

dependencyManagement {
  imports {
    mavenBom 'org.springframework.boot:spring-boot-dependencies:2.0.1.RELEASE'
  }
}

dependencies {
  compile 'org.elasticsearch.client:transport:6.1.3'
}

task wrapper(type: Wrapper) {
  gradleVersion = '4.7'
}
```

**Result**
```
./gradlew dependencyInsight --configuration compile --dependency transport-netty4-client       

> Task :dependencyInsight
org.elasticsearch.plugin:transport-netty4-client:5.6.8 (selected by rule)
   variant "runtime"

org.elasticsearch.plugin:transport-netty4-client:6.1.3 -> 5.6.8
   variant "runtime"
\--- org.elasticsearch.client:transport:6.1.3
     \--- compile
```
Transitive dependency `transport-netty4-client` is in `5.6.8` version.
Its version was overridden by the version declared in [spring-boot-dependencies:2.0.1.RELEASE](http://central.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.0.1.RELEASE/spring-boot-dependencies-2.0.1.RELEASE.pom)

## Final thoughts

I am not sure if this is the desired behavior but IMHO it makes any project hard to maintain. Every transitive dependency that was added to the project must be checked if it was not overridden in the imported bom. For example the [spring-boot-dependencies](http://central.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.0.1.RELEASE/spring-boot-dependencies-2.0.1.RELEASE.pom) defines 485 dependencies where some of the are other boms.

In my opinion the desired behavior is to **not** override transitive dependency versions.
Is there any option to apply such a policy?

**Comment by wilkinsona** [comment]
> In my opinion the desired behavior is to not override transitive dependency versions.

That's not how Maven's dependency management behaves and this plugin's aim is to mimic Maven's behaviour.

> Is there any option to apply such a policy?

No, and it doesn't make sense to add one as it would mean that the plugin no longer achieve its primary goal.

**Comment by wilkinsona** [comment]
If you want to use a version of Elasticsearch other than that defined in `spring-boot-dependencies`, you should override the `elasticsearch.version` property and then declare any direct Elasticsearch dependencies without a version:

```
ext['elasticsearch.version'] = '6.1.3'

dependencies {
  compile 'org.elasticsearch.client:transport'
}
```

**Comment by pmendelski** [comment]
This way I still need to know all the dependencies declared in `spring-boot-dependencies` or at least all the `*.version` properties (there are 174 of them).

**Comment by wilkinsona** [comment]
Indeed you do, which is why Spring Boot documents them in its reference guide. This plugin's `dependencyManagement` task will also list all of the managed versions.

**Comment by pmendelski** [comment]
Ok, many thanks for explanation.
It seems I just need to change my expectations - stoic wisdom ;)

**Comment by pmendelski** [comment]
Although I still have problem with this solution.

Let's assume that someone forgot about the fact that a dependency is declared in `spring-boot-dependencies`. Then problems may happen in runtime, potentially on a production environment. The only way to avoid this situation is to test the dependencies.

**Comment by wilkinsona** [comment]
> Then problems may happen in runtime, potentially on a production environment. The only way to avoid this situation is to test the dependencies.

That applies to any approach to controlling the versions of your dependencies. If the bom didn't change the version of transitive dependencies then you may end up using a version with which Spring Boot isn't known to be compatible.

**Comment by pmendelski** [comment]
Spring-boot is a big set of libraries. I haven't seen a project that uses all of them. Nevertheless transitive dependencies are overridden. I don't that mind that `spring-boot-starter-data-elasticsearch` has wrong dependency on my classpath because I don't use it. The potential threat of non-trivial dependency issues is far greater then the gains.

**Comment by wilkinsona** [comment]
Then don’t use the bom. No one is forcing you to do so.

**Comment by pmendelski** [comment]
Yes... we could end this discussion here or create a feature request out of it.

**Comment by vpavic** [comment]
@pmendelski I don't know if you're aware that Gradle 4.6+ includes a preview of new improved POM support feature that's actually handling transitive dependencies as you expect. You can learn more about this feature [here](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html). There are also a couple of Gradle issues that contain some interesting discussions and provide some background - see gradle/gradle#1162 and gradle/gradle#4979
