### ISSUE TITLE
Allow dependency without version for exclusion purposes

### ISSUE THREAD

**Issue by pelepelin** [spring-gradle-plugins/dependency-management-plugin#217]
Hello!

Here is a build.gradle

```
buildscript {
	ext {
		springBootVersion = '2.0.2.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group = 'com.example'
version = '0.0.1-SNAPSHOT'

repositories {
	mavenCentral()
}

dependencies {
	compile('org.springframework.boot:spring-boot-starter-web',
            'org.springframework.boot:spring-boot-starter-jetty')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
	dependencies {
		dependency("org.springframework.boot:spring-boot-starter-web:${springBootVersion}") {
			exclude 'org.springframework.boot:spring-boot-starter-tomcat'
		}
	}
}
```

As you see, while Spring Boot plugin applies versions to all dependencies, for the exclusion block I need to specify `springBootVersion` second time. More, I can't use variables within `plugins {}` block if I want to switch to that DSL so I would need to duplicate a string literally (I don't know if the plugin exposes its own version as a variable).

What I want:

For the purposes of dependency exclusion, it could be allowed to specify a dependency without a version:
```
dependencyManagement {
	dependencies {
		dependency("org.springframework.boot:spring-boot-starter-web") {
			exclude 'org.springframework.boot:spring-boot-starter-tomcat'
		}
	}
}
```

**Comment by wilkinsona** [comment]
They are only applicable to exclusions declared in a Maven pom:

> This applies to exclusions declared in a project's dependencies that have a Maven pom and exclusions declared in imported Maven boms.

**Comment by pelepelin** [comment]
> The two main advantages of using this mechanism are that they will be included in the <dependencyManagement> of your project's generated pom and that they will be applied using Maven's exclusion semantics.

Do I understand correctly that if I add exclusions using [gradle's built-in DSL](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:excluding_transitive_module_dependencies) and then my project is added as a dependency to another project (Maven or Gradle), exclusions are not applied, but if my project applies exclusions using this module's DSL, they are still applied?

If that's the case, then it's a valid usecase.

**Comment by wilkinsona** [comment]
It depends on how you have configured the exclusion and any customisations that have been made to the pom that Gradle generates. For example, if you declare the exclusion on the dependency, I believe Gradle will add an `<exclusion>` to the generated pom.

I'm closing this issue as what you're looking to do is out of the scope of this plugin and, dependency on how you use it, is already supported by Gradle.

**Comment by peter-he-by** [comment]
It is still not working for example in multiple subprojects
in projectA, upgrade HikariCP to 4.0.2 by the following script
compile('com.zaxxer:HikariCP:4.0.2!!')
compile('org.springframework.boot:spring-boot-starter-data-jpa:2.2.8.RELEASE'){
  exclude group 'com.zaxxer': module 'HikariCP;
}
in project B: build.gralde script like the following line:
compile project(':projectA')

HikariCP change back to 3.4.5 which is transitive depends on 'org.springframework.boot:spring-boot-starter-data-jpa:2.2.8.RELEASE'

**Comment by wilkinsona** [comment]
@peter-he-by I can't see the connection with the rest of this issue as you aren't trying to configure any exclusions. The behaviour that you are seeing may well be expected. If project B has dependency management applied to it, the version declared in the dependency management will win. If that's not the case and you believe you've found a bug, please open a new issue with a complete and minimal example.
