### ISSUE TITLE
A managed dependency with a classifier in an imported bom can override dependency management for the same dependency with no classifier

### ISSUE THREAD

**Issue by jolivares** [spring-gradle-plugins/dependency-management-plugin#218]
I have the following BOM:
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.github.jolivares</groupId>
	<artifactId>platform-parent</artifactId>
	<version>000.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>Jolivares platform parent pom</name>
	
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.dropwizard.metrics</groupId>
				<artifactId>metrics-bom</artifactId>
				<scope>import</scope>
				<type>pom</type>
				<version>4.0.2</version>
				<exclusions>
					<exclusion>
						<groupId>org.eclipse.jetty</groupId>
						<artifactId>jetty-servlet</artifactId>
					</exclusion>
				</exclusions>
			</dependency>

			<dependency>
				<groupId>org.eclipse.jetty</groupId>
				<artifactId>jetty-servlet</artifactId>
				<version>9.4.11.v20180605</version>
			</dependency>
			<dependency>
				<groupId>org.eclipse.jetty</groupId>
				<artifactId>jetty-server</artifactId>
				<version>9.4.11.v20180605</version>
			</dependency>

		</dependencies>
	</dependencyManagement>
</project>
```
Which leads to the following effective pom (I will just focus on jetty-servlet):
```
mvn help:effective-pom | grep jetty-servlet -B 2 -A 3

      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-servlet</artifactId>
        <version>9.4.11.v20180605</version>
      </dependency>
      <dependency>
--
--
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-servlet</artifactId>
        <version>9.4.8.v20171121</version>
        <classifier>tests</classifier>
        <scope>test</scope>
```
The first `<dependency>` is the one defined by me, the second one comes from `io.dropwizard.metrics` pom.

Now if I use it on a mvn project:
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.github.jolivares</groupId>
	<artifactId>test-import-bom</artifactId>
	<version>000.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>Jolivares test import pom</name>
	
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.github.jolivares</groupId>
				<artifactId>platform-parent</artifactId>
				<scope>import</scope>
				<type>pom</type>
				<version>000.1-SNAPSHOT</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-servlet</artifactId>
		</dependency>
	</dependencies>
</project>
```
It uses the jetty-servlet version I defined (9.4.11.v20180605):
```
mvn dependency:tree
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------< com.github.jolivares:test-import-bom >----------------
[INFO] Building Jolivares platform parent pom 000.1-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ test-import-bom ---
[INFO] com.github.jolivares:test-import-bom:pom:000.1-SNAPSHOT
[INFO] \- org.eclipse.jetty:jetty-servlet:jar:9.4.11.v20180605:compile
[INFO]    \- org.eclipse.jetty:jetty-security:jar:9.4.11.v20180605:compile
[INFO]       \- org.eclipse.jetty:jetty-server:jar:9.4.11.v20180605:compile
[INFO]          +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO]          +- org.eclipse.jetty:jetty-http:jar:9.4.11.v20180605:compile
[INFO]          |  \- org.eclipse.jetty:jetty-util:jar:9.4.11.v20180605:compile
[INFO]          \- org.eclipse.jetty:jetty-io:jar:9.4.11.v20180605:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.914 s
[INFO] Finished at: 2018-07-12T08:39:08+02:00
[INFO] ------------------------------------------------------------------------
```
But If I use it in gradle by means of this plugin:
```
buildscript {
    repositories {
        maven { url 'https://repo.spring.io/plugins-snapshot' }
        mavenLocal()
    }
    dependencies {
        classpath 'io.spring.gradle:dependency-management-plugin:1.0.5.RELEASE'
    }
}

apply plugin: 'java'
apply plugin: 'io.spring.dependency-management'

repositories {
    mavenLocal()
    mavenCentral()
    jcenter()
}

dependencyManagement {
     imports {
          mavenBom 'com.github.jolivares:platform-parent:000.1-SNAPSHOT'
     }
}

dependencies {
     compile 'org.eclipse.jetty:jetty-servlet'
}
```
It selects the dependency declared by `io.dropwizard.metrics` (9.4.8.v20171121) which, in addition, is defined for a  different scope (test):
```
 gradle -q dependencyInsight --dependency jetty-servlet
org.eclipse.jetty:jetty-servlet:9.4.8.v20171121 (selected by rule)
   variant "default" [
      org.gradle.status = release (not requested)
      Requested attributes not found in the selected variant:
         org.gradle.usage  = java-api
   ]

org.eclipse.jetty:jetty-servlet -> 9.4.8.v20171121
   variant "default" [
      org.gradle.status = release (not requested)
      Requested attributes not found in the selected variant:
         org.gradle.usage  = java-api
   ]
\--- compileClasspath
```
To mee it looks like a bug. Is this plugin somehow storing the dependencies from the pom in some map regardless of the dependency scope, and for this reason the second occurrence of the same dependency (but with different scope) is overriding the first one?

**Comment by wilkinsona** [comment]
Thanks for the report. I think I understand but it's difficult to be sure. Can you please provide small Maven and Gradle sample projects that illustrate the different behaviour?

Also, I am a little confused by the exclusion in your bom:

```
<dependency>
	<groupId>io.dropwizard.metrics</groupId>
	<artifactId>metrics-bom</artifactId>
	<scope>import</scope>
	<type>pom</type>
	<version>4.0.2</version>
	<exclusions>
		<exclusion>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-servlet</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

I don't believe it will have any effect as, AFAIK, `jetty-servlet` is not a transitive dependency of `metrics-bom`. It's managed by the metrics bom but I don't think the exclusion will stop that dependency management from being imported. Can you please clarify what the exclusion does or what it is intended to do?

**Comment by jolivares** [comment]
Sorry for the confusion with the `<exclusions>` in the BOM import. I was just trying several options to check If I could make it work. But as you said it has no effect. There's still an open issue to have that working in maven: https://issues.apache.org/jira/browse/MNG-5600

I will try to provide the sample projects.

**Comment by jolivares** [comment]
Here you are
 - test-maven-bom: mvn project declaring BOM
 - test-import-maven-bom: mvn project using the BOM
 - test-gradle-bom: gradle project using the BOM

[BOM-projects.zip](https://github.com/spring-gradle-plugins/dependency-management-plugin/files/2187658/BOM-projects.zip)

**Comment by wilkinsona** [comment]
Thanks. I've reproduced the problem and understand the problem now.

The problem is caused by these two dependency management entries:

```xml
<dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-servlet</artifactId>
    <version>9.4.11.v20180605</version>
</dependency>
<dependency>
    <groupId>org.eclipse.jetty</groupId>
    <artifactId>jetty-servlet</artifactId>
    <version>9.4.8.v20171121</version>
    <classifier>tests</classifier>
    <scope>test</scope>
</dependency>
```

The plugin doesn't differentiate between the dependency with no classifier and the dependency with the `tests` classifier. Due to the order in which they appear in the effective bom, the latter then overrides the former and the managed version for `jetty-servlet` becomes `9.4.11.v20180605`.

Gradle's support for classifiers is inadequate for this plugin to fully support Maven's behaviour. For example, a dependency's classifier isn't available during dependency resolution. This makes it impossible to apply classifier-specific dependency management (see https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/67).

With this limitation in mind, I think it might make sense for the plugin to ignore dependency management in an imported bom that declares a classifier. This would prevent the dependency management with the `tests` classifier from overriding the dependency management with no classifier. It would also prevent a more general problem where dependency management that targets a specific classifier was being applied more broadly than intended.

**Comment by wilkinsona** [comment]
You can work around the problem by adding dependency management for `jetty-servlet` with the `tests` classifier:

```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.dropwizard.metrics</groupId>
            <artifactId>metrics-bom</artifactId>
            <scope>import</scope>
            <type>pom</type>
            <version>4.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlet</artifactId>
            <version>9.4.11.v20180605</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlet</artifactId>
            <version>9.4.11.v20180605</version>
            <classifier>tests</classifier>
        </dependency>
    </dependencies>
</dependencyManagement>
```

**Comment by jolivares** [comment]
Thanks for your quick response! 
l'll be using the workaround in the meantime. Looking forward the 1.0.6.RELEASE.

**Comment by flozano** [comment]
Question about this change: if I want to manage dependency of something like this (http://repo1.maven.org/maven2/io/netty/netty-tcnative/2.0.12.Final/), which uses classifier to indicate which OS the binaries are for, I cannot do it anymore after this change?

**Comment by wilkinsona** [comment]
Hmm, interesting problem. You should still be able to do it by providing dependency management without a classifier. That might adversely affect use of Netty's bom though.
