### ISSUE TITLE
Broken with 0.3.0.RELEASE

### ISSUE THREAD

**Issue by haggholm** [spring-gradle-plugins/dependency-management-plugin#22]
I'm not sure why the build is broken for me, so forgive me if the report is not as focused as it might be. I upgraded my plugin dependency to 0.3.0, and when I next attempted to build my project, I was greeded by a flood of the following repeated over and over:

```
Processing of axis-1.4.pom failed:
    'distributionManagement.status' must not be specified. in org.apache.axis:axis:1.4
Processing of axis-jaxrpc-1.4.pom failed:
    'distributionManagement.status' must not be specified. in org.apache.axis:axis-jaxrpc:1.4
Processing of axis-1.4.pom failed:
    'distributionManagement.status' must not be specified. in org.apache.axis:axis:1.4
Processing of axis-jaxrpc-1.4.pom failed:
    'distributionManagement.status' must not be specified. in org.apache.axis:axis-jaxrpc:1.4
Processing of axis-1.4.pom failed:
    'distributionManagement.status' must not be specified. in org.apache.axis:axis:1.4
Processing of axis-jaxrpc-1.4.pom failed:
    'distributionManagement.status' must not be specified. in org.apache.axis:axis-jaxrpc:1.4
``` 

Later, compilation failed.

```
java.lang.NoClassDefFoundError: org/apache/log4j/Level
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
        at com.bamsas.injection.InjectionGenerator.<clinit>(InjectionGenerator.java:34)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Level
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        ... 6 more
```

I don't know whether it matters, but my build consists of a root project, the `subprojects` section of which applies `dependencyManagement` to all subprojects and imports a couple of `mavenBom`s.

**Comment by RobWin** [comment]
Hello,

unfortunately I have to confirm that dependency resolution takes an incredible amount of time.
It's not usable. 

Kind regards,

Robert Winkler

**Comment by wilkinsona** [comment]
@RobWin Can you provide some more information? Details of your project's dependencies and the dependency management you're using should be sufficient.

**Comment by RobWin** [comment]
@wilkinsona What information do you need exactly?
We have a lot of external and internal dependencies. 

The Gradle Plugin v0.2.1 is much faster, but does not generate a correct POM file.
Any debugging options I should use?

**Comment by wilkinsona** [comment]
I've made some improvements that, in my testing at least, improve things by up to 10x. This was with a project that depends on everything in the Spring IO Platform (~500 dependencies).

@RobWin Please give the latest snapshot a try and let me know what, if any, improvement you see.

**Comment by RobWin** [comment]
@wilkinsona Thx. I will give it a try.
Did you upload a snapshot to any snapshot repository?

**Comment by wilkinsona** [comment]
@RobWin Sorry, should have pointed you to the snapshot repo. They're available from `https://repo.spring.io/plugins-snapshot` and you should use `0.3.1.BUILD-SNAPSHOT` as the version.

**Comment by RobWin** [comment]
Thx.
Looks much better now, but it's still takes several minutes in a project with ~17 gradle modules.

**Comment by wilkinsona** [comment]
@RobWin Thanks. Good to hear we're making progress. Several minutes is still longer than I'd like, though.

The latest snapshot adds support for disabling Maven-style exclusions:

```groovy
dependencyManagement {
    applyMavenExclusions false
}
```

If you have a moment, I'd be interested to know how long the build takes without the added exclusion processing. I've spotted a few more areas where I can speed things up, but nothing like the earlier ~10x improvement.

**Comment by RobWin** [comment]
Already uploaded to the repo?

**Comment by wilkinsona** [comment]
Yes. The CI server takes care of that. The timestamp's `20150106.104855-6`.

**Comment by wilkinsona** [comment]
I've committed some further improvements that reduce the time for `./gradlew dependencies` from 43 seconds to 27 seconds in my single module test project with ~500 direct dependencies and ~1000 dependencies in total.

There are no remaining obvious ways to dramatically improve the performance. @RobWin @haggholm If things are still too slow for your projects, please feel free to open another issue but I'll need enough information to recreate the problem to be able to investigate further.
