### ISSUE TITLE
Allow a Maven bom to be imported directly from a file

### ISSUE THREAD

**Issue by bsideup** [spring-gradle-plugins/dependency-management-plugin#224]
Hi!

Currently it is not possible to use `imports { mavenBom file("pom.xml") }` but it would be extremely helpful when one wants to store the dependencies in project's file containing some declarative format (and Maven BOM is de facto the most popular one), so that tools like http://dependabot.com or Snyk work without any extra effort.

I could contribute it if you're ok with that. Hits would be appreciated!

**Comment by wilkinsona** [comment]
It's already possible to import a bom that's a local file but you need to configure a repository that makes it available. That said, an overload that takes a `java.io.File` (and can then be used with [`Project.file`](
https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#file-java.lang.Object-)) would makes things more concise and align support more closely with Gradle's support for declaring dependencies.

> I could contribute it if you're ok with that. Hits would be appreciated!

Yes, please. A PR that implements this would be most welcome.

**Comment by bsideup** [comment]
Ok, thanks, will check how to add it. 
I got some ideas, but maybe you have some architectural hints, to align about it beforehand? :)

**Comment by wilkinsona** [comment]
Closing in favour of #229.
