### ISSUE TITLE
Effective model building for Maven poms is inefficient as models are not cached

### ISSUE THREAD

**Issue by moley** [spring-gradle-plugins/dependency-management-plugin#225]
Hi Andy, 

I have reinvestigated performance issue when resolving dependencies with spring-gradle-plugin and found the problem. As [https://github.com/moley/exampleGradleDepsPerformance/blob/master/profiler_real_project.png](pic) shows, the problem is that when reading the maven model a huge number of calls on Interpolation mechanism is the problem. In io.spring.gradle.dependencymanagement.internal.maven.EffectiveModelBuilder you build a org.apache.maven.model.building.DefaultModelBuildingRequest, but do not set a cache implementation. I have prototyped it for me by adding a static HashMap (which is not the end solution, but for first comparison enough), which improves performance the following: 

Without cache duration :                    44s
With cache duration:                           13s

So I would like to provide a pullrequest, were I want to ask if this implementation is accepted by you: 
I'd add the cache implementation to io.spring.gradle.dependencymanagement.internal.dsl.StandardDependencyManagementExtension, where you can also override as customer of the plugin.
In EffectiveModelBuilder I would ask for extension in root project and set this to the Request. 
Is this OK for you?

**Comment by wilkinsona** [comment]
Very interesting findings. Thank you.

I'd really like `EffectiveModelBuilder` and the addition of any cache to be an implementation detail. I'd definitely like to avoid exposing it as a configuration option as it isn't something that a user of the plugin should have to care about.

I'm not sure that something `static` can be used as I have a feeling it will lead to a memory leak when using Gradle's daemon. If a `static` is used, I think it'll be necessary to ensure that its size is limited explicitly or use soft references.

Now that you've homed in a bit more on the problem, can you provide some more details of how to reproduce the problem with your sample project so that I can see exactly how the model building is happening and get a better idea of what the options might be for caching?

**Comment by moley** [comment]
No - this `static` thing was only a first prototype implementation. As said - I would provide an instance variable in StandardDependencyManagementExtension to save it in root project and to reuse this cache in every project. So it is automatically removed after build is finished. With this implementation the user can even replace the cache implementation. 

If you want to reproduce it: 
In [https://github.com/moley/exampleGradleDepsPerformance](testproject) step to logistikMavenizedSpringPlugin and call ../gradlew resolve needs about 44s on my local machine. With the cache in place it needs about 6s. 

Cheers
Markus

**Comment by wilkinsona** [comment]
> a default implementation could be provided by default, overwritable?

Making it overwritable would expose it to users of the plugin. I'd like to avoid that if at all possible.

**Comment by moley** [comment]
OK, so I would suggest to hide it at a project.ext variable at the project.... to be removed after the build. Would this be ok? If not - please suggest a different location.

**Comment by wilkinsona** [comment]
I can't suggest anything at the moment as it's not yet clear to me how the proposed caching will help. Running `resolve` in `logistikMavenizedSpringPlugin` builds 182 models, but there doesn't appear to be any repetition. There are 182 different poms for which a model is built.

I wonder if your prototype is only showing an improvement as you're using Gradle's daemon and the models are being cached across builds due to the use of `static`. If so, anything that scopes the cache to a `Project` doesn't look like it will speed things up.

**Comment by moley** [comment]
No - I have currently completely disabled the daemon on my machine. 
The problem is: if you have repetitions in the dependency tree, e.g. if you depend on module A and B and C and ALL of them depend on module D, then pom.xml of module D is read three times without the cache. If cache is enabled the second and third call loads the data from cache. I could provide a pullrequest without static things, provide a unit test for you to take a look at it and investigate the difference

**Comment by wilkinsona** [comment]
Thanks, that's the information that I was missing.

From your description thus far and the desire the share the cache statically, it appeared that the caching would only be of benefit when spread across multiple model building requests. Having looked at how Maven behaves more closely [and prototyped something](https://github.com/wilkinsona/dependency-management-plugin/commit/e684d60f042fee1519e654353afdddac5eaeec66), I now see that's not the case. A single model building request can lead to multiple models being created, and a model with the same groupId, artifactId, version, and tag may be created multiple times.

In my prototype, the cache is scoped to the `EffectiveModelBuilder` instance and it has a dramatic effect on performance. Without the cache, `./gradlew resolve --no-daemon` takes 33 seconds. With the cache, `./gradlew resolve --no-daemon` takes 3 seconds.

**Comment by moley** [comment]
Looks good - I think. 
If you want to retest this issue, could you please provide me any kind of release?
Thank you for this quick fix

**Comment by wilkinsona** [comment]
The change is now available in 1.0.7 snapshots. You can use them by adding https://repo.spring.io/plugins-snapshot as a Maven repository and overriding the version of the dependency management plugin to be 1.0.7.BUILD-SNAPSHOT:

```groovy
buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://repo.spring.io/libs-snapshot' }
        maven { url 'https://repo.spring.io/plugins-snapshot' }
    }
    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:2.1.0.M1"
        classpath "io.spring.gradle:dependency-management-plugin:1.0.7.BUILD-SNAPSHOT"
    }
}
```

**Comment by moley** [comment]
For users, that have multi module projects in gradle it would be even better to hold the cache only once per multi module. This would even provide an additional performance improvement. But I think the most improvement is done by this fix, which improves a full build from 1m 14s to 39s in one of my cases. Thank you for description how to use it, too.

**Comment by wilkinsona** [comment]
Thanks for trying out the change. I agree that it would be better from a performance perspective to share a single cache across a multi-module build, but I cannot think of a good way to do it.

A typical multi-module setup applies the dependency management plugin to all subprojects but not to the root project. In that situation, storing the cache in the root project doesn't feel right as I don't think a plugin should make any changes to a project to which it hasn't been applied. Given that all the projects to which the plugin has been applied could be siblings, there's no obvious place for them to look to find the shared cache. If they had a common ancestor to which the plugin had been applied, that would be the logical place to look.

Given the above, I think the best compromise between minimising complexity and improving performance is to scope the cache to an individual project. The almost 50% reduction in build time is already pretty good after all. Thanks again for bringing the possible improvement to my attention.

**Comment by moley** [comment]
Yes, you're right, for us the improvement is enough :-) so thank you for all

**Comment by moley** [comment]
Hi Andy, 

as this bug is fixed, but not yet released, I'd like to ask when you plan to release a 1.0.7.RELEASE, because we need a real version in near future to get into production..... Would be nice if you could give me a hint...

**Comment by wilkinsona** [comment]
Thanks for the nudge. 1.0.7.RELEASE is now available from Maven Central and the Gradle Plugin Portal.

**Comment by moley** [comment]
No problem - thank you for your fast reaction.
