### ISSUE TITLE
include/exclude certain sourceSet configurations

### ISSUE THREAD

**Issue by xenoterracide** [spring-gradle-plugins/dependency-management-plugin#230]
I've had this problem twice, first time, the platform.bom was overriding the guava version for the `errorProneCompile` (I know guava no longer managed), which is added by the error prone plugin.

now I have my own custom configuration (a test-library scope), and I'd like to use bom management for it, and only it.

maybe something like

```
apply plugin: 'io.spring.dependency-management'

dependencyManagement {
     scopes = [ "testLibrary" ]
}
```

**Comment by wilkinsona** [comment]
The plugin already allows you to [configure dependency management for a specific configuration](
https://github.com/spring-gradle-plugins/dependency-management-plugin#dependency-management-for-specific-configurations).

**Comment by wilkinsona** [comment]
What’s not right? Perhaps you can provide a complete example that shows the problem? There may need to be some changes to work nicely with the Kotlin DSL. It should work fine with Groovy however.

**Comment by xenoterracide** [comment]
the syntax is different, I suspect this works (it compiles), but I ran into other issues with another plugin that generates code... and just causing pain, so I'm abandoning doing it as a sourceset
```
dependencyManagement {
    configurations {
        "stubCompile" {}
    }
}
```
leaving open if you feel like more documentation would help, 'cause  I did skim through the docs, and I thought that section was about configuring compile with imports... I didn't think it applied to custom source sets. If not, closing is fine.

**Comment by wilkinsona** [comment]
Nothing in the dependency management plugin applies to source sets directly. The dependency management plugin affects the versions of dependencies in configurations. Those configurations may then be used to create the classpath of a source set as you have done.
