### ISSUE TITLE
Provide Kotlin DSL-based examples in the README

### ISSUE THREAD

**Issue by wilkinsona** [spring-gradle-plugins/dependency-management-plugin#232]

**Comment by eriwen** [comment]
Here are a couple additional resources for contributors:

 * [Migrating build logic from Groovy to Kotlin guide](https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/)
 * [Exemplar for automated samples testing](https://blog.gradle.org/documentation-samples-testing-exemplar)
 * [Join #kotlin-dsl channel in Gradle Community Slack for personalized help](https://join.slack.com/t/gradle-community/shared_invite/enQtNDE3MzAwNjkxMzY0LTYwMTk0MWUwN2FiMzIzOWM3MzBjYjMxNWYzMDE1NGIwOTJkMTQ2NDEzOGM2OWIzNmU1ZTk5MjVhYjFhMTI3MmE)

Thank you for providing a great Gradle plugin!

**Comment by checketts** [comment]
I wouldn't mind contributing this. Anyone mind if I take it?

**Comment by wilkinsona** [comment]
Not at all, @checketts. That’d be much appreciated.

**Comment by checketts** [comment]
Addressed by #233

**Comment by wilkinsona** [comment]
Closing in favour of #233.
