### ISSUE TITLE
Reference documentation doesn't directly link to documentation

### ISSUE THREAD

**Issue by asarkar** [spring-gradle-plugins/dependency-management-plugin#238]
The [reference documentation](https://docs.spring.io/dependency-management-plugin/docs/current-SNAPSHOT/reference/) points to a directory, where clicking on `html5` takes me to https://docs.spring.io/dependency-management-plugin/docs/current-SNAPSHOT/reference/html5/. Why two hops, it seems unnecessary? (perhaps an oversight)?

**Comment by wilkinsona** [comment]
It's like that to leave room for other formats such as PDF in the future.
