### ISSUE TITLE
Enable build scan generation on CI

### ISSUE THREAD

**Issue by aalmiray** [spring-gradle-plugins/dependency-management-plugin#240]
Would the team be interested in enabling build scans when running on CI?

I noticed that the project has a gitter channel, perhaps you'd be interested in letting members know when a scan is ready, as it's shown at http://andresalmiray.com/hooking-gradle-build-scans-notifications-to-gitter/

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but I don't want to tie CI to any external services unless it's absolutely necessary.
