### ISSUE TITLE
Cannot pass properties into resolutionStrategy

### ISSUE THREAD

**Issue by Frozkata** [spring-gradle-plugins/dependency-management-plugin#241]
I have this in my **build.gradle**

```groovy
ext {
  springVersion = "2.1.2.RELEASE"
}

dependencyManagement {
  imports { ... }
  resolutionStrategy {
    force "org.springframework.boot:spring-boot-dependencies:$springVersion"
  }
}
```

And I get the following error
```> Failed to notify dependency resolution listener.
   > Failed to resolve imported Maven boms: Configuration with name 'springVersion' not found.
   > Configuration with name 'springVersion' not found.
```
Works the same and outputs the same error for every dependency/BOM.

It works when I apply the version like this `"org.springframework.boot:spring-boot-dependencies:2.1.2.RELEASE"`

Am I missing something? Is there a way to use props inside the dependencyManagement's resolutionStrategy? It does work for `buildscript` block for example.

**Comment by wilkinsona** [comment]
For `$springVersion` to work, the project has to be the closure's delegate and that's not the case. You need to qualify it so that it's clear that you're referencing a property on the project: `$project.springVersion`.
