### ISSUE TITLE
Dependency management does not work with includeBuild

### ISSUE THREAD

**Issue by prismec** [spring-gradle-plugins/dependency-management-plugin#246]
The attached file includes two projects `commons` and `service`, where `service` `includeBuild`s `commons`. 

`commons` uses the dependency management plugin and everything is resolved correctly, but when running `gradlew dependencies` on `service`, then any dependencies managed by `commons` cannot be resolved.

```
commons:> gradlew dep --configuration compile

> Task :dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

compile - Dependencies for source set 'main' (deprecated, use 'implementation' instead).
\--- com.google.guava:guava -> 23.0
     +--- com.google.code.findbugs:jsr305:1.3.9
     +--- com.google.errorprone:error_prone_annotations:2.0.18
     +--- com.google.j2objc:j2objc-annotations:1.1
     \--- org.codehaus.mojo:animal-sniffer-annotations:1.14
```

```
service> gradlew dep --configuration compile

> Task :dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

compile - Dependencies for source set 'main' (deprecated, use 'implementation' instead).
\--- commons:commons -> project :commons
     \--- com.google.guava:guava FAILED
```

[includebuild.zip](https://github.com/spring-gradle-plugins/dependency-management-plugin/files/2979279/includebuild.zip)

**Comment by wilkinsona** [comment]
This is caused by a limitation of Gradle. Please see https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/127 and https://github.com/gradle/gradle/issues/947 to which it links.
