### ISSUE TITLE
Suggest why the dependency can not be resolved and propose a fix

### ISSUE THREAD

**Issue by bric3** [spring-gradle-plugins/dependency-management-plugin#256]
Is it possible to tell the reason why why a certain dependency resolving fails. e.g. I had this issue. The use case I'm thinking is can the dependency-management-plugin tells that a dependency is not declared in the imported maven BOM. And may propose to declare the missing dependency in the dependencyManagement / dependencies block.

----

For example in `org.springframework.boot:spring-boot-dependencies:1.5.x` I was expecting to have all spring-restdocs related artefacts, however `org.springframework.restdocs:spring-restdocs-asciidoctor` is not and requires one to either set the version directly in the dependencies block (ike in the example above), or to declare `dependency("org.springframework.restdocs:spring-restdocs-asciidoctor:$springRestDocsVersion")` within dependencyManagement > dependencies block

```
* What went wrong:
Execution failed for task ':asciidoctor'.
> Could not resolve all files for configuration ':asciidoctor'.
   > Could not find org.springframework.restdocs:spring-restdocs-asciidoctor:.
     Required by:
         project :
```

with this _edited_ build script :

```gradle
plugins {
    id 'application'
    id 'jacoco'
    id 'nebula.facet' version '6.0.3'
    id 'org.asciidoctor.convert' version '1.6.1'
    id 'org.springframework.boot' version '1.5.21.RELEASE'
    id 'io.spring.dependency-management' version '1.0.7.RELEASE'
}

ext {
    lombokVersion = '1.18.8'
    springBootVersion = '1.5.21.RELEASE'
    jacksonVersion = '2.9.9'
    restAssuredVersion = '4.0.0'
    springRestDocsVersion = '1.2.6.RELEASE'
    asciidoctorjDiagramVersion = '1.5.16'

}

dependencyManagement {
    imports {
        // properties available here https://github.com/spring-projects/spring-boot/blob/1.5.x/spring-boot-dependencies/pom.xml
        mavenBom("org.springframework.boot:spring-boot-dependencies:$springBootVersion") {
            bomProperties([
                'lombok.version' : lombokVersion,
                'jackson.version' : jacksonVersion,

                // test
                'undertow.version' : undertowVersion,
                'mockito.version' : mockitoVersion,
                'assertj.version' : assertjVersion,

                // doc
                'spring-restdocs.version' : springRestDocsVersion
            ])
        }

        dependencies {
            dependency("io.rest-assured:rest-assured:$restAssuredVersion")
            // some dependencySet
        }
    }
}



dependencies {
    // implementation 
    // compileOnly
    // annotationProcessor
    // testImplementation

    integrationTestImplementation "io.rest-assured:rest-assured"
    integrationTestImplementation "org.springframework.restdocs:spring-restdocs-core"
    integrationTestImplementation "org.springframework.restdocs:spring-restdocs-restassured"

    // documentation
    asciidoctor "org.springframework.restdocs:spring-restdocs-asciidoctor:$springRestDocsVersion" // version needed
    asciidoctor "org.asciidoctor:asciidoctorj-diagram:$asciidoctorjDiagramVersion"
}

asciidoctorj {
    version = '1.5.8.1'
}

asciidoctor {
    requires 'asciidoctor-diagram'
    options doctype: 'book'
    sources {
        include 'index.adoc'
    }
}

```

**Comment by wilkinsona** [comment]
Interesting suggestion, thank you. It is possible to do what you've described. Spring Boot's plugin has [some code](https://github.com/spring-projects/spring-boot/blob/ae5b5be597d62833044dea790957372d95ceb7c6/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/plugin/UnresolvedDependenciesAnalyzer.java) that does something somewhat similar. Its plugin used to apply this plugin automatically but, in Boot 2.0, we moved to having to apply this plugin explicitly to allow alternative dependency management solutions to be used. If a dependency with no version specified fails to resolve, it asks if you've forgotten to apply this plugin.

I'm not sure how well it would work for more complex situations such as the one you have described above. Perhaps you'd like to prototype something?

**Comment by wilkinsona** [comment]
Closing due to the lack of the requested feedback. We can re-open this issue if the feedback is provided in the future.
