### ISSUE TITLE
Invalid pom is produced when using both the dependency management plugin and Gradle's bom support

### ISSUE THREAD

**Issue by acidbee** [spring-gradle-plugins/dependency-management-plugin#257]
When including other BOMs in a build file, generating POMs for publishing artifacts include two dependency management nodes resulting in an invalid POM.

build.gradle.kts
```kotlin
plugins {
    java
    application
    maven
    `maven-publish`
    id("org.springframework.boot") version "2.1.5.RELEASE"
    id("com.gorylenko.gradle-git-properties") version "2.0.0"
}

apply(plugin = "io.spring.dependency-management")

group = "com.isonas"

repositories {
    mavenCentral()
}

// Configure Java
java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

// Enable creating jar as part of build artifacts
tasks.getByName<Jar>("jar") {
    enabled = true
}

// Define main class name for distributions
springBoot {
    mainClassName = "com.isonas.microservice.App"
    buildInfo()
}

application {
    mainClassName = "com.isonas.microservice.App"
}

// Make sure distributions have launch scripts
tasks.bootJar {
    launchScript()
}

publishing {
    publications {
        create<MavenPublication>("jar") {
            from(components["java"])
            artifact(tasks.getByName("jar"))
        }

        create<MavenPublication>("bootJar") {
            artifact(tasks.getByName("bootJar"))
        }
    }
}

// Explicitly enable the JUnit 5 Jupiter engine
tasks.test {
    useJUnitPlatform()
}

// Project Dependencies
dependencies {
    // Bill of Materials
    implementation(platform("software.amazon.awssdk:bom:2.5.29"))

    // Annotation Processors
    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")

    // Spring Boot Framework
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-actuator")

    // AWS
    implementation("software.amazon.awssdk:ssm")

    // Test Dependencies
    testImplementation("org.junit.jupiter:junit-jupiter-api")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}
```

Running a publish task results in an error
```
$gradle clean build publishToMavenLocal --stacktrace

> Task :publishJarPublicationToMavenLocal FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishJarPublicationToMavenLocal'.
> Failed to publish publication 'jar' to repository 'mavenLocal'
   > Invalid publication 'jar': POM file is invalid. Check any modifications you have made to the POM file.

...

Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: Duplicated tag: 'dependencyManagement' (position: START_TAG seen ...</dependencies>\n  <dependencyManagement>... @36:25)
```

build/publications/jar/pom-default.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.isonas</groupId>
  <artifactId>micro-service-template</artifactId>
  <version>unspecified</version>
  <packaging>pom</packaging>
  <!-- AWS SDK BOM -->
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>software.amazon.awssdk</groupId>
        <artifactId>bom</artifactId>
        <version>2.5.29</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>ssm</artifactId>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
  <!-- Spring Boot BOM -->
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>2.1.5.RELEASE</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>

```

**Comment by wilkinsona** [comment]
This looks like a Gradle bug to me. This plugin only adds `<dependencyManagement>` to the project's pom if it does not already exist:

https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/a206b9ac336c1fe9c162f269748d603b3edb8ffc/src/main/java/io/spring/gradle/dependencymanagement/internal/StandardPomDependencyManagementConfigurer.java#L106-L117

There's also a test that verifies this behaviour:

https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/master/src/test/groovy/io/spring/gradle/dependencymanagement/internal/StandardPomDependencyManagementConfigurerSpec.groovy#L129-L145

If you have evidence to the contrary, please comment with it here and we can re-open the issue to investigate. Otherwise, I think this needs to be reported to the Gradle team. You could also avoid the problem by using either the dependency management plugin or Gradle's platform support, rather than mixing the two.

**Comment by primehot** [comment]
Hello,
If some one still have this problem.
Solution works for me: 
`dependencyManagement {
	imports {
		mavenBom 'groupId:artifactID:version'
	}
}`

**Comment by nstdio** [comment]
Using 

```gradle
implementation platform("my.company:dependencies:$version")
implementation platform("org.springframework.boot:spring-boot-dependencies:$springBootVersion")
```

Correctly publishes to Artifactory.

**Comment by piyush8098** [comment]
> When including other BOMs in a build file, generating POMs for publishing artifacts include two dependency management nodes resulting in an invalid POM.
> 
> build.gradle.kts
> 
> ```kotlin
> plugins {
>     java
>     application
>     maven
>     `maven-publish`
>     id("org.springframework.boot") version "2.1.5.RELEASE"
>     id("com.gorylenko.gradle-git-properties") version "2.0.0"
> }
> 
> apply(plugin = "io.spring.dependency-management")
> 
> group = "com.isonas"
> 
> repositories {
>     mavenCentral()
> }
> 
> // Configure Java
> java {
>     sourceCompatibility = JavaVersion.VERSION_11
>     targetCompatibility = JavaVersion.VERSION_11
> }
> 
> // Enable creating jar as part of build artifacts
> tasks.getByName<Jar>("jar") {
>     enabled = true
> }
> 
> // Define main class name for distributions
> springBoot {
>     mainClassName = "com.isonas.microservice.App"
>     buildInfo()
> }
> 
> application {
>     mainClassName = "com.isonas.microservice.App"
> }
> 
> // Make sure distributions have launch scripts
> tasks.bootJar {
>     launchScript()
> }
> 
> publishing {
>     publications {
>         create<MavenPublication>("jar") {
>             from(components["java"])
>             artifact(tasks.getByName("jar"))
>         }
> 
>         create<MavenPublication>("bootJar") {
>             artifact(tasks.getByName("bootJar"))
>         }
>     }
> }
> 
> // Explicitly enable the JUnit 5 Jupiter engine
> tasks.test {
>     useJUnitPlatform()
> }
> 
> // Project Dependencies
> dependencies {
>     // Bill of Materials
>     implementation(platform("software.amazon.awssdk:bom:2.5.29"))
> 
>     // Annotation Processors
>     annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")
> 
>     // Spring Boot Framework
>     implementation("org.springframework.boot:spring-boot-starter-web")
>     implementation("org.springframework.boot:spring-boot-starter-actuator")
> 
>     // AWS
>     implementation("software.amazon.awssdk:ssm")
> 
>     // Test Dependencies
>     testImplementation("org.junit.jupiter:junit-jupiter-api")
>     testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
>     testImplementation("org.springframework.boot:spring-boot-starter-test")
> }
> ```
> 
> Running a publish task results in an error
> 
> ```
> $gradle clean build publishToMavenLocal --stacktrace
> 
> > Task :publishJarPublicationToMavenLocal FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':publishJarPublicationToMavenLocal'.
> > Failed to publish publication 'jar' to repository 'mavenLocal'
>    > Invalid publication 'jar': POM file is invalid. Check any modifications you have made to the POM file.
> 
> ...
> 
> Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: Duplicated tag: 'dependencyManagement' (position: START_TAG seen ...</dependencies>\n  <dependencyManagement>... @36:25)
> ```
> 
> build/publications/jar/pom-default.xml
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
>   <modelVersion>4.0.0</modelVersion>
>   <groupId>com.isonas</groupId>
>   <artifactId>micro-service-template</artifactId>
>   <version>unspecified</version>
>   <packaging>pom</packaging>
>   
>   <dependencyManagement>
>     <dependencies>
>       <dependency>
>         <groupId>software.amazon.awssdk</groupId>
>         <artifactId>bom</artifactId>
>         <version>2.5.29</version>
>         <type>pom</type>
>         <scope>import</scope>
>       </dependency>
>     </dependencies>
>   </dependencyManagement>
>   <dependencies>
>     <dependency>
>       <groupId>org.springframework.boot</groupId>
>       <artifactId>spring-boot-starter-web</artifactId>
>       <scope>runtime</scope>
>     </dependency>
>     <dependency>
>       <groupId>org.springframework.boot</groupId>
>       <artifactId>spring-boot-starter-actuator</artifactId>
>       <scope>runtime</scope>
>     </dependency>
>     <dependency>
>       <groupId>software.amazon.awssdk</groupId>
>       <artifactId>ssm</artifactId>
>       <scope>runtime</scope>
>     </dependency>
>   </dependencies>
>   
>   <dependencyManagement>
>     <dependencies>
>       <dependency>
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-dependencies</artifactId>
>         <version>2.1.5.RELEASE</version>
>         <scope>import</scope>
>         <type>pom</type>
>       </dependency>
>     </dependencies>
>   </dependencyManagement>
> </project>
> ```

Hi @acidbee , I am facing the same issue. Were you able to fix it?

**Comment by wilkinsona** [comment]
@piyush8098 Did you try the suggestion above:

> You could also avoid the problem by using either the dependency management plugin or Gradle's platform support, rather than mixing the two.

**Comment by Warfront1** [comment]
I had the same problem when using `implementation platform("software.amazon.awssdk:bom:2.17.8")`  and plugin `id 'io.spring.dependency-management' version '1.0.11.RELEASE'` 

In order to fix this I removed the awssdk:bom implementation and directly just referenced the AWS components I needed:
`implementation "software.amazon.awssdk:s3:2.17.8"` etc...

Obviously less than ideal, but I wasn't able to get anything working that was already posted.

**Comment by FrogDevelopper** [comment]
I get the same issue and used the hack found in [Gradle plugin: Duplicated tag: 'dependencyManagement'](https://github.com/jfrog/build-info/issues/198#issuecomment-611240524)

```groovy
task fixPom {
    doLast {
        File file = new File("$buildDir/publications/maven/pom-default.xml")
        def text = file.text
        def pattern = "(?s)(<dependencyManagement>.+?<dependencies>)(.+?)(</dependencies>.+?</dependencyManagement>)"
        Matcher matcher = text =~ pattern
        if (matcher.find()) {
            text = text.replaceFirst(pattern, "")
            def firstDeps = matcher.group(2)
            text = text.replaceFirst(pattern, '$1$2' + firstDeps + '$3')
        }
        file.write(text)
    }
}
generatePomFileForMavenPublication.finalizedBy fixPom
```

this will merge the 2 blocks `<dependencyManagement>` into 1 and so resolve the issue.

**Comment by lucianspec** [comment]
thanks @FrogDevelopper 's solutions , it save my day.

**Comment by wwShuang** [comment]
@FrogDevelopper excellent solution! thanks!

**Comment by nddipiazza** [comment]
omg thank you. you saved my friday.

**Comment by morohon** [comment]
@wilkinsona Hello!
I made issues in the gradle repo: https://github.com/gradle/gradle/issues/21277#issuecomment-1701182829 , but they seem to have found a problem on the plugin side. Maybe you can study and comment on this point?

**Comment by wilkinsona** [comment]
@jvandort is correct (thank you, Justin). The tests didn't catch the problem as the name (returned as `Object` by Groovy's API) was always a `String` and never a `QName`.
