### ISSUE TITLE
Last wins ordering is not honoured when the same bom is imported multiple times

### ISSUE THREAD

**Issue by bric3** [spring-gradle-plugins/dependency-management-plugin#259]
Version : 1.0.8.RELEASE (while this [milestone](https://github.com/spring-gradle-plugins/dependency-management-plugin/milestone/28) is still open, the jar is available on [central](https://search.maven.org/artifact/io.spring.gradle/dependency-management-plugin/1.0.8.RELEASE/jar))

The [plugin documentation](https://docs.spring.io/dependency-management-plugin/docs/1.0.8.RELEASE/reference/html/#dependency-management-configuration-bom-import-multiple) indicates that multiple bom imports are supported and that the dependency that should be picked is the one from the _latest bom_

> *Importing Multiple Boms*
> 
> If you import more than one bom, the order in which the boms are imported can be important. The boms are processed in the order in which they are imported. If multiple boms provide dependency management for the same dependency, the dependency management from the last bom will be used.

Given this `dependencyManagement` configuration in a single root module gradle project :

```gradle
plugins {
    id 'java'
    id 'org.springframework.boot' version '2.1.8.RELEASE'
    id 'io.spring.dependency-management' version '1.0.8.RELEASE'
}

ext {
    // versions
    commonJavaVersion = '4.+'
    springBootVersion = '2.1.8.RELEASE'
}

dependencyManagement {
    imports {
        mavenBom("com.company.service.common:common-java:$commonJavaVersion")
        // properties available here https://github.com/spring-projects/spring-boot/blob/2.1.x/spring-boot-project/spring-boot-dependencies/pom.xml
        mavenBom("org.springframework.boot:spring-boot-dependencies:$springBootVersion") {
            bomProperties([
                'lombok.version' : '1.18.2',
                'jackson.version' : '2.9.9',

                // test
                'junit-jupiter.version' : '5.5.2',
                'undertow.version' : '2.0.20.Final',
                'mockito.version' : '3.0.0',
                'assertj.version' : '3.13.2',
                'rest-assured.version' : '4.0.0',

                // doc
                'spring-restdocs.version' : '2.0.3.RELEASE'
            ])
        }
    }
    dependencies {
        // ...
        dependency("org.fusesource.jansi:jansi:1.17.1")
        dependency("com.akaita.java:rxjava2-debug:1.4.0")
        dependency("com.github.akarnokd:rxjava2-jdk8-interop:0.3.5")
        dependencySet(group:'com.squareup.okhttp3', version: '3.14.1') {
            entry('okhttp')
            entry('logging-interceptor')
            entry('mockwebserver')
        }

        // ...
    }
}
```

1. Spring dependency management plugin choose the lowest available version, regardless of the `mavenBom` directive order. Here 

   * `com.company.service.common:common-java:$commonJavaVersion` declares `org.springframework.boot:spring-boot-starter-web:2.1.6.RELEASE`
   * but `org.springframework.boot:spring-boot-dependencies:$springBootVersion` declares `2.1.8.RELEASE`

   yet it's the lower version that is selected.

```bash
./gradlew dependencyInsight --dependency spring-boot-starter-web

> Task :dependencyInsight
org.springframework.boot:spring-boot-starter-web:2.1.6.RELEASE (selected by rule)
   variant "compile" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-api
      org.gradle.libraryelements     = jar (compatible with: classes)
      org.gradle.category            = library (not requested)

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 11
   ]

org.springframework.boot:spring-boot-starter-web -> 2.1.6.RELEASE
\--- compileClasspath

A web-based, searchable dependency report is available by adding the --scan option.
```

2. Properties override don't work as well if there's two `mavenBom` imports. Here 

   * `com.company.service.common:common-java:$commonJavaVersion` declares mockito 2.28.2
   * `org.springframework.boot:spring-boot-dependencies:$springBootVersion` declares mockito 2.23.4
   * `org.springframework.boot:spring-boot-dependencies:$springBootVersion` mockito version is overriden by mine `'mockito.version' : '3.0.0'`

   yet version 2.23.4 is selected

```bash
./gradlew dependencyInsight --dependency mockito-core --configuration testCompileClasspath

> Task :dependencyInsight
org.mockito:mockito-core:2.23.4 (selected by rule)
   variant "compile" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-api
      org.gradle.libraryelements     = jar (compatible with: classes)
      org.gradle.category            = library (not requested)

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 11
   ]

org.mockito:mockito-core -> 2.23.4
\--- testCompileClasspath

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
```

If I remove this import declaration `mavenBom("com.company.service.common:common-java:$commonJavaVersion")`, then everything works as expected. I wonder if there's some sort of conflict with the `org.springframework.boot` plugin ?!

**Comment by wilkinsona** [comment]
> while this milestone is still open, the jar is available on central

Thanks for pointing this out. I've closed the milestone now.

> Spring dependency management plugin choose the lowest available version, regardless of the mavenBom directive order

There's a test that verifies the ordering behaviour:

https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/a206b9ac336c1fe9c162f269748d603b3edb8ffc/src/test/groovy/io/spring/gradle/dependencymanagement/DependencyManagementPluginSpec.groovy#L1022-L1035

Without knowing what's in `com.company.service.common:common-java:$commonJavaVersion`, I could only speculate as to why you're seeing different behaviour. If you'd like me to spend some time investigating, can you please provide a complete and minimal sample that reproduces the problem? A small Gradle project that uses a file-based repository to provide the additional bom would be ideal.

> I wonder if there's some sort of conflict with the org.springframework.boot plugin ?!

That may well be related. As it stands, your configuration will be importing Spring Boot's bom twice as Boot's plugin will import it automatically as a result of the dependency management plugin being applied.

**Comment by bric3** [comment]
@wilkinsona [Here][1]'s what I think will reproduce the issues described above, I had to clean up the pom file, but the same problem should arise.

1. `./gradlew dependencyInsight --dependency spring-boot --configuration testCompileClasspath` reports `2.1.6.RELEASE`, but if this line is commented `mavenBom("com.company.service.common:common-java:$commonJavaVersion")` then the correct version is selected `2.1.8.RELEASE`

2. `./gradlew dependencyInsight --dependency mockito-core --configuration testCompileClasspath` reports `2.23.4`, but if this line is commented `mavenBom("com.company.service.common:common-java:$commonJavaVersion")` then the correct version is selected `3.0.0`


[1]: https://github.com/bric3/dependency-management-plugin-issue259

**Comment by wilkinsona** [comment]
Thanks very much. I've reproduced the problem and I can see what's happening now.

There are three boms being imported:

1. `org.springframework.boot:spring-boot-dependencies:2.1.8.RELEASE` 
2. `com.company.service.common:common-java:4.+` 
3. `org.springframework.boot:spring-boot-dependencies:2.1.8.RELEASE` 

A Gradle `configuration` is created to get the resolved artifacts for the three boms. Usually this is fine as Gradle returns them as an ordered set. However, in this case where the same bom appears twice, the second occurrence is lost. This results in the following boms being applied:

1. `org.springframework.boot:spring-boot-dependencies:2.1.8.RELEASE` 
2. `com.company.service.common:common-java:4.14.0`

**Comment by wilkinsona** [comment]
The problem can be worked around by importing the `common-java` bom before Spring Boot's bom. This requires the application of Boot's plugin to be deferred. Here's a diff that makes the necessary changes:

```diff
diff --git a/build.gradle b/build.gradle
index 50f6c1f..5761961 100644
--- a/build.gradle
+++ b/build.gradle
@@ -1,6 +1,6 @@
 plugins {
     id 'java'
-    id 'org.springframework.boot' version '2.1.8.RELEASE'
+    id 'org.springframework.boot' version '2.1.8.RELEASE' apply false
     id 'io.spring.dependency-management' version '1.0.8.RELEASE'
 }
 
@@ -22,23 +22,6 @@ ext {
 dependencyManagement {
     imports {
         mavenBom("com.company.service.common:common-java:$commonJavaVersion")
-        // properties available here https://github.com/spring-projects/spring-boot/blob/2.1.x/spring-boot-project/spring-boot-dependencies/pom.xml
-        mavenBom("org.springframework.boot:spring-boot-dependencies:$springBootVersion") {
-            bomProperties([
-                'lombok.version' : '1.18.2',
-                'jackson.version' : '2.9.9',
-
-                // test
-                'junit-jupiter.version' : '5.5.2',
-                'undertow.version' : '2.0.20.Final',
-                'mockito.version' : '3.0.0',
-                'assertj.version' : '3.13.2',
-                'rest-assured.version' : '4.0.0',
-
-                // doc
-                'spring-restdocs.version' : '2.0.3.RELEASE'
-            ])
-        }
     }
     dependencies {
         // main
@@ -70,6 +53,23 @@ dependencyManagement {
     }
 }
 
+ext {
+    set 'lombok.version','1.18.2'
+    set 'jackson.version','2.9.9'
+
+    // test
+    set 'junit-jupiter.version','5.5.2'
+    set 'undertow.version','2.0.20.Final'
+    set 'mockito.version','3.0.0'
+    set 'assertj.version','3.13.2'
+    set 'rest-assured.version','4.0.0'
+
+    // doc
+    set 'spring-restdocs.version','2.0.3.RELEASE'
+}
+
+apply plugin: 'org.springframework.boot'
+
 dependencies {
     implementation "org.hibernate.validator:hibernate-validator"
```

The changes are:

1. Do not apply Boot's plugin up front
2. Import the `common-java` bom only
3. Set some extra properties to control the versions in the `spring-boot-dependencies` bom
4. Apply Boot's plugin so that it imports its bom

**Comment by bric3** [comment]
Hi @wilkinsona I won't have time to test this this week, I'll try asap next week, thanks a lot for the help though !

**Comment by bric3** [comment]
@wilkinsona It's good, thank you !!!

**Comment by bric3** [comment]
Thanks @wilkinsona !
