### ISSUE TITLE
dependencies.dependency.scope' for junit:junit:jar must be one of [compile, runtime, system] but is 'test'. in log4j:log4j:1.2.16

### ISSUE THREAD

**Issue by rongbo-j** [spring-gradle-plugins/dependency-management-plugin#260]
i use io.spring.dependency-management  plugin ,when build project , intellij idea output some error log.
![20191012100348](https://user-images.githubusercontent.com/12210807/66693117-f986de00-ecd7-11e9-8864-489ed562ff29.jpg)

it make me confused, my project not dependency log4j,  the error log come from this code:

```
final class EffectiveModelBuilder {
 ... ...
private void reportErrors(List<ModelProblem> errors, File file) {
        StringBuilder message = new StringBuilder("Errors occurred while build effective model from " + file + ":");
        for (ModelProblem error: errors) {
            message.append("\n    " + error.getMessage() + " in " + error.getModelId());
        }
        logger.error(message.toString());
    }
    .... ... 
}
```
can you change log level to warn , or  upgrade  log4j to 1.2.17

**Comment by wilkinsona** [comment]
The dependency management plugin doesn't depend on Log4j, directly or transitively. I suspect your project has a transitive dependency on it and that's where a correction should be made.
