### ISSUE TITLE
Missing classpath dependency for tests

### ISSUE THREAD

**Issue by lobodpav** [spring-gradle-plugins/dependency-management-plugin#261]
Having a `Gradle 6.0` project for a `SpringBoot 2.1.9` application with an integration test using `@EmbeddedKafka`.

When running `./gradlew clean build`, the test fails on

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedKafka': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/apache/zookeeper/server/ZooKeeperServer
```

A simplified version is here: https://github.com/lobodpav/SpringDependencyManagementIssue

When running `./gradlew dependencies`, the `ZooKeeper` is listed there.
When running `./gradlew printTestRuntimeClasspath` the `ZooKeeper` dependency is not printed out.

I have found 3 workarounds:
1. Removing the plugin completely, and specifying the `2.1.9.RELEASE` version manually for all dependencies, fixes the issue.
2. Having the `mavenLocal()` repository as the last one fixes the issue.
3. Manually adding the `ZooKeeper` dependency using `testImplementation "org.apache.zookeeper:zookeeper:3.4.10"` fixes the issue.

**Comment by wilkinsona** [comment]
Thanks for the sample. Unfortunately, it does not reproduce the problem that you have described. I see the ZooKeeper jar listed in the dependencies output and in the printTestRuntimeClasspath output and all of the tests pass.

Given that moving `mavenLocal()` after `mavenCentral()` fixes the problem, you appear to have a corrupted copy of the zookeeper jar in your local Maven cache. That it works when you explicitly specify 3.4.10 as the version (3.4.13 is the default) also points towards. I think the 3.4.13 version of the ZooKeeper jar in your local Maven cache is corrupted. You could verify that by using `jar -tf` to list its contents.

If that jar is not corrupted, please update the issue with the precise steps that are necessary to reproduce the problem and we can re-open it and take another look.

**Comment by lobodpav** [comment]
Now, that is interesting!
The build fails both on my local macOS Catalina, and on Jenkins as well.

I have figured that the JAR came to the local maven repo from another project, downloaded from my company's nexus.

If I only remove the `~/.m2/repository/org/apache/zookeeper/zookeeper/3.4.13/` directory, the build starts to work.

The `~/.m2/repository/org/apache/zookeeper/zookeeper/3.4.13/` contains only the POM file, SHA1 file, and a `_remote.repositories` file, which was created by a `Maven Resolver` as it states in it's content `#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.`.

I guess this is the reason for my problem even though I am not yet sure why.

**Comment by lobodpav** [comment]
I have found the root cause, and it has nothing to do with your plugin. Sorry for that.
See https://github.com/gradle/gradle/issues/2631 for more details.

**Comment by wilkinsona** [comment]
No problem. Thanks for letting us know.
