### ISSUE TITLE
avoid dependency version modification of a gradle configuration used by another gradle plugin

### ISSUE THREAD

**Issue by hauner** [spring-gradle-plugins/dependency-management-plugin#266]
## issue
I'm trying to use a self build plugin in a spring boot project with the dependency-management-plugin.

My plugin uses a plugin specific gradle configuration to collect its dependencies. The configuration is used to run a task of the plugin with an isolated classpath based on that configuration.

Problem is that the dependency-management-plugin applies the spring versions to the configuration of my plugin which leads to an "Unable to load class 'com.fasterxml.jackson.core.JsonFactoryBuilder'" error because jackson gets downgraded from 2.10 to 2.9 (which does not have that class). Jackson is a transitive dependency of a library (created by me) added to the custom configuration.

The plugin is generating source code and its dependencies have no impact on the spring boot application itself, they are used only for the generation step.

## workaround

I can make it run by overriding it for my configuration

```
dependencyManagement {
    openapiGeneratr {
          dependencies {
              dependency 'com.fasterxml.jackson.core:jackson-core:2.10.2'
          }
     }
}
```

but this is not very practical for someone using the plugin. It would be necessary for all dependencies (about 50 transitive dependencies) of the library to make sure it is getting the right versions.

## solution?

Is there a way to tell the dependency management plugin to skip my custom configuration? 
Or can I add something to my library so that the versions of the dependencies are not changed?

## sample
Here is a sample project https://github.com/hauner/openapi-generatr-spring-mvc-sample

running the `generatrSpring` task triggers the error (after disabling the workaround)

**Comment by wilkinsona** [comment]
Have you considered using a [detached configuration](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ConfigurationContainer.html#detachedConfiguration-org.gradle.api.artifacts.Dependency...-) in your plugin? That will hide it such that dependency management is not applied to it.

**Comment by hauner** [comment]
No, probably have seen that at some point but didn't see where or why I would use it. :-) 

There is not much info about it. I started with a few code changes and this could work.... May even be simpler than my current code if it works.

Thanks for the hint!

**Comment by wilkinsona** [comment]
No problem. Let me know if it doesn’t work out and we can consider other options.
