### ISSUE TITLE
Fetching `maven-metada.xml` from wrong repository

### ISSUE THREAD

**Issue by wyhasany** [spring-gradle-plugins/dependency-management-plugin#267]
During execution task `:compileJava` (subtask `:detachedConfiguration`) dependency-management-plugin tries to fetch `maven-metadata.xml` from my local maven server. How can I instruct it to use specific repository?  The error looks as follows:
```
Failed to get resource: GET. [HTTP HTTP/1.1 400 Repository version policy: RELEASE does not allow metadata in path: io/springfox/springfox-swagger2/3.0.0-SNAPSHOT/maven-metadata.xml: my_local_nexus/nexus/repository/releases/io/springfox/springfox-swagger2/3.0.0-SNAPSHOT/maven-metadata.xml)]
```

that's related to following springfox snapshot version:
```
val springfoxVersion = "3.0.0-SNAPSHOT"
repositories {
    jcenter {
        name = "jcenter-snapshots"
        url = uri("http://oss.jfrog.org/artifactory/oss-snapshot-local/")
    }
}

dependencies {
    implementation("io.springfox:springfox-swagger2:$springfoxVersion")
    implementation("io.springfox:springfox-swagger-ui:$springfoxVersion")
}
```

I am using newest dependency-management-plugin:
```
plugins {
  id("io.spring.dependency-management") version "1.0.9.RELEASE"
}
```

**Comment by wyhasany** [comment]
that's related to following springfox snapshot version:
```
val springfoxVersion = "3.0.0-SNAPSHOT"
repositories {
    jcenter {
        name = "jcenter-snapshots"
        url = uri("http://oss.jfrog.org/artifactory/oss-snapshot-local/")
    }
}

dependencies {
    implementation("io.springfox:springfox-swagger2:$springfoxVersion")
    implementation("io.springfox:springfox-swagger-ui:$springfoxVersion")
}
```

**Comment by wilkinsona** [comment]
The plugin delegates pom resolution to Gradle. It creates a `Dependency` for each pom that it needs, adds them to a `Configuration` and then asks Gradle to resolve the configuration. Gradle uses the repositories configured in your build for this resolution. In short, only the repositories that are configured in your build should be used. If you have evidence to the contrary, please provide a minimal sample that reproduces it and I can take a look.

**Comment by wyhasany** [comment]
I'll try

**Comment by wyhasany** [comment]
I was wrong. It's not fault of your plugin. It's on the gradle side.

**Comment by wilkinsona** [comment]
Thanks for letting me know.
