### ISSUE TITLE
Provide an alternative to adding bom imports to generated poms

### ISSUE THREAD

**Issue by wilkinsona** [spring-gradle-plugins/dependency-management-plugin#27]
Publishing an artifact using `install` or `mavenPublish` will fail if a bom that isn't available in Maven Central's being used. This appears to be a limitation of Gradle. To work around this limitation the plugin should offer an option (and it should probably be the default) to add versions to the dependencies in the generated bom rather than adding a bom import in the pom's dependency management section.

**Comment by wilkinsona** [comment]
Having given this some more thought, I don't think that adding versions to the individual dependencies is, necessarily, the right approach.

The goal is to produce a pom file that, when consumed by Gradle with this plugin configured or Maven, produces the same dependencies that the project had when it was built. Copying the versions to the dependencies in the pom may not do that as it loses information, for example the information that will affect the versions of transitive dependencies.

I think that a better alternative will be to offer an option that, instead of importing the bom in the generated pom's dependency management section, its contents are duplicated instead. This should result in a pom that has (very close to) the same behaviour as if the bom had been imported, while also allowing the use of a bom that isn't available in Maven Central.

The current behaviour (adding dependency management imports for imported boms) should remain the default.

**Comment by checketts** [comment]
Yes I favor the duplication of dependency management block. In my current usage, I added gradle step that copies the version as you had originally proposed, and that has worked, but I think your second option is better.

**Comment by effiban** [comment]
Hi,
I see that this feature has not been released yet. Any way to workaround the issue until it is?
We have a project where we must use an imported BOM which is not in Maven Central.

Thanks,
Effi

**Comment by wilkinsona** [comment]
Probably easiest if I just push out another release.

Have you tried a snapshot? I'd appreciate if you could do so and verify that it's resolved your problem. They're available from https://repo.spring.io/plugins-snapshot. The version is 0.3.2.BUILD-SNAPSHOT.

**Comment by effiban** [comment]
Snapshot works! Thanks :-)
We'll keep using it until you release the new version.

**Comment by wilkinsona** [comment]
Excellent. Thanks for taking it for a spin. All being well, I'll release a new version (0.4.0.RELEASE) tomorrow.

**Comment by effiban** [comment]
Thanks, that would be very helpful.

One more question if you don't mind:
The parent BOM we use declares Maven properties, and we would like these to be visible to our Gradle build (they indicate "global" version numbers that are used throughout application but not necessarily in each repository).
It seems that the plugin can only import dependencies, but not properties. Is that correct? Any chance this could be added in the future?

**Comment by wilkinsona** [comment]
You're correct. I've opened #29 and tried to capture one use case for the functionality in the issue. If your use case is different, then please feel free to comment on the issue.

**Comment by effiban** [comment]
The use case you mention is the main use case we have. There are a few others too which I'll mention in the PR. Thanks
