### ISSUE TITLE
wrong version of guava selected when importing spring cloud dependencies bom

### ISSUE THREAD

**Issue by jnizet** [spring-gradle-plugins/dependency-management-plugin#280]
I've had a really strange issue when upgrading a private Spring Boot application from version 2.2.1 to version 2.3.1, that I've managed to reproduce in a very small demo project, pinpointing what I think is an issue with the dependency management plugin.

See the repo https://github.com/jnizet/dependency-management-issue for a complete minimal reproduction of the issue. The README explains it, but here's the crux of it:

I have a multi-project build where the `core` java-library project exposes `guava:29.0-jre` in its api dependencies.
The `app` project has a dependency on `core`, and uses the dependency management plugin to import the spring cloud dependencies Maven BOM.

But instead of getting `guava:29.0-jre` in its dependencies (from the core project), it gets `guava:29.0-android` instead.

 - removing the spring cloud dependencies BOM import solves the issue.
 - adding an implementation dependency on `guava:29.0-jre` solves the issue (but that shouldn't be necessary)
 - using the standard gradle way of importing a BOM (i.e. `implementation(platform("org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR6"))`) rather than the dependency management plugin solves the issue.

I tried using `./gradlew :app:dependencyInsight --dependency com.google.guava:guava` and to use a gradle build scan to try understanding why the 29.0-android version is being used, and where it comes from, but I couldn't figure it out.

**Comment by wilkinsona** [comment]
Thanks for the sample. This is due to [a bug in spring-cloud-gcp](https://github.com/spring-cloud/spring-cloud-gcp/issues/2419). You will see the same behaviour with Gradle's native bom support if you used `enforcedPlatform` rather than `platform`:

```diff
diff --git a/app/build.gradle b/app/build.gradle
index 7cca321..3f56fc8 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -11,7 +11,7 @@ repositories {
 }
 
 dependencies {
-    implementation(platform("org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR6"))
+    implementation(enforcedPlatform("org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR6"))
     implementation project(':core')
 }
```

```
$ ./gradlew app:dependencies --configuration runtimeClasspath

> Task :app:dependencies

------------------------------------------------------------
Project :app
------------------------------------------------------------

runtimeClasspath - Runtime classpath of source set 'main'.
+--- org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR6
|    \--- com.google.guava:guava:29.0-android (c)
\--- project :core
     \--- com.google.guava:guava:29.0-jre -> 29.0-android
          +--- com.google.guava:failureaccess:1.0.1
          +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
          +--- com.google.code.findbugs:jsr305:3.0.2
          +--- org.checkerframework:checker-compat-qual:2.5.5
          +--- com.google.errorprone:error_prone_annotations:2.3.4
          \--- com.google.j2objc:j2objc-annotations:1.3

(c) - dependency constraint
A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 535ms
1 actionable task: 1 executed
```

**Comment by jnizet** [comment]
Thanks @wilkinsona 

I've noticed other weird stuff using the dependency management plugin with both spring boot 2.3.1 and spring cloud Hoxton.SR6. They're probably caused by the fact that Spring cloud is (as far as I understand) supposed to release a new version that is compatible with Spring Boot 2.3.1. 
For example, if the core project exposes `influxdb-java` in its api, and the app project imports the spring cloud BOM, then the retrofit dependency in app is downgraded compared to the version in core, which is surprising (I expected it to use the most recent version).

I've solved all these issues by using te standard gradle platform support instead of the dependency management plugin.
Is that something Spring Boot considers recommending in the future instead of using the dependency management plugin?
Do you have any idea when Spring cloud will release a version designed to be compatible with Spring Boot 2.3.1 (and where their roadmap can be found)?

**Comment by wilkinsona** [comment]
> Is that something Spring Boot considers recommending in the future instead of using the dependency management plugin?

Yes, very much so. Unless you are making use of the dependency management plugin's support for overriding version properties, I recommend using Gradle's native bom support over this plugin. Unfortunately, from what we've seen, lots of users make use of that functionality so we can't switch the default. There's some background and further information in https://github.com/spring-projects/spring-boot/issues/21570 and a documentation update planned in https://github.com/spring-projects/spring-boot/issues/21570.

> Do you have any idea when Spring cloud will release a version designed to be compatible with Spring Boot 2.3.1 (and where their roadmap can be found)?

Their roadmap's on GitHub: https://github.com/spring-cloud/spring-cloud-release/milestones

**Comment by jnizet** [comment]
Thanks again @wilkinsona 

I'm reassured to hear you recomend the gradle BOM support. If I ever want a different version than the one specified in one of the BOMs, I will add a explicit dependency constraint to my platform project.
Thanks for the roadmap too. It seems there will be an SR7 version compatible with Boot 2.3.x quite soon. Great!
