### ISSUE TITLE
Spring-vault-core version is getting downgraded

### ISSUE THREAD

**Issue by sibidominic** [spring-gradle-plugins/dependency-management-plugin#282]
We are using id 'io.spring.dependency-management' version '**1.0.10.RELEASE**', along with mavenBom 'org.springframework.cloud:spring-cloud-dependencies:**Hoxton.SR7**'

Hoxton.SR7 has spring-vault-core 2.2.2.RELEASE, but dependency-management is downgrading it to 2.2.0.

 Task :dependencyInsight
org.springframework.vault:spring-vault-core:2.2.0.RELEASE (selected by rule)
   variant "compile" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-api
      org.gradle.libraryelements     = jar (compatible with: classes)
      org.gradle.category            = library
      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 11
   ]

org.springframework.vault:spring-vault-core:2.2.2.RELEASE -> 2.2.0.RELEASE
+--- org.springframework.cloud:spring-cloud-starter-vault-config:2.2.4.RELEASE
|    \--- compileClasspath (requested org.springframework.cloud:spring-cloud-starter-vault-config)
\--- org.springframework.cloud:spring-cloud-vault-config:2.2.4.RELEASE
     \--- org.springframework.cloud:spring-cloud-starter-vault-config:2.2.4.RELEASE (*)

gradle dependencies
|    +--- org.springframework.cloud:spring-cloud-vault-config:2.2.4.RELEASE
|    |    +--- org.springframework:spring-web:5.2.8.RELEASE (*)
|    |    +--- org.springframework.cloud:spring-cloud-commons:2.2.4.RELEASE (*)
|    |    +--- org.springframework.cloud:spring-cloud-context:2.2.4.RELEASE (*)
|    |    \--- org.springframework.vault:spring-vault-core:2.2.2.RELEASE -> 2.2.0.RELEASE
|    |         +--- org.springframework:spring-context:5.2.1.RELEASE -> 5.2.8.RELEASE (*)
|    |         \--- com.fasterxml.jackson.core:jackson-databind:2.10.0 -> 2.11.2 (*)
|    \--- org.springframework.vault:spring-vault-core:2.2.2.RELEASE -> 2.2.0.RELEASE (*)

**Comment by wilkinsona** [comment]
The managed version of spring-vault-core is 2.2.0.RELEASE. You can see this with the following Maven project:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.example</groupId>
	<artifactId>dmp-282</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>dmp-282</name>	
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>Hoxton.SR7</version>
				<scope>import</scope>
				<type>pom</type>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-vault-config</artifactId>
		</dependency>
	</dependencies>
</project>
```

It produces the following dependency tree:

```
[INFO] com.example:dmp-282:jar:0.0.1-SNAPSHOT
[INFO] \- org.springframework.cloud:spring-cloud-starter-vault-config:jar:2.2.4.RELEASE:compile
[INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.10:compile
[INFO]    |  \- commons-codec:commons-codec:jar:1.11:compile
[INFO]    +- org.apache.httpcomponents:httpcore:jar:4.4.12:compile
[INFO]    +- org.springframework.cloud:spring-cloud-starter:jar:2.2.4.RELEASE:compile
[INFO]    |  +- org.springframework.boot:spring-boot-starter:jar:2.3.2.RELEASE:compile
[INFO]    |  |  +- org.springframework.boot:spring-boot:jar:2.3.2.RELEASE:compile
[INFO]    |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.3.2.RELEASE:compile
[INFO]    |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.3.2.RELEASE:compile
[INFO]    |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO]    |  |  |  |  +- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO]    |  |  |  |  \- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO]    |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.13.3:compile
[INFO]    |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.13.3:compile
[INFO]    |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.30:compile
[INFO]    |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO]    |  |  +- org.springframework:spring-core:jar:5.2.8.RELEASE:compile
[INFO]    |  |  |  \- org.springframework:spring-jcl:jar:5.2.8.RELEASE:compile
[INFO]    |  |  \- org.yaml:snakeyaml:jar:1.26:compile
[INFO]    |  +- org.springframework.cloud:spring-cloud-context:jar:2.2.4.RELEASE:compile
[INFO]    |  |  \- org.springframework.security:spring-security-crypto:jar:5.3.3.RELEASE:compile
[INFO]    |  +- org.springframework.cloud:spring-cloud-commons:jar:2.2.4.RELEASE:compile
[INFO]    |  \- org.springframework.security:spring-security-rsa:jar:1.0.9.RELEASE:compile
[INFO]    |     \- org.bouncycastle:bcpkix-jdk15on:jar:1.64:compile
[INFO]    |        \- org.bouncycastle:bcprov-jdk15on:jar:1.64:compile
[INFO]    +- org.springframework.cloud:spring-cloud-vault-config:jar:2.2.4.RELEASE:compile
[INFO]    |  \- org.springframework:spring-web:jar:5.2.8.RELEASE:compile
[INFO]    |     \- org.springframework:spring-beans:jar:5.2.8.RELEASE:compile
[INFO]    \- org.springframework.vault:spring-vault-core:jar:2.2.0.RELEASE:compile
[INFO]       +- org.springframework:spring-context:jar:5.2.1.RELEASE:compile
[INFO]       |  +- org.springframework:spring-aop:jar:5.2.1.RELEASE:compile
[INFO]       |  \- org.springframework:spring-expression:jar:5.2.1.RELEASE:compile
[INFO]       \- com.fasterxml.jackson.core:jackson-databind:jar:2.10.0:compile
[INFO]          +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.0:compile
[INFO]          \- com.fasterxml.jackson.core:jackson-core:jar:2.10.0:compile
```

As you can see, `spring-vault-core` is `2.2.0.RELEASE`:

```
[INFO]    \- org.springframework.vault:spring-vault-core:jar:2.2.0.RELEASE:compile
```

This comes from [the `spring-vault.version` property in `spring-cloud-config-dependencies`](https://github.com/spring-cloud/spring-cloud-config/blob/fc58acc331d18a0892558c376eeadab591fc4716/spring-cloud-config-dependencies/pom.xml#L19). You may want to ask the Spring Cloud team why they are downgrading the version that's [defined in `spring-cloud-vault-dependencies`](https://github.com/spring-cloud/spring-cloud-vault/blob/v2.2.4.RELEASE/spring-cloud-vault-dependencies/pom.xml#L23).
