### ISSUE TITLE
dependency resolution not working for subprojects

### ISSUE THREAD

**Issue by bradmac-ats** [spring-gradle-plugins/dependency-management-plugin#283]
It seems as though the dependency resolution plugin isn't working in subprojects? I'm using 1.0.10 and Gradle 6.4.1

> Could not find "org.springframework.boot:spring-boot-starter:.
> Required by:
>     project : > project :core
> 
> Possible solution:
>  - Declare repository providing the artifact, see the documentation at 
> https://docs.gradle.org/current/userguide/declaring_repositories.html

This little project demonstrates the issue:
[restapi-demo.zip](https://github.com/spring-gradle-plugins/dependency-management-plugin/files/5110289/restapi-demo.zip)

**Comment by wilkinsona** [comment]
There's a typo in your build script:

```
'"org.springframework.boot'
```

It should be:

```
'org.springframework.boot'
```
