### ISSUE TITLE
after using `maven-publish` to package and release and introduced to other projects, the version is lost

### ISSUE THREAD

**Issue by halower** [spring-gradle-plugins/dependency-management-plugin#286]
hi, I use gradle 6.7.1 and the maven-publish plugin to publish the following public class library that uses dependency management. The name is  `a-module.jar`, which is normal  working in the library, but when I import this jar  use complie('xxxx: a-moudle:1.0.0') in other project, will cause the version managed in the pom (xxx:common-denpendences:1.0.0) to be lost
``` 
plugins {
    id "io.spring.dependency-management"
}

dependencyManagement {
    dependencies {
        imports {
            mavenBom 'xxx:common-denpendences:1.0.0'
        }

    }
}

dependencies {
    api ('commons-io:commons-io: 2.8.0')
    ...
}
```

import other project ，for example,

```
dependencies {
   // this lib include the commons-io:commons-io: 2.8.0, infact 2.8.0 has lost
    api ('xxx:a-module: 1.0.0')
    ...
}
```

 the expectation is `compile('commons-io:commons-io: 2.8.0') ` in fact, an error will be reported, the version number (2.8.0) has not been inherited, and `dependencyManagement` must be introduced again for management, but it works normally in the `gradle 4.x ` . after the migration and upgrade, the version is lost. How can I modify this problem (can it be achieved without `gradle platform`)?

**Comment by wilkinsona** [comment]
When `a-module` is published, the dependency management plugin should [automatically update its pom to include dependency management information](https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/#pom-generation). When `a-module` is then consumed from a Maven repository in another build, that dependency management should take effect. It sounds like that isn't happening for you but I can't tell why from what you have shared thus far. Can you please share a minimal project that reproduces the behaviour that you have described? You mentioned that it works with Gradle 4.x. A project that works with 4.x and fails with 6.7.1 would be ideal.

**Comment by halower** [comment]
[gradle-demo.zip](https://github.com/spring-gradle-plugins/dependency-management-plugin/files/5699733/gradle-demo.zip)
this a  minimal project
`dependence_pom` is pom file that will be publish private local repository
`a-module` reference `dependence_pom`
`b-module` is a separate project

**Comment by wilkinsona** [comment]
Your dependencies pom is incorrect. It is missing `<packaging>pom</packaging>`. This causes Gradle to look for both a `.jar` file and and `.pom` file, when the `.jar` file can't be found, the artifact is ignored. You can see this by running your build with `--debug` and looking at Gradle's log output.

**Comment by halower** [comment]
**sorry, it's missing in the demo，in fact, it is not the problem of missing the packaging node. at present, no solution has been found. where did I write it? Is there any error? please continue to guide, thank you .**

 **the pom  in my private repository as follows**
![image](https://user-images.githubusercontent.com/4995227/102338037-40ecb680-3fce-11eb-99da-3f0aa2591505.png)
**the POM file generated after publishing is as follows**
![image](https://user-images.githubusercontent.com/4995227/102338764-3e3e9100-3fcf-11eb-812a-314c5a1093ab.png)
**the effect of the introduction in idea is as follows**
![image](https://user-images.githubusercontent.com/4995227/102339025-8e1d5800-3fcf-11eb-81b7-7dbeafbe3d9c.png)

**Comment by wilkinsona** [comment]
To be able to continue to guide you, I'll need a sample project that accurately reproduces the problem. In its current state, your sample does not do that. In addition to the missing pom packaging, it also refers to a private Maven repository to which I do not have access and the version of the `newbie-spring-boot-dependencies` import does not match that versions that's deployed.

**Comment by halower** [comment]
thank you very much for your reply. next, I will browse the use of gradle in the springboot source code repository. maybe I haven't grasped the problems caused by its usage. If it can't be solved, or solved, I will feedback here.

**Comment by halower** [comment]
I used Java platform Plugin to implement version management instead of maven pom
