### ISSUE TITLE
Applying Spring Boot Gradle plugin to large scale multi project slow down IntelliJ reload.

### ISSUE THREAD

**Issue by kazuki-ma** [spring-gradle-plugins/dependency-management-plugin#288]
> Enhancement (please don't include this emoji/text, just add your details)

(Moved from https://github.com/spring-projects/spring-boot/issues/24612)

## Problems
We have large scale server side project using spring-boot gradle plugin. (~200 modules)

After using spring-boot dependency management, IntelliJ idea gradle reload tooks over 2 minutes.
If I set `setApplyMavenExclusions(false)` it reduced to 30 seconds. (improved. But I thinks it's not best).

## Goal

If you have any idea (Known limitation, option or workaround etc..) please let me know.

**Comment by kazuki-ma** [comment]
In my case, if `setApplyMavenExclusions(false)` is set `isDependencyOnLocalProject` is one hotspot.

![image](https://user-images.githubusercontent.com/1370068/103112711-88440880-469a-11eb-9f78-a5410e186e5e.png)

**Comment by kazuki-ma** [comment]
In my case`isDependencyOnLocalProject` occupied 12,540 samples by profiler (25,460 samples total).
It's about 50% of CPU usage.

Graphs below.
Full width = all java code execution during IntelliJ reload. Except GC time.
Highlighted width = `isDependencyOnLocalProject` execution.

![image](https://user-images.githubusercontent.com/1370068/103123234-fe5e6480-46c6-11eb-9f45-f10c38577177.png)

This is because gradle's `.getAllprojects()` is heavy and not optimized for frequency call.

This hotspot executes every (project x configuration x dependency pair) 😢 .

Anyway, in this use case, we can cache local project name.

**Comment by kazuki-ma** [comment]
Another reason of why gradle realod is heavy is `applyMavenExclusions`.

![image](https://user-images.githubusercontent.com/1370068/103125224-c60e5480-46cd-11eb-9790-cd693910c9ea.png)

Note: There is workaround. put `setApplyMavenExclusions(false)`.

There are any significant difference in my case. (example: protobuf module is exclude from MySQL connector or not)

**Comment by wilkinsona** [comment]
Thanks for the report. The support for Maven-style exclusions has been through a few rounds of optimisation and I think it's as fast as it can reasonably be. Caching the local project names sounds like a good thing to do. We can use #289 to do that (thanks for the PR).
