### ISSUE TITLE
Expose properties in imported Maven boms to the Gradle build

### ISSUE THREAD

**Issue by wilkinsona** [spring-gradle-plugins/dependency-management-plugin#29]
It's common for a Maven pom to use properties to configure its versions. It would be useful to be able to reuse these properties from within a Gradle build. A concrete example is Spring Boot's bom. It declares a property for the version of Hibernate, `hibernate.version`, but doesn't provide dependency management for every Hibernate module. Having access to the `hibernate.version` property would allow additional Hibernate dependencies to easily use the same version as the imported bom uses.

**Comment by wilkinsona** [comment]
I'm envisaging the properties being available via `dependencyManagement.properties` for global dependency management and perhaps `dependencyManagement.<configuration>.properties` for configuration-specific dependency management.

**Comment by effiban** [comment]
A few other examples of properties we have in our bom and would like to reuse, which are not related to artifact versions:

* JDK version
* artifactory URL (not sure if this makes sense since maybe it needs to be defined first)
* character encoding

**Comment by wilkinsona** [comment]
@effiban If you have a moment please try out `0.4.0.BUILD-SNAPSHOT` (available from https://repo.spring.io/plugins-snapshot) and let me know if it meets your needs.

**Comment by effiban** [comment]
Just tried it, works fine :-)
