### ISSUE TITLE
Exclusions from Maven BOMs not applied under specific conditions

### ISSUE THREAD

**Issue by GFriedrich** [spring-gradle-plugins/dependency-management-plugin#298]
Recently I've stumbled into an issue of non-working exclusions from Maven BOMs.
It only happens when using a very specific project setup.
I've created a minimal reproducible example (see [exclusion-issue.zip](https://github.com/spring-gradle-plugins/dependency-management-plugin/files/6137509/exclusion-issue.zip)). The main project is the "exclusion-issue" project and to trigger the issue you need to include the composite build in the settings.gradle.kts.

I've also already did a root-cause analysis and came up with the following:

### Requirements:
* Use a BOM to manage your dependencies (e.g. simply use the Spring Boot plugin)
* Have a dependency in your build script, which was added to two different configurations (e.g. "implementation" and "runtimeOnly")
* Have an included build in your project setup (see reasons below)

### What is expected?
The exclusions from the BOM shall be applied properly to your build and e.g. when running the "bootJar" task to create the Spring Boot Jar this Jar shouldn't contain the excluded Jars.

### What happens?
E.g. for the given attached example project the Boot Jar contains the commons-logging library, even though this one is excluded in the Spring Boot BOM.

### Why is that?
When running the BootJar task normally the "compileJava" task gets triggered first which resolves the "compileClasspath". This in turn applies the exclusions to all the compile dependencies (e.g. "implementation"). Afterwards the "bootJar" gets executed and by that the "runtimeClasspath" gets resolved, so that the "runtimeOnly" dependencies are resolved and exclusions are applied accordingly.
But when using a composite build, things are running in a different order:
Due to the composite build the creation of the task graph for the "bootJar" ends up in the resolution of the "runtimeClasspath" first (which is used later on by the Boot Jar). As the exclusions are applied to the DependencySet of the "runtimeClasspath" containing all dependencies from the configurations hierarchy, only one of two dependencies is contained in this Set (because it is a Set - not a List - and both dependencies are basically the same).
You can find the bad code here: https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/39c37fc944794b9ff6615f894f2d5c053061682a/src/main/java/io/spring/gradle/dependencymanagement/internal/ExclusionConfiguringAction.java#L98-L107

So only one of two dependencies will receive the exclusions but both are used when resolving the "runtimeClasspath" later on, which in turn results in excluded artifacts in the Boot Jar, which were originally excluded from the BOMs.
From my point of view the issue here is, that the plugin relies on the fact that the configurations are resolved in a specific order.
To fix the issue I've patched my local copy of the plugin with applying the exclusions to the entire configuration hierarchy which worked without any issues.
E.g. a code like this worked for me:
```java
for (Configuration configuration : configuration.getHierarchy()) {
    for (org.gradle.api.artifacts.Dependency dependency : configuration.getDependencies()) {
        if (dependency instanceof ModuleDependency) {
            for (Map<String, String> exclusion : exclusions) {
                ((ModuleDependency) dependency).exclude(exclusion);
            }
        }
    }
}
```

In case you've questions, feel free to ask. Otherwise I would be happy if the issue could be resolved. 😄

**Comment by wilkinsona** [comment]
Thanks very much for reporting this and for the detailed analysis.

>  As the exclusions are applied to the DependencySet of the "runtimeClasspath" containing all dependencies from the configurations hierarchy, only one of two dependencies is contained in this Set (because it is a Set - not a List - and both dependencies are basically the same).

It may also be because the plugin's using `getDependencies()` rather than `getAllDependencies()`. I'm not sure if the dependency would appear twice in the set when getting all dependencies or if they are indeed considered the same so will only appear once.

Is `configuration` in your code above `this.configuration` on `ExclusionConfiguringAction`?

**Comment by GFriedrich** [comment]
The current implementation of `resolvableDependencies.getDependencies()` in fact calls `getAllDependencies()` internally. So this is already the case and doesn't help at all. 😞

And yes: The outer `configuration` is the `configuration` from the `ExclusionConfiguringAction`. The current method argument of `resolvableDependencies` wouldn't be used at all then.

**Comment by wilkinsona** [comment]
I haven't been able to convince myself that it's safe to use the whole configuration hierarchy when applying the exclusions. Unfortunately that means that the risk of fixing this is greater than the benefits. The long-term plan is to [remove support for Maven-style exclusion semantics](https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/331). In the meantime, your local patched version of the plugin is probably the best option. Alternatively, you could use one of Gradle's standard exclusion mechanisms instead.
