### ISSUE TITLE
Describe plugin more clearly

### ISSUE THREAD

**Issue by jkellyinsf** [spring-gradle-plugins/dependency-management-plugin#305]
Can you clarify the first couple lines of the readme and the description at https://plugins.gradle.org/plugin/io.spring.dependency-management?

> A Gradle plugin that provides Maven-like dependency management and exclusions. The plugin provides a DSL to configure dependency management directly and by importing existing Maven boms.

Gradle already provides a DSL for configuring dependencies. It's already "Maven-like" in all sorts of ways, including importing BOMs.  What problem, if any, does this plugin solve?

**Comment by wilkinsona** [comment]
Duplicates #211.
