### ISSUE TITLE
Provide an option to not generate <dependencyManagement/> tag

### ISSUE THREAD

**Issue by quaff** [spring-gradle-plugins/dependency-management-plugin#309]
https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:resolved_dependencies
Gradle supports resolving version for every dependency now, then the `<dependencyManagement/>` is superfluous, Currently I need to remove it in `pom.withXml {}`.
```groovy
publishing {
	publications {
		maven(MavenPublication) {
			from components.java
			versionMapping {
				usage("java-api") {
					fromResolutionOf("runtimeClasspath")
				}
				usage("java-runtime") {
					fromResolutionResult()
				}
			}
			pom.withXml {
				var node = asNode()
				node.remove(node.dependencyManagement[0])
			}
		}
	}
}
```

**Comment by wilkinsona** [comment]
As [described in the documentation](https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/#pom-generation-disabling), customization of the pom can already be disabled.

**Comment by quaff** [comment]
👍 Great!

**Comment by quaff** [comment]
Could we check if `versionMapping` present then disable it by default?

**Comment by wilkinsona** [comment]
While I think that would be technically possible, I would prefer not to add the complexity that it would bring both in terms of the code and in the behaviour of the configuration option. For example, what would happen if customization of the pom has been explicitly enabled yet every dependency has a version?

**Comment by quaff** [comment]
> While I think that would be technically possible, I would prefer not to add the complexity that it would bring both in terms of the code and in the behaviour of the configuration option. For example, what would happen if customization of the pom has been explicitly enabled yet every dependency has a version?

Only set the default `enabled` to `false` if `versionMapping` of `MavenPublication` present, if user set `enabled` explicitly, respect it no matter `true` or `false`.

**Comment by wilkinsona** [comment]
Thanks for the suggestion,  but as I said above, I don't want to add the complexity.
