### ISSUE TITLE
Transitive platform dependencies may prevent exclusions from being applied

### ISSUE THREAD

**Issue by akvone** [spring-gradle-plugins/dependency-management-plugin#310]
We have [a project](https://github.com/akvone/bug-gradle-platform-disables-spring-exclusions/commit/1ff036fa7fb8dfac05db70b0dcb73d2bdaed9b8f) with `spring-boot-dependencies:2.4` and excluded transitive dependency (`junit`):
```
dependencies {
    implementation('org.apache.xmlrpc:xmlrpc-client')
    implementation('com.fasterxml.jackson.core:jackson-databind')
}

dependencyManagement {
    imports{
        mavenBom("org.springframework.boot:spring-boot-dependencies:2.4.4")
    }
    dependencies {
        dependency('org.apache.xmlrpc:xmlrpc-client:3.1.3') {
            exclude 'junit:junit'
        }
    }
}
```
When we [tried to bump a version](https://github.com/akvone/bug-gradle-platform-disables-spring-exclusions/commit/2d03a479761c12f1fb6fed3602377af666e76a79) to `spring-boot-dependencies:2.5` the `junit` appeared again. 
It turned out that `spring-boot-dependencies:2.5` brings jackson dependencies with version 2.12 instead of 2.11 which in turn [started to publish Gradle metadata](https://github.com/FasterXML/jackson-core/issues/672) which brings Jackson platform  (`jackson-bom`). The platform controls `junit` and this disables our exclusion.

The same behavior appears if we just use [jackson dependency with version 2.12](https://github.com/akvone/bug-gradle-platform-disables-spring-exclusions/commit/6caaec74efceb5150edb774cc40973ce3a1e6023) or if we use [`jackson-bom` platform](https://github.com/akvone/bug-gradle-platform-disables-spring-exclusions/commit/dd92d29353e656de07f89673c724bf79c76d6017).

After reading the Gradle documentation and some existing issues we found a [solution](https://github.com/akvone/bug-gradle-platform-disables-spring-exclusions/commit/0b718c45bda5d70fe6237cafbefdc7289340f6e2): we also exclude `junit` from the platform:
```
dependencyManagement {
    imports{
        mavenBom("org.springframework.boot:spring-boot-dependencies:2.5.4")
    }
    dependencies {
        dependency('org.apache.xmlrpc:xmlrpc-client:3.1.3') {
            exclude 'junit:junit'
        }
        dependency('com.fasterxml.jackson:jackson-bom:2.12.4'){
            exclude 'junit:junit'
        }
    }
}
```

The question is: Do we use the correct way to handle such logic? And could the documentation contain a warning about this case?

**Comment by akvone** [comment]
We use `gradle dependencies --configuration=runtimeClasspath` to see the classpath

**Comment by wilkinsona** [comment]
I am surprised that JUnit appearing in Jackson's bom (which should only affect its version if it already appears in the dependency graph) prevented its exclusion. It would appear that the appearance of the dependency constraints in the resolution result is confusing the algorithm that determines the dependencies that should be excluded. I think it probably needs to be updated to ignore dependencies where the selected variant's `org.gradle.category` attribute has a value of `platform`.

**Comment by akvone** [comment]
Got it, thank you.
