### ISSUE TITLE
Spring Boot 2.7.0 has incompatible org.jooq:jooq:{jooq.version}

### ISSUE THREAD

**Issue by minseokLim** [spring-gradle-plugins/dependency-management-plugin#323]
Since SpringBoot 2.7.0, SpringBoot has depended on 'com.h2database:h2:2.1.212'.
'org.springframework.boot:spring-boot-starter-jooq:2.7.0' depends on 'org.jooq:jooq:3.14.15'.
However, 'org.jooq:jooq:3.14.15' doesn't support 'com.h2database:h2:2.1.212'.
Please check [here](https://www.jooq.org/download/support-matrix)

So, whenever I try to generate codes with jooq, I can find these kinds of exceptions.
![image](https://user-images.githubusercontent.com/36442984/170810076-0324d83b-0060-422d-995e-6a5debb7ed3c.png)

Please change the version of jooq in spring-boot-starter-jooq, and check the compatibility.

**Comment by minseokLim** [comment]
It just occurred to me that this might be a problem of JOOQ, not Spring Dependency, because they say 'Minimum version' in [here](https://www.jooq.org/download/support-matrix). It's confusing, because I'm not sure that JOOQ can solve this problem.

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-projects/spring-boot/issues/31168.
