### ISSUE TITLE
Configurations

### ISSUE THREAD

**Issue by corneil** [spring-gradle-plugins/dependency-management-plugin#34]
I was trying to use the plugin on this project: https://github.com/corneil/spring-data-demo

I added an importBom for Spring IO 1.1.1 and only removed versions from spring dependencies.
The QueryDSL APT fails with strange errors. I think it may be because the generator is using a different configuration.

**Comment by wilkinsona** [comment]
"Fails with strange errors" isn't very helpful as it doesn't explain why you think there's a problem with the plugin. If you'd like me to investigate please provide some more information, ideally some code somewhere that reproduces the failure.

**Comment by corneil** [comment]
My apologies. I did manage to find the problem, it was on my side. 

On a different note, I would like to make some suggestions:
I am assuming the plugin updates the versions on dependencies after projects was loaded. I would suggest it print a warning/error if it finds a dependency without a version that isn't in the bom. 

The syntax around entry and exclude seem a bit ambiguous  by requiring a comma before the { in some cases.

**Comment by wilkinsona** [comment]
> I am assuming the plugin updates the versions on dependencies after projects was loaded. I would suggest it print a warning/error if it finds a dependency without a version that isn't in the bom.

The plugin can't assume that it's the only thing that will apply a version to a dependency. For example, there may be a resolution strategy that runs after the plugin that does so. This means that any warning or error that it produces may be incorrect so I don't think it's appropriate for the plugin to print anything.

> The syntax around entry and exclude seem a bit ambiguous by requiring a comma before the { in some cases.

Is this the difference that you're referring to:

```
entry 'spring-core' {
    exclude 'commons-logging:commons-logging'
}
```

vs

```
'org.springframework:spring-core' '4.0.3.RELEASE', {
    exclude 'commons-logging:commons-logging'
}
```

Unfortunately, Groovy seems to require the comma in the latter case (I suspect it's a side effect of using `methodMissing`). The syntax could become:

```
dependency 'org.springframework:spring-core:4.0.3.RELEASE` {
    exclude 'commons-logging:commons-logging'
}
```

This perhaps is better aligned with Gradle's DSL, however I'm not convinced that the benefit outweighs the increased verbosity.

**Comment by corneil** [comment]
I figured out that project with multiple modules is a little tricky.

The solution was to create a gradle file called dependencies.gradle that I placed in the root project.

    apply plugin: "io.spring.dependency-management"
    dependencyManagement {
        imports {
            mavenBom 'io.spring.platform:platform-bom:1.1.1.RELEASE'
            mavenBom 'org.springframework.data:spring-data-releasetrain:Evans-SR2'
        }
    }

Then in the root project:

    subprojects {
        apply from: new File(rootProject.projectDir, 'dependencies.gradle')
    }

Adding the dependencyManagement block inside of subproject was not resulting in version numbers on resolution.

**Comment by corneil** [comment]
I would vote for:

    dependency 'org.springframework:spring-core:4.0.3.RELEASE` {
        exclude 'commons-logging:commons-logging'
    }

It just seems consistent with the rest of gradle DSL.
It should also allow:

    dependency(group:'org.springframework', name:'spring-core', version:'4.0.3.RELEASE` {
        exclude 'commons-logging:commons-logging'
    }

This way converting pom to gradle is straight forward and copying existing dependency definitions to the dependencyManagement section doesn't require a lot of fiddling.

**Comment by wilkinsona** [comment]
> I figured out that project with multiple modules is a little tricky.

As far as I know, the approach that you've taken isn't necessary. There's also nothing special for a plugin to do to handle `subprojects` so it's not clear why you believe there's a problem with the plugin.

This works fine for me:

**build.gradle**
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'io.spring.gradle:dependency-management-plugin:0.4.0.RELEASE'
    }
}

allprojects {
    group 'sample'
}

subprojects {
    repositories {
        jcenter()
    }

    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'

    dependencyManagement {
        imports {
            mavenBom 'io.spring.platform:platform-bom:1.1.1.RELEASE'
        }
    }

    dependencies {
        compile 'org.springframework:spring-core'
    }
}
```

**settings.gradle**
```
include "alpha", "bravo"
```

**Dependencies output**
```
$ gradle alpha:dependencies --configuration compile
:alpha:dependencies

------------------------------------------------------------
Project :alpha
------------------------------------------------------------

compile - Compile classpath for source set 'main'.
\--- org.springframework:spring-core: -> 4.1.4.RELEASE

BUILD SUCCESSFUL

Total time: 3.062 secs

$ gradle bravo:dependencies --configuration compile
:bravo:dependencies

------------------------------------------------------------
Project :bravo
------------------------------------------------------------

compile - Compile classpath for source set 'main'.
\--- org.springframework:spring-core: -> 4.1.4.RELEASE

BUILD SUCCESSFUL

Total time: 3.113 secs
```

If you believe that there is a problem, please open a separate issue with sufficient information to recreate the problem.

**Comment by corneil** [comment]
I hadn't put enough inside of subprojects initially.
I tried it quickly with the content of dependencies.gradle at the bottom of subprojects closure.
I have the hang of it now.
I prefer the dependency management stuff in a separate file.

Thanks
