### ISSUE TITLE
Support Gradle Module Metadata

### ISSUE THREAD

**Issue by rpost** [spring-gradle-plugins/dependency-management-plugin#342]
Plugin (by default!) customizes generated pom.xml in case of using `maven-publish` plugin. Modern versions of gradle produce https://docs.gradle.org/current/userguide/publishing_gradle_module_metadata.html as well (along to pom.xml) which is not customized. Can you apply pom changes to gradle module metadata as well?

**Comment by wilkinsona** [comment]
I don't believe that's possible as Gradle does not provide APIs for customizing the module metadata. It may be something that happens in the future as a side-effect of https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/330. However, if you're interested in modern Gradle features such as its module metadata, I would recommend not using this plugin and using modern Gradle features such as version catalogs and (enforced) platforms for version management.
