### ISSUE TITLE
v1.0.15.RELEASE appears to be unpublished from Gradle Plugin Portal

### ISSUE THREAD

**Issue by kyrylo-merzlikin-blablacar** [spring-gradle-plugins/dependency-management-plugin#343]
There is no version 1.0.15.RELEASE of this plugin [on Gradle Plugin Portal](https://plugins.gradle.org/plugin/io.spring.dependency-management/1.0.15.RELEASE), even though this version exists [on Maven Central](https://mvnrepository.com/artifact/io.spring.gradle/dependency-management-plugin/1.0.15.RELEASE) and there is a reference to it [in the Spring Boot Project v2.7.5](https://github.com/spring-projects/spring-boot/blob/v2.7.5/spring-boot-project/spring-boot-dependencies/build.gradle#L258).

This issue was also mentioned by other people [on Gitter](https://gitter.im/spring-gradle-plugins/dependency-management-plugin?at=635f8426cf41c67a5cd77984).

**Comment by wilkinsona** [comment]
Thanks for catching this. 1.0.15.RELEASE is now available from the Plugin Portal.

**Comment by AlexBen** [comment]
Hi!
https://repo.gradle.org/ui/native/jcenter/io/spring/gradle/dependency-management-plugin/1.0.15.RELEASE/dependency-management-plugin-1.0.15.RELEASE.pom - still not there, and not even in the list (after 1.0.13.RELEASE):
https://repo.gradle.org/ui/native/jcenter/io/spring/gradle/dependency-management-plugin/

Should we just wait a bit?

**Comment by wilkinsona** [comment]
There appear to be problems with JCenter: https://status.gradle.com/incidents/9740r6bzx438. I'd recommend getting the plugin from Maven Central in the meantime.
