### ISSUE TITLE
Groovy version is not managed for Spring Boot >= 3.0

### ISSUE THREAD

**Issue by Ibanezos92** [spring-gradle-plugins/dependency-management-plugin#349]
I am migrating an old Spring Boot (2.1.3) + Groovy (2.5.6) Gradle (5.5.1) project to the newest versions for all of its components using Java 17. 
In the mentioned configuration, with the following Gradle script, the auto-deduction of Groovy version was 2.5.6:
build.gradle (with JDK 8)
```
plugins {
    id 'org.springframework.boot' version '2.1.3.RELEASE'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'groovy'
}

dependencies {
    implementation 'org.codehaus.groovy:groovy'
}
```
In my newest configuration with JDK 17 and Gradle 8.0.1:
```
plugins {
    id 'org.springframework.boot' version '3.0.3'
    id 'io.spring.dependency-management' version "1.1.0"
    id 'groovy'
}

dependencies {
   implementation 'org.codehaus.groovy:groovy'
}
```
The automatic resolution fails. 
When setting to:
```
id 'org.springframework.boot' version '2.7.9'
```
The resolution of groovy version is 3.0.15.

**Comment by wilkinsona** [comment]
Spring Boot 3.0 uses Groovy 4 [where the `org.codehaus.groovy:groovy` module no longer exists](https://groovy-lang.org/releasenotes/groovy-4.0.html). You should use `org.apache.groovy:groovy` instead.
