### ISSUE TITLE
Align the dependency syntax with Gradle's DSL

### ISSUE THREAD

**Issue by wilkinsona** [spring-gradle-plugins/dependency-management-plugin#35]
With the `dependencyManagement` block, declaring a version for individual dependencies is currently done like this:

```groovy
dependencyManagement {
    dependencies {
        'org.springframework:spring-core' '4.0.3.RELEASE'
    }
}
```

And with an exclusion, it looks like this:

```groovy
dependencyManagement {
    dependencies {
        'org.springframework:spring-core' '4.0.3.RELEASE', {
            exclude 'commons-logging:commons-logging'
        }
    }
}
```

Note the comma before the closure and the lack of brackets which is inconsistent with the configuration for a `dependencySet`:

```groovy
dependencyManagement {
    dependencies {
        dependencySet(group:'org.springframework', version: '4.1.4.RELEASE') {
            entry 'spring-core' {
                exclude 'commons-logging:commons-logging'
            }
        }
    }
}
```

Gradle's DSL already has set something of a precedent for this sort of configuration in its support for [client module dependencies](https://gradle.org/docs/current/userguide/dependency_management.html):

```groovy
dependencies {
    runtime module("org.codehaus.groovy:groovy:2.3.6") {
        dependency("commons-cli:commons-cli:1.0") {
            transitive = false
        }
    }
}
```

Based on this precedent, I think the syntax for management of individual dependencies should be:

```groovy
dependencyManagement {
    dependencies {
        dependency 'org.springframework:spring-core:4.1.4.RELEASE'
    }
}
```

The map-based syntax that allows named parameters should also be supported:

```groovy
dependencyManagement {
    dependencies {
        dependency group: 'org.springframework', name: 'spring-core', version: '4.1.4.RELEASE'
    }
}
```

This syntax change will also remove the need for the comma prior to the closure when configuring exclusions:

```groovy
dependencyManagement {
    dependencies {
        dependency('org.springframework:spring-core:4.0.3.RELEASE') {
            exclude 'commons-logging:commons-logging'
        }
    }
}
```

This will be a breaking API change for a core piece of the plugin's functionality. The plan is to add support for the new syntax in 0.4.1 and deprecate the old syntax prior to removing it in 0.5.

**Comment by checketts** [comment]
By adding in the `dependency` syntax, can we eliminate the surrounding `dependencies` block?

**Comment by wilkinsona** [comment]
I did consider this briefly, but I came to the conclusion that the `dependencies` block should remain. It provides nice separation between Maven bom imports and direct dependency management configuration. The separation has benefits for the readability of a build script and the structure of the code that implements the DSL.

**Comment by checketts** [comment]
Would allowing separating out the version, splitting with a comma make sense? This is more for conversation than a request.

My motivation is with my current dependency managed versions I have several related versions and being able to align them has made them stand out as a unit.

```
dependencyManagement {
    dependencies {
                def jacksonVersion = '2.4.4'
                dependency 'com.fasterxml.jackson.core:jackson-core',                   jacksonVersion
                dependency 'com.fasterxml.jackson.core:jackson-databind',               jacksonVersion
                dependency 'com.fasterxml.jackson.core:jackson-annotations',            jacksonVersion
                dependency 'com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider',   jacksonVersion
                dependency 'com.fasterxml.jackson.datatype:jackson-datatype-joda',      jacksonVersion
                dependency 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml',   jacksonVersion
    }
}
```

(Though clearly the version variable also groups them in a way)

**Comment by wilkinsona** [comment]
I'm keen to align with Gradle's conventions and, as far as I know, it doesn't support that syntax. You could, however, use the map-based syntax with similar effect:

```
dependencyManagement {
    dependencies {
        def jacksonVersion = '2.4.4'
        dependency(group:'com.fasterxml.jackson.core',       name:'jackson-core', version:       jacksonVersion)
        dependency(group:'com.fasterxml.jackson.core',       name:'jackson-databind',            jacksonVersion)
        dependency(group:'com.fasterxml.jackson.core',       name:'jackson-annotations',         jacksonVersion)
        dependency(group:'com.fasterxml.jackson.jaxrs',      name:'jackson-jaxrs-json-provider', jacksonVersion)
        dependency(group:'com.fasterxml.jackson.datatype',   name:'jackson-datatype-joda',       jacksonVersion)
        dependency(group:'com.fasterxml.jackson.dataformat', name:'jackson-dataformat-xml',      jacksonVersion)
    }
}
```

**Comment by checketts** [comment]
I agree aligning with Gradle's syntax is best. Sorry if these questions are ranging far a field, I believe they are pertinent in regards to the discussion of the breaking API changes though.

How does it best address using variables with the shorthand syntax?

Is a GString the best option?
```
dependencyManagement {
    dependencies {
        def jacksonVersion = '2.4.4'
        dependency "com.fasterxml.jackson.core:jackson-core:$jacksonVersion"
    }
}
```

Or concatenation?
```
dependencyManagement {
    dependencies {
        def jacksonVersion = '2.4.4'
        dependency 'com.fasterxml.jackson.core:jackson-core:'+$jacksonVersion
    }
}
```

The purpose of this question is to see if there is an opportunity to 'bake in' support of external variables. For example in my usecases the `jacksonVersion` mentioned above is actually populated based more like so:

```
def jacksonVersion = "2.4.4"
if project.hasProperty('jacksonVersion'){
    jacksonVersion = project.jacksonVersion
}
```
