### ISSUE TITLE
Update the reference documentation to use more up-to-date examples

### ISSUE THREAD

**Issue by jearton** [spring-gradle-plugins/dependency-management-plugin#354]
spring.version -> spring-framework.version

**Comment by wilkinsona** [comment]
Thanks for the report but I'm not sure what problem you're reporting. The examples in the docs are using the (now admittedly end-of-life) Spring IO Platform bom that does contain a `spring.version` property. Can you please be more specific?

**Comment by jearton** [comment]
@wilkinsona Oh, it's my fault. I imported Spring Boot Parent bom that is `org.springframework.boot:spring-boot-dependencies:3.1.0` in which the spring version property is `spring-framework.version`

**Comment by wilkinsona** [comment]
Cool. Thanks for the clarification. I don't think it would hurt to update the docs with some more up-to-date examples. We can use this issue to do that.
