### ISSUE TITLE
Plugin is not published on plugins.gradle.org

### ISSUE THREAD

**Issue by osoykan** [spring-gradle-plugins/dependency-management-plugin#364]
It might have been forgotten to publish it on gradle registries. It is still the old version, and Gradle can not resolve it when I bump it to 1.1.1.

https://plugins.gradle.org/plugin/io.spring.dependency-management

**Comment by wilkinsona** [comment]
Thanks for the nudge. 1.1.1 is now available from the plugin portal. Please note that it contained a regression (#360) which has been fixed in 1.1.2 which is also available from the plugin portal.
