### ISSUE TITLE
Typo in "Importing a Maven Bom" example

### ISSUE THREAD

**Issue by liy-cn** [spring-gradle-plugins/dependency-management-plugin#366]
https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/#dependency-management-configuration-bom-import

![企业微信截图_20230815183143](https://github.com/spring-gradle-plugins/dependency-management-plugin/assets/2853829/dac95d35-142f-483f-b6e3-d7992722dd78)

mavenBom 'org.springframework.boo:spring-boot-dependencies:3.1.1' should be
mavenBom 'org.springframework.boot:spring-boot-dependencies:3.1.1'

**Comment by wilkinsona** [comment]
Thanks for noticing and reporting this, @liy-cn.
