### ISSUE TITLE
spring dependency management gradle plugin dependency version jars

### ISSUE THREAD

**Issue by wvargas10** [spring-gradle-plugins/dependency-management-plugin#373]
A bit confused with dependency management which can be imported in two  ways

```
plugins {
  id 'io.spring.dependency-management' version '1.1.4'
}

dependencies {
   implementation platform("org.springframework.boot:spring-boot-dependencies:3.2.1")
}
```

I can go online in Maven Repository in see which jar versions are included for 'dependencies'. How do I determine which jar versions are included for the 'plugin'?

**Comment by wilkinsona** [comment]
> ```
> plugins {
>   id 'io.spring.dependency-management' version '1.1.4'
> }
> ```

This alone doesn't apply any dependency management. It just adds the dependency management plugin to the project. To also apply some dependency management, some further configuration is required:

```groovy
dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:3.2.1"
    }
}
```

Note that if you apply both the Spring Boot plugin (`org.springframework.boot`) and the dependency management plugin, the above configuration will be performed automatically. This is a [feature of Spring Boot's Gradle plugin](https://docs.spring.io/spring-boot/docs/3.2.1/gradle-plugin/reference/htmlsingle/#managing-dependencies.dependency-management-plugin).
