### ISSUE TITLE
Provide example how a BOM can be generated from a set of module dependencies

### ISSUE THREAD

**Issue by alexei-osipov** [spring-gradle-plugins/dependency-management-plugin#388]
We use Spring Dependency Management plugin in a multi-module project and want to publish a set of effective dependencies of one modules as a BOM.

Is there any good way to do that? If so, it would be nice to add it to the plugin documentation.

**Comment by wilkinsona** [comment]
The dependency management plugin is intended to consume boms, not publish them. As such, documenting how to create and publish a bom is out of scope.
