### ISSUE TITLE
Add an example of resolving a dependency with a classifier.

### ISSUE THREAD

**Issue by dsyer** [spring-gradle-plugins/dependency-management-plugin#397]
This works:

```groovy
dependencies {
      ...
      testRuntimeOnly "io.netty:netty-transport-native-epoll::linux-x86_64"
}
```

and apparently it is standard notation for Gradle, but I couldn't find any examples anywhere, so we could add one here and that would make users of this plugin aware at least.

**Comment by wilkinsona** [comment]
I'd like to see if the Gradle docs could be improved (as the syntax above isn't specific to this plugin) before documenting it here.

**Comment by wilkinsona** [comment]
Another alternative is:

```groovy
dependencies {
      testRuntimeOnly(group = "io.netty", name = "netty-transport", classifier = "linux-x86_64")
}
```

The Gradle team are going to update their docs so I'll close this one. Hopefully this issue will prove helpful in the meantime.
