### ISSUE TITLE
How can we print the actual reason of a dependency version resolution?

### ISSUE THREAD

**Issue by artemptushkin** [spring-gradle-plugins/dependency-management-plugin#399]
This is a general question for support, it's very much related but I believe it's the best place to ask however I can not find the answer in other issues.

If I use [the SB plugin approach](https://docs.spring.io/spring-boot/gradle-plugin/managing-dependencies.html#managing-dependencies.dependency-management-plugin)

```groovy
dependencyManagement {
        imports {
            mavenBom(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
          ....
```

Then I get

```txt
> Task :distribution:dependencyInsight
io.netty:netty-common:4.1.114.Final (selected by rule)
...

io.netty:netty-common:4.1.114.Final
+--- io.netty:netty-buffer:4.1.114.Final
```

There is no clear reason why it was selected by which rule

---

If I use [the Gradle BOM approach](https://docs.spring.io/spring-boot/gradle-plugin/managing-dependencies.html#managing-dependencies.gradle-bom-support):

```groovy
dependencies {
    implementation(platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES))
   ....
```

Then I get

```txt
> Task :distribution:dependencyInsight
io.netty:netty-common:4.1.114.Final
  Variant runtime:
...
   Selection reasons:
      - Selected by rule
      - By constraint

io.netty:netty-common:4.1.114.Final
+--- io.netty:netty-buffer:4.1.114.Final
|    +--- org.springframework.boot:spring-boot-dependencies:3.3.5
```

Where `org.springframework.boot:spring-boot-dependencies` explains the reason clearly

Q: How can I get the actual reason for `selected by rule` with one single command? I.e. I expect a message like _"overridden by the spring boot plugin and the property `netty.version=4.1.114.Final` (delegates to [this](https://docs.spring.io/spring-boot/appendix/dependency-versions/properties.html))_

Otherwise, it's not clear why this version was selected in any Gradle tasks output

**Comment by wilkinsona** [comment]
You can use the `dependencyManagement` task to see a list of all of the versions that are managed by the dependency management plugin. Beyond that, I'm afraid there isn't a single command that will show you exactly why a dependency has a particular version. To participate in the information displayed by `dependencyInsight`, this plugin would have to [switch to using constraints](https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/330). Never say never, but I think that's unlikely to happen even in the medium term as it's a large change with a high risk of regression and we have other higher priority work that has to come first.

If insight into exactly why a particular version was selected is of high importance to you, all I can really recommend is that you take that into account when deciding whether to use this plugin or Gradle's built-in platform support.

**Comment by artemptushkin** [comment]
@wilkinsona thank you for the answer! So far I support that issue you mentioned, `because` is clearly what's needed for the topic.

As for me `dependencyManagement` is not enough because it's simply a list but I will be playing with `dependencyManagement.managedVersions` and `dependencyManagement.importedProperties` Gradle DSLs.

---
Just for context why it might be important to see the reason.

It's actually AI tools (assuming developers can guess if they do it) that could automate routine with dependencies updates in regards to vulnerabilities. Imagine, now then mostly can recommend **transitive dependency enforcement** but with a clear reason of a selected version they could tell you to update **parent dependency (bom)** which is much cleaner for the codebase.
