### ISSUE TITLE
Populate bom properties before dependency resolution

### ISSUE THREAD

**Issue by pearj** [spring-gradle-plugins/dependency-management-plugin#40]
I would like to use the properties from a [JBoss BOM](https://maven.repository.redhat.com/techpreview/all/org/jboss/bom/eap/jboss-eap-bom-parent/6.3.3.GA/jboss-eap-bom-parent-6.3.3.GA.pom) file, however the they don't seem to be populated by the time that gradle resolves dependencies.

For example I have tried

    testCompile "org.jboss.arquillian.testng:arquillian-testng-container:" + ext['version.org.jboss.arquillian']

But it failed with

    FAILURE: Build failed with an exception.

    * Where:
    Script '/home/japearson/dev/project/main/arquillian-testable.gradle' line: 35

    * What went wrong:
    A problem occurred evaluating script.
    > Cannot get property 'version.org.jboss.arquillian' on extra properties extension as it does not exist

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

    BUILD FAILED

I have tried to use this plugin to resolve the dependencies automatically, however it causes build issues for my project such as:

    * What went wrong:
    Execution failed for task ':project-analytics:ejb-jar:dependencyInsight'.
    > Could not resolve all dependencies for configuration ':project-analytics:ejb-jar:jbossasRemoteTestRuntimeCopy'.
       > Module version main.project-analytics:ejb-jar:unspecified, configuration 'jbossasRemoteTestRuntimeCopy' declares a dependency on configuration 'core' which is not declared in the module descriptor for main.project-analytics:ejb-jar:unspecified

However, when I specify versions manually it works properly ie ```testCompile "org.jboss.arquillian.testng:arquillian-testng-container:1.1.0.Final"```

**Comment by pearj** [comment]
Additionally I'm running Gradle 2.3, and I have found that unless I add ```apply plugin: 'io.spring.dependency-management'``` to the ```allprojects {}``` part of my main gradle file, then dependency resolution doesn't happen at all and it tries to download depedencies without version information ie ```http://nexus.mycompany.com.au/content/repositories/redhat-techpreview/org/jboss/as/jboss-as-arquillian-container-managed//jboss-as-arquillian-container-managed-.pom```

It also turns out that specifying versions directly doesn't fix the ```not declared in the module descriptor``` error. Applying the plugin is what is causing the error.

So if there is some way that I can resolve the properties from the BOM without apply the plugin to every project, that would be good.

**Comment by wilkinsona** [comment]
You're using the wrong syntax to access an imported bom's properties. The correct syntax is [described in the README](https://github.com/spring-gradle-plugins/dependency-management-plugin#accessing-properties-from-imported-boms). You want something like:

```
dependencyManagement.importedProperties['version.org.jboss.arquillian']
```

The bom you're using is unusual as it doesn't declare any dependency management, only a handful of properties. The plugin doesn't tolerate the lack of dependency management which causes a failure. See #41. You could work around this by using one of the other JBoss boms that does provide some dependency management: https://maven.repository.redhat.com/techpreview/all/org/jboss/bom/eap/

> Additionally I'm running Gradle 2.3, and I have found that unless I add apply plugin: 'io.spring.dependency-management' to the allprojects {} part of my main gradle file, then dependency resolution doesn't happen at all and it tries to download depedencies without version information

The plugin only takes effect in projects where it's been applied. This is standard behaviour for Gradle and its plugins. In a multi-project build this will typically mean that you should apply the plugin either in `allprojects` or `subprojects`, depending on the structure of the build.

**Comment by pearj** [comment]
Thanks, I wasn't actually importing the parent bom directly, I am actually doing:

	dependencyManagement {
	 imports {
			 mavenBom "org.jboss.bom.eap:jboss-javaee-6.0-with-tools:$jbossEAPVersion"
			 mavenBom "org.jboss.bom.eap:jboss-javaee-6.0-with-transactions:$jbossEAPVersion"
			 mavenBom "org.jboss.bom.eap:jboss-javaee-6.0-with-security:$jbossEAPVersion"
			 mavenBom "org.jboss.bom.eap:jboss-javaee-6.0-with-hibernate:$jbossEAPVersion"
			 mavenBom "org.jboss.bom.eap:jboss-javaee-6.0-with-resteasy:$jbossEAPVersion"
	 }
	}

Using ```testCompile "org.jboss.arquillian.testng:arquillian-testng-container:" + dependencyManagement.importedProperties['version.org.jboss.arquillian']``` worked a treat because I didn't need to apply the plugin to the subprojects, which meant I didn't need to solve that other build problem.

Thanks again for your help.

By the way, what is the correct place to ask for help on this plugin? The gitter chat room? https://gitter.im/spring-gradle-plugins/dependency-management-plugin ?

**Comment by wilkinsona** [comment]
When you've imported one of those boms, you don't need to specify a version for Arquillian. This will work (and is how this plugin is intended to be used):

```
dependencyManagement {
	imports {
		mavenBom "org.jboss.bom.eap:jboss-javaee-6.0-with-tools:6.3.3.GA"
	}
}

dependencies {
	testCompile "org.jboss.arquillian.testng:arquillian-testng-container"
}
```

The plugin automatically applies the version in the bom to the `org.jboss.arquillian.testng:arquillian-testng-container` dependency.

> By the way, what is the correct place to ask for help on this plugin? The gitter chat room? https://gitter.im/spring-gradle-plugins/dependency-management-plugin ?

Yes, the Gitter chat room is a good place to ask for help. I prefer to keep issues for bugs and feature requests.

**Comment by pearj** [comment]
I did try something like:

	dependencies {
		testCompile "org.jboss.arquillian.testng:arquillian-testng-container"
	}

However it worked for some subprojects and not others, by simply applying the plugin to some of the subprojects it fails with:

	* What went wrong:
	Execution failed for task ':project-analytics:ejb-jar:dependencyInsight'.
	> Could not resolve all dependencies for configuration ':project-analytics:ejb-jar:jbossasRemoteTestRuntimeCopy'.
	   > Module version main.project-analytics:ejb-jar:unspecified, configuration 'jbossasRemoteTestRuntimeCopy' declares a dependency on configuration 'core' which is not declared in the module descriptor for main.project-analytics:ejb-jar:unspecified

So ```dependencyManagement.importedProperties['version.org.jboss.arquillian']``` is a nice workaround where the plugin causes havock on particular subprojects.

**Comment by wilkinsona** [comment]
That's probably due to your project's configuration, rather than that plugin, however it's impossible to say as you've never actually shared enough information to reproduce the problem. I'm happy to help if I can, but it should be tracked as a separate issue. If you do open another issue please take the time to provide a detailed description of the problem you're facing along with the configuration that's required to reproduce it.

**Comment by pearj** [comment]
I have no doubt it's due to the project configuration.  We have quite a complicated (and convoluted in some places) project configuration, that was initially built during the pre 1.0 days of Gradle. If I get time I'll try to find the parts of the configuration that cause the error and raise a separate issue as you suggest.
