### ISSUE TITLE
Downloading detachedConfiguration*.pom slows down my project compilation

### ISSUE THREAD

**Issue by LayHuts** [spring-gradle-plugins/dependency-management-plugin#401]
build.gradle.kts is configured as follows.
```
plugins {
    id("java")
    id("org.springframework.boot") version "3.2.7"
    id("io.spring.dependency-management") version "1.1.5"
}

group = "com.demo"
version = "1.0-SNAPSHOT"

repositories {
    mavenLocal()
    mavenCentral()
}
```

It is currently found that using Sync Gradle Changes will cause Downloading problems.

<img width="553" alt="image" src="https://github.com/user-attachments/assets/95a479de-2832-44e2-b7cc-23c8caf97ccd" />

It will request downloading */1.0-SNAPSHOT/maven-metadata.xml in order of repositories, which will slow down Sync Gradle Changes

```
Download https://repo.maven.apache.org/maven2/com/demo/1.0-SNAPSHOT-detachedConfiguration72/1.0-SNAPSHOT/maven-metadata.xml
```
If you remove io.spring.dependency-management and use manual import of BOM, there will be no downloading.

**Comment by wilkinsona** [comment]
The detached configurations are used to download the poms of all of the dependencies in the graph. This is necessary to apply Maven-style exclusion semantics which can be [disabled](https://docs.spring.io/dependency-management-plugin/docs/1.1.x/reference/html/#maven-exclusions-disabling) if you wish. Alternatively, you can use Gradle's built-in platform support.

**Comment by LayHuts** [comment]
> The detached configurations are used to download the poms of all of the dependencies in the graph. This is necessary to apply Maven-style exclusion semantics which can be [disabled](https://docs.spring.io/dependency-management-plugin/docs/1.1.x/reference/html/#maven-exclusions-disabling) if you wish. Alternatively, you can use Gradle's built-in platform support.

Thanks for your reply
