### ISSUE TITLE
Incorrect deprecated warning when dependencySet configuration is used

### ISSUE THREAD

**Issue by SathishThiagrajan** [spring-gradle-plugins/dependency-management-plugin#45]
I believe there is incorrect logging when dependencySet is used. 

For example, below configuration will trigger deprecated warning  

dependencySet(group:'org.springframework', version: '3.1.0.RELEASE') {
                entry 'spring-test'
                entry 'spring-core'
                entry 'spring-web'
}

Warning message:
"The 'group:name' 'version' syntax is deprecated and will be removed in a future release. Please use dependency 'group:name:version' instead."

**Comment by wilkinsona** [comment]
I don't think that's what's triggering the warning. This script:

```groovy
buildscript {
	repositories {
		jcenter()
	}
	dependencies {
		classpath 'io.spring.gradle:dependency-management-plugin:0.4.1.RELEASE'
	}
}

apply plugin: 'io.spring.dependency-management'
apply plugin: 'java'

repositories {
	jcenter()
}

dependencyManagement {
	dependencies {
		dependencySet(group:'org.springframework', version: '3.1.0.RELEASE') {
			entry 'spring-test'
			entry 'spring-core'
			entry 'spring-web'
		}
	}
}

dependencies {
	compile 'org.springframework:spring-core'
}
```

Works as expected with no deprecation warning:

```
$ gradle dependencies --configuration compile
:dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

compile - Compile classpath for source set 'main'.
\--- org.springframework:spring-core: -> 3.1.0.RELEASE
     +--- org.springframework:spring-asm:3.1.0.RELEASE
     \--- commons-logging:commons-logging:1.1.1

BUILD SUCCESSFUL

Total time: 3.263 secs
```

Can you share a `build.gradle` that reproduces the problem?

**Comment by wilkinsona** [comment]
Closing due to lack of response. If you'd like the issue to be reopened, please comment with the requested information.
