### ISSUE TITLE
Cyclic project dependency fails to resolve

### ISSUE THREAD

**Issue by checketts** [spring-gradle-plugins/dependency-management-plugin#46]
I have 2 projects that are inter-dependent.

*my-module*
````
dependencies {
  testCompile project(':my-module-test-utils')
}
````

*my-module-test-utils*
````
dependencies {
  compile project(':my-module')
}
````

When compiling I get the following error:
```
> Could not resolve all dependencies for configuration ':my-module:testRuntimeCopy'.
  > Module version com.example:my-module-test-utils:0.1.1, configuration 'default' declares a dependency on configuration 'default' which is not declared in the module descriptor for com.example:my-module:7.0.0
```

This used to work with the `0.1.RELEASE`, but ran into it when I tried upgrading to the latest version.

**Comment by wilkinsona** [comment]
Yuck. This is a side-effect of the logic that makes exclusions behave as they do in Maven. Disabling that behaviour may help:

```
dependencyManagement {
    applyMavenExclusions false
}
```

I'll spend a little bit of time seeing if the plugin can be updated to tolerate a cyclic build. However, a better solution would, imo, be to fix your build to remove the circular dependency.

**Comment by checketts** [comment]
Thanks for looking into this @wilkinsona . I agree that the cyclic dependency should be eliminated in my build. I only raised the ticket as is had used to work for us. I think in the end it will improve my build to refactor out the cyclic dependency.

I found myself looking at disabling the `mavenExclusion` stuff for a separate reason (it was causing surprises for my team) so I'll test it so I can report back.

**Comment by wilkinsona** [comment]
This looks to be a bug in/limitation of Gradle.

The plugin creates a copy of the configuration so that it can analyse the transitive dependencies and then use this analysis to configure exclusions on the actual configuration before it's resolved. The copy is taken in the configuration's `beforeResolve` callback. It's done at this point as the configuration's dependencies will all have been configured by this stage, giving the plugin a complete view of those dependencies.

This build script will fail:

```
subprojects {
	apply plugin: 'java'
}

project (':alpha') {
    dependencies {
        testCompile project(':bravo')
    }
    configurations.testRuntime.incoming.beforeResolve {
        configurations.testRuntime.copyRecursive().resolve()
    }
}

project (':bravo') {
    dependencies {
        compile project(':alpha')
    }
}
```

It will also fail if the copy is performed in afterResolve:

```
subprojects {
	apply plugin: 'java'
}

project (':alpha') {
    dependencies {
        testCompile project(':bravo')
    }
    configurations.testRuntime.incoming.afterResolve {
        configurations.testRuntime.copyRecursive().resolve()
    }
}

project (':bravo') {
    dependencies {
        compile project(':alpha')
    }
}
```

If the copy is performed outside of the resolution callbacks (no use to the plugin, but a potentially interesting data point), it will resolve successfully:

```
subprojects {
	apply plugin: 'java'
}

project (':alpha') {
    dependencies {
        testCompile project(':bravo')
    }
    configurations.testRuntime.copyRecursive().resolve()
}

project (':bravo') {
    dependencies {
        compile project(':alpha')
    }
}
```

**Comment by wilkinsona** [comment]
I've [reported the problem on the Gradle forum](http://discuss.gradle.org/t/recursive-copy-of-a-configuration-with-cyclic-dependencies-fails-to-resolve/8726).

**Comment by wilkinsona** [comment]
There's now a [JIRA issue](https://issues.gradle.org/browse/GRADLE-3280) tracking the problem with Gradle. I'm going to close this as won't fix as I don't believe there's anything that can be done in the plugin. You'll either have to wait for a fix in Gradle or remove the cycles from your build.

**Comment by n0mer** [comment]
@wilkinsona i've got the same problem:

my `build.gradle` declares the project's JAR as it's own dependency. Same module, but configuration with custom name.

(N.B.: I use this artificial configuration in the following way: i publish "project JAR" artifact to repo, then resolve everything in this artificial configuration (including "project JAR") from repository, to be able to finally copy everything (including that JAR) to external directory for further assembly and deployment. All this - just to have SNAPSHOT artifacts stored in Nexus for QA.)

After project migrated to BOM approach and "spring io platform", i had to disable MavenExclusions, and this allowed `gradlew dependencies` to resolve dependencies for my artificual configuration.

So, first of all - thank you @wilkinsona for the suggestion about `applyMavenExclusions`.

Next question - is it possible to have `applyMavenExclusions` as `true`, to allow dependency resolution in my case?

**Comment by wilkinsona** [comment]
> is it possible to have applyMavenExclusions as true, to allow dependency resolution in my case?

I don't know. I'm not sure that I've understood your description of your project setup, or why it's necessary. Why not try it and see?

**Comment by n0mer** [comment]
here is a snippet of `build.gradle`

```groovy

configurations.create("worker-${project.name}")

ext {
    workerDir = "$buildDir/worker"
}

task resolveWorker(type: Copy) {
    description "fetch artifacts for Docker image into [$workerDir]"
    from configurations."worker-${project.name}"
    into workerDir
}

dependencies {
    "worker-${project.name}" "${project.group}:${jar.baseName}:${project.version}"
    "worker-${project.name}" "com.newrelic.agent.java:newrelic-agent:${newrelicVersion}"
    "worker-${project.name}" "${project.group}:newrelic-config-${jar.baseName}:${newrelicConfigVersion[jar.baseName]}@yml"
}

```

If `applyMavenExclusions` is set to `true`, i'm getting error 

```
configuration 'worker-webCopy' declares a dependency on configuration 'default' which is not declared in the module descriptor
```

Hope this is more clear.

**Comment by wilkinsona** [comment]
As suspected, you have a dependency cycle. Until there's a fix for [GRADLE-3280](https://issues.gradle.org/browse/GRADLE-3280), you'll either have to set `applyMavenExclusions` to `false` or restructure your build to break the cycle.

**Comment by n0mer** [comment]
@wilkinsona , this is what i did - and thank you for this suggestion.

**Comment by mxab** [comment]
@wilkinsona I had also this error message but no circular dependency but some "similar namings" in a multi project build

folder structure:
```
core/api/build.gradle
core/impl/build.gradle
foo/api/build.gradle
foo/impl/build.gradle
settings.gradle
```

my settings.gradle:
```
include ':core:api'
...
include ':foo:api'
...
```

and my foo api project had a dependency core api, therefore:

_foo/api/build.gradle_ :
```
compile project(":core:api")
```

and I guess therefore gradle thought the api project was itself.
As a workarround I renamed the subprojects folders `core/core-api` and so my project names are "unique"
```
compile project(":core:core-api")
```


Just in case someone has the same issue

**Comment by wilkinsona** [comment]
Thanks, @mxab.
