### ISSUE TITLE
Managed dependency resolves to non-project dependency when version is higher than project version

### ISSUE THREAD

**Issue by checketts** [spring-gradle-plugins/dependency-management-plugin#51]
This may be a gradle bug. Occasionally we would notice the a `:project` dependency which has a matching instance declared in the `dependencyManagement` block would choose the non-project in the dependency tree. (This explanation sounds weird, but the we have a 'core' plugin that lists all the managed dependencies for all our projects so that is why it would get this duplication)

For example in a project we have a helper method to build the `version` attribute like so: `version = ver("1.0")`, the helper puts the Git branch and build number in the version. So when run locally the version is `1.0.0_local` (build number `0` and `local` branch) and the managed dependency version is `1.0.1234_master`.

It wasn't obvious why gradle was ignoring the project dependency, but once we'd chased it to this cause we are able to work around it by making the local version default to a high number so it now generates `1.0.99999_local`

A potential fix to the plugin would be to actually remove the managed dependency from its collection when it detects a collision.

**Comment by wilkinsona** [comment]
I'm not 100% sure that I'm following your description of the projects and their versions. Can you put together a small sample that illustrates the problem?

The plugin shouldn't apply any dependency management to project dependencies (see #9), so it's possible that what you're seeing is Gradle's standard behaviour where it will select the highest version of a dependency.

**Comment by checketts** [comment]
I'll create a sample. We've recreated this in several projects so I believe we have a good understanding of the minimum required to trigger this.

**Comment by wilkinsona** [comment]
@checketts Any joy with the sample?

**Comment by checketts** [comment]
Sorry, had some team reorgs that completely threw this out of mind. I'll be back on this today.

**Comment by wilkinsona** [comment]
Closing due to lack of feedback. @checketts If you have a change to gather the required info, please comment on the issue and I'll reopen it.
