### ISSUE TITLE
spring-cloud-versions causes 1.2.2-RELEASE to be used instead of 1.2.3-RELEASE

### ISSUE THREAD

**Issue by leon** [spring-gradle-plugins/dependency-management-plugin#52]
If I include a spring cloud dependency from start.spring.io so that the mavenBom for spring cloud is included it spring boot gets pulled back to 1.2.2 instead of running 1.2.3

```gradle
buildscript {
    ext {
        springBootVersion = '1.2.3.RELEASE'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}") 
        classpath("io.spring.gradle:dependency-management-plugin:0.5.0.RELEASE")
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'spring-boot' 
apply plugin: 'io.spring.dependency-management' 

jar {
    baseName = 'demo'
    version = '0.0.1-SNAPSHOT'
}
sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
}


dependencies {
    compile("org.springframework.boot:spring-boot-starter-actuator")
    compile("org.springframework.cloud:spring-cloud-starter-oauth2")
    compile("org.springframework.boot:spring-boot-starter-security")
    compile("org.springframework.boot:spring-boot-starter-web")
    testCompile("org.springframework.boot:spring-boot-starter-test") 
}

dependencyManagement {
	imports { 
		mavenBom "org.springframework.cloud:spring-cloud-versions:1.0.0.RELEASE" 
	}
}


eclipse {
    classpath {
         containers.remove('org.eclipse.jdt.launching.JRE_CONTAINER')
         containers 'org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8'
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.3'
}

```

**Comment by wilkinsona** [comment]
The `spring-cloud-versions` bom extends from `spring-boot-starter-parent`, i.e. it provides a superset of Spring Boot's dependency management. Version 1.0.0.RELEASE of `spring-cloud-versions` builds on Spring Boot 1.2.2.RELEASE so that why you're seeing Spring Boot 1.2.2 dependencies being used in your project. In short, the plugin's working as designed.

Spring Cloud 1.0.1.RELEASE is out and it builds on Spring Boot 1.2.3.RELEASE so the easiest solution may be to change the version of Spring Cloud you're using. `spring-cloud-versions` doesn't appear to exist in `1.0.1.RELEASE` (I'm not sure why), but you can use `spring-cloud-starter-parent` instead:

```groovy
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-starter-parent:1.0.1.RELEASE"
    }
}
```

Alternatively, if you want to stay with Spring Cloud 1.0.0.RELEASE you could also import Boot's bom, ensuring it's imported after `spring-cloud-versions`:

```groovy
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-versions:1.0.0.RELEASE"
        mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
    }
}
```

**Comment by leon** [comment]
What will be the best practice for importing boms in spring boot?
Since org.springframework.cloud:spring-cloud-versions is included from start.spring.io that would suggest that that is the preferred way?

**Comment by leon** [comment]
Say to override to spring-data-fowler the preferred way would be

```gradle

ext['spring-data-releasetrain.version'] = 'Fowler-RELEASE'

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-versions:${springCloudVersion}"
        mavenBom "org.springframework.boot:spring-boot-versions:${springBootVersion}"
    }
}
```

**Comment by wilkinsona** [comment]
I think the disappearance of `spring-cloud-versions` in Spring Cloud 1.0.1 was a glitch. It should be back again in 1.0.2. That said, it looks like `spring-cloud-starter-parent` contains the same dependency management and [the Spring Cloud docs](http://projects.spring.io/spring-cloud/docs/1.0.1/spring-cloud.html) recommend its use. @snicoll, perhaps we should update the Initializr to match the docs?

I wouldn't use `spring-boot-versions`. You're better off sticking with `spring-boot-starter-parent` or `spring-boot-dependencies`. There's a subtle difference between the two: `spring-boot-starter-parent` excludes commons-logging.

Other than the changes to the bom coordinates discussed above, your override of the `spring-data-relasetrain.version` property looks good to me.

**Comment by snicoll** [comment]
Andy, I tried using `spring-cloud-starter-parent` has a bom and it didn't work for me. I can try again if you want.

**Comment by wilkinsona** [comment]
Yes please, Stephane. It works fine for me with the dependency management plugin.

**Comment by snicoll** [comment]
Andy, I tried again and it looks like this was a different problem. Current initializr is now on Spring Cloud 1.0.1, using `spring-boot-starter-parent`. Thanks!
