### ISSUE TITLE
Option to disable plugin entirely

### ISSUE THREAD

**Issue by masc3d** [spring-gradle-plugins/dependency-management-plugin#53]
I have just updated to spring-boot-gradle-plugin-1.3.0 and realized the dependency management plugin is now included transitively.

Even when not importing boms it will mess with my own dependencies and resolution strategies to a degree that is not acceptable for me.

I might have missed it, but I could not figure out a way to entirely disable it.

**Comment by wilkinsona** [comment]
This probably needs to be raised against Spring Boot, but it's hard to say for sure without some more specifics about "it will mess with my own dependencies and resolution strategies to a degree that is not acceptable for me". Can you give some examples of the behaviour that you'd like to be able to switch off?

**Comment by masc3d** [comment]
it's a multi project build and I have a gradle resolution strategy applied to all subprojects. spring-boot is only used in one of those subprojects and the dependency plugin will silently override any resolution strategies for packages it has in its own dependency configuration (there seems to be a default bom being imported)

**Comment by wilkinsona** [comment]
There is indeed. Spring Boot applies its own bom. Please raise an issue against [Spring Boot](https://github.com/spring-projects/spring-boot/issues/new) to allow its dependency management to be disabled.

**Comment by masc3d** [comment]
I just did. https://github.com/spring-projects/spring-boot/issues/3164
thanks!
