### ISSUE TITLE
Importing BOMs from outside maven central

### ISSUE THREAD

**Issue by h4xmd** [spring-gradle-plugins/dependency-management-plugin#57]
What is the limitation that is preventing the plugin from resolving BOMs from outside of Maven Central?

**Comment by h4xmd** [comment]
Upon further investigation, it looks like the problem I am having is related to the fact that the BOM I import is simply a parent that imports other BOMs.  Unless those BOMs are installed into my local maven repo (~/.m2), then they never get resolved.

**Comment by wilkinsona** [comment]
Boms and their dependencies are all resolved using the configured repositories. I would guess that you don't have a repository configured that contains the boms imported by the bom that you are importing.
