### ISSUE TITLE
dependencyManagement is not resolving dependencies based on gradle build script but based on maven's settings.xml

### ISSUE THREAD

**Issue by mhuebner** [spring-gradle-plugins/dependency-management-plugin#58]
dependencyManagement plugin is bundled in Grails 3.x apps and plugins. 
But the problem is not related to grails.

dependencyManagement resolves it's dependencies based on maven's settings.xml and this should not be the case. dependencyManagement should resolve dependencies based on the definition from within the gradle build script (repositories). So you have no direct control on where dependencies are resolved from via Gradle. Another problem is that the credential settings from settings.xml are not honored (these should also be definied in gradle's build script).

**Comment by wilkinsona** [comment]
> dependencyManagement resolves it's dependencies based on maven's settings.xml and this should not be the case

What makes you think that this is the case? Any boms that you import are added to a Gradle configuration which is then resolved using Gradle's standard resolution process.

**Comment by wilkinsona** [comment]
Having read grails/grails-core#9274 in more detail, this has nothing to do with the dependency management plugin. It's a limitation of Gradle 2.3 that's [described in the README](https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/master/README.md#using-a-bom-that-is-not-in-maven-central).

**Comment by mhuebner** [comment]
Thanks for outlining that! I wasn't aware of this special case.

**Comment by mhuebner** [comment]
Now I am using Gradle 2.6 in conjunction with Grails 3.1.0 M1 and the bom dependency is resolved only via maven central:

```
   > Unable to initialize POM pom-default.xml: POM 'org.springframework.integration:spring-integration-bom' not found in repository: Unable to download the artifact from any repository
     
       org.springframework.integration:spring-integration-bom:pom:4.2.0.RC1
     
     from the specified remote repositories:
       central (http://repo1.maven.org/maven2)
```

**Comment by wilkinsona** [comment]
It works for me.

Here's a build with Gradle 2.3. As expected, it fails as it can't resolve the Spring Integration bom from Maven Central:

```
$ rm -rf ~/.m2/repository/org/springframework/integration/
$ gradle install
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:install
Downloading: org/springframework/integration/spring-integration-bom/4.2.0.RC1/spring-integration-bom-4.2.0.RC1.pom from repository central at http://repo1.maven.org/maven2
Unable to locate resource in repository
:install FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':install'.
> Could not publish configuration 'archives'
   > Unable to initialize POM pom-default.xml: POM 'org.springframework.integration:spring-integration-bom' not found in repository: Unable to download the artifact from any repository

       org.springframework.integration:spring-integration-bom:pom:4.2.0.RC1

     from the specified remote repositories:
       central (http://repo1.maven.org/maven2)

      for project org.springframework.integration:spring-integration-bom

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.324 secs
```

It works after switching to Gradle 2.6:

```
$ brew switch gradle 2.6
Cleaning /usr/local/Cellar/gradle/1.11
Cleaning /usr/local/Cellar/gradle/1.12
Cleaning /usr/local/Cellar/gradle/2.0
Cleaning /usr/local/Cellar/gradle/2.1
Cleaning /usr/local/Cellar/gradle/2.2
Cleaning /usr/local/Cellar/gradle/2.2.1
Cleaning /usr/local/Cellar/gradle/2.3
Cleaning /usr/local/Cellar/gradle/2.4
Cleaning /usr/local/Cellar/gradle/2.6
1 links created for /usr/local/Cellar/gradle/2.6
$ gradle install
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar
:install

BUILD SUCCESSFUL

Total time: 4.555 secs
```

**Comment by mhuebner** [comment]
This is what I do, but when I add the correct repo to the repositories (gradle build file) this has absolutely no effect because the dependency-management-plugin resolves dependencies from settings.xml not from the build file:

```
repositories {
    mavenLocal()
    mavenCentral()
    maven { url "http://maven.springframework.org/milestone" }
}
```

This only happens if I try to publish 

```
gradlew publish // grails 3.1.0.M1 plugin with bundled Gradle 2.6
```
It's a grails bundled plugin. 
Here's my example app: https://github.com/mhuebner/dependencyMgt_58

**Comment by wilkinsona** [comment]
I'm not surprised it doesn't work; [the wrapper in that repository is Gradle 2.3](https://github.com/mhuebner/dependencyMgt_58/blob/master/gradle/wrapper/gradle-wrapper.properties#L6). That's out of sync with the configuration [which specifies 2.6](https://github.com/mhuebner/dependencyMgt_58/blob/master/gradle.properties#L2).

**Comment by mhuebner** [comment]
Yeah, just saw that, too: https://github.com/grails/grails-core/issues/9274
So it has to be fixed in Grails. Thank you for your quick reply!!
