### ISSUE TITLE
dependency management + spring boot + solr + log4j + junit = error?

### ISSUE THREAD

**Issue by lesliel** [spring-gradle-plugins/dependency-management-plugin#59]
build.gradle:
```
buildscript {
    repositories.mavenCentral()
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:0.5.3.RELEASE"
        classpath "org.springframework.boot:spring-boot-gradle-plugin:1.2.6.RELEASE"
    }
}
apply plugin: 'java'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'spring-boot'
repositories.mavenCentral()
dependencies.compile("org.apache.solr:solr-solrj:4.7.2") //{ exclude group: 'log4j' }
startScripts.enabled = false
bootRepackage.enabled = false
```

result:

_:distTarProcessing of [...]\log4j-1.2.16.pom failed:
    'build.plugins.plugin[io.spring.gradle.dependencymanagement.org.apache.maven.plugins:maven-antrun-plugin].dependencies.dependency.scope' for junit:junit:jar must be one of [compile, runtime, system] but is 'test'. in log4j:log4j:1.2.16_

Excluding _log4j_ of course eliminates this error.

However removing `apply plugin: 'io.spring.dependency-management'`or `apply plugin: 'spring-boot'` (+ `startScripts...` and `bootRepackage...`) would also make the error disappear.

**Comment by wilkinsona** [comment]
There's a bug in Log4J 1.2.16's pom. You can work around that bug by ensuring that your build uses 1.2.17, either by declaring an explicit dependency on `log4j:log4j:1.2.17` or via some dependency management. Given that you appear to be using Spring Boot, you may want to use its bom as the source of the dependency management:

```
dependencyManagement {
	imports {
		mavenBom 'org.springframework.boot:spring-boot-dependencies:1.2.6.RELEASE'
	}
}
```
