### ISSUE TITLE
testCompile {} configuration as specified in README doesn't work

### ISSUE THREAD

**Issue by oliverlockwood** [spring-gradle-plugins/dependency-management-plugin#60]
On the README page it is suggested that the following syntax is valid.
```groovy
dependencyManagement {
    dependencies {
        dependency 'org.springframework:spring-core:4.1.5.RELEASE'
    }
    testCompile {
        dependencies {
            dependency 'org.springframework:spring-beans:4.1.5.RELEASE'
        }
    }
}
```

However, if you run this (with either versions 0.5.2 or 0.5.3 of the plugin) then gradle fails with the following error message:
>Configuration with name 'testCompile' not found.

What is the correct syntax for setting up test-scoped dependency management with the plugin?  And can this please be made clear in the README?  Thanks.

**Comment by wilkinsona** [comment]
The README is correct, AFAIK. I would guess that you don't have a `testCompile` configuration defined in your build. Have you declared such a configuration explicitly or applied a plugin that will declare it for you?

This works for me:

```
buildscript {
	repositories {
		jcenter()
	}
	dependencies {
		classpath "io.spring.gradle:dependency-management-plugin:0.5.3.RELEASE"
	}
}

apply plugin: 'java'
apply plugin: 'io.spring.dependency-management'

repositories {
	jcenter()
}

dependencyManagement {
	testCompile {
		dependencies {
			dependency 'org.springframework:spring-beans:4.1.5.RELEASE'
		}
	}
}
```

Here's the resulting dependency management:

```
$ gradle dependencyManagement
:dependencyManagement

------------------------------------------------------------
Root project
------------------------------------------------------------

global - Default dependency management for all configurations
No dependency management

archives - Dependency management for the archives configuration
No dependency management

compile - Dependency management for the compile configuration
No dependency management

default - Dependency management for the default configuration
No dependency management

runtime - Dependency management for the runtime configuration
No dependency management

testCompile - Dependency management for the testCompile configuration
    org.springframework:spring-beans 4.1.5.RELEASE

testRuntime - Dependency management for the testRuntime configuration
    org.springframework:spring-beans 4.1.5.RELEASE


BUILD SUCCESSFUL

Total time: 2.975 secs
```

**Comment by oliverlockwood** [comment]
Right you are. I had misunderstood, thinking that the `testCompile` configuration inside `dependencyManagement` was coming from this plugin rather than the `java` plugin.

Thank you for clarifying; I'll close this now.

**Comment by oliverlockwood** [comment]
Further clarification for posterity: you have to have done `apply plugin: 'java'` before specifying this configuration.

Which probably comes naturally if you're inlining within a single build script, but potentially less so if you've abstracted out the dependency management and are using e.g. `apply from: '../dep-mgmt.gradle'`.
