### ISSUE TITLE
Build takes three times longer

### ISSUE THREAD

**Issue by knacht** [spring-gradle-plugins/dependency-management-plugin#62]
Hello,

we hat a similar issue like this: https://github.com/spring-projects/spring-boot/issues/3197#issuecomment-114039564 

We refactored our gradle multi module project, replacing spring-boot-plugin with dependeny-management-plugin

The problem is, our build now takes nine minutes instead of three (with skipping tests)
The --profile option from gradle, shows that most of the time is using for the dependncy resolution, espacilly the module which contains the @SpringBootApp.

Of course it is possible, that out configuration has some errors. 
What is the best way, to debug what is increasing the build time?

**Comment by wilkinsona** [comment]
It's a bit rudimentary, but you could try running with `--debug` and examining the timestamps of its output. If you'd like me to do some investigation, please provide a sample `build.gradle` that reproduces the problem.

**Comment by knacht** [comment]
The debug flag didnt really help. It is blazing fast until ich reach the my module which contains the SpringBootApplciation

I try to reproduce the issue with a new project.

**Comment by knacht** [comment]
I am unable to reproduce this with a new, clean project. Therefore there must be something wrong with our config. 

I will take a closer look and open a new issue if neccassary.

**Comment by eugene-kamenev** [comment]
@knacht I am experiencing the same, had you found the reason causing slow build with multiprojects?

**Comment by knacht** [comment]
Nope, but there is definitely something wrong with our project structure (declaring too many dependencies in our top level cradle file)

**Comment by wilkinsona** [comment]
@eugene-kamenev If you have a sample that shows the problem, I'd be happy to take a look

**Comment by knacht** [comment]
Hello,

I am still unable to reproduce our issue, but I stumpled upoton this https://github.com/spring-projects/spring-boot/issues/4538#issuecomment-157761748

Without using `dependencyManagement {
    applyMavenExclusions false
}`

the build takes exactly about 4 mins 30 secs

With 'dependencyManagement {
    applyMavenExclusions false
}'

it goes down to 20.538 secs

**Comment by wilkinsona** [comment]
@knacht Thanks. I've opened #65 to tackle that. I have a couple of improvements locally that require a little more testing. Once they're in a snapshot, it'd be great if you could try them out. I'll mention you on #65 when the time comes.

**Comment by knacht** [comment]
Sure thing, looking forward to it!
