### ISSUE TITLE
Improve performance of Maven exclusion handling

### ISSUE THREAD

**Issue by wilkinsona** [spring-gradle-plugins/dependency-management-plugin#65]
Originally reported as a [Spring Boot issue](https://github.com/spring-projects/spring-boot/issues/4538)

**Comment by wilkinsona** [comment]
@knacht A new 0.5.4.BUILD-SNAPSHOT build's available from https://repo.spring.io/plugins-snapshot that should speed things up quite significantly. If you have a chance to try it out, please let me know how much, if any, difference it makes to the speed of your build.

**Comment by knacht** [comment]
Thx! I will give it a try on Monday and let you know.

**Comment by knacht** [comment]
@wilkinsona 
Hello, Ijust gave it a try, and using the gradle demon, it is as fast using `applyMavenExclusions false`
In other words, it speeds things up quite significantly.
Thank you!

Can you provide more details about the change?

**Comment by wilkinsona** [comment]
@knacht That's excellent news. Thank you for trying out a snapshot. You can see the change that was made [here](https://github.com/spring-gradle-plugins/dependency-management-plugin/commit/3ca43491495769e511f1d051ccd1a3cf59da7425). The commit comment provides some more details.
