### ISSUE TITLE
Support the use of classifiers in dependency management 

### ISSUE THREAD

**Issue by Fredericson** [spring-gradle-plugins/dependency-management-plugin#67]
In maven a version from the dependency management section is only used if it exactly matches the properties {groupId, artifactId,type,classifier}.

I would expect the same behaviour for the version plugin. It means when I specify the following:

```
dependencyManagement {
    dependencies {
		dependency group: 'org.springframework', name: 'spring-context', classifier: 'sources', version: '3.2.8.RELEASE'
    }
}
```

I would expect that this definition will only be applied for a dependency:

```
compile group: 'org.springframework', name:'spring-context', classifier:'sources'
```

and not for

```
compile group: 'org.springframework', name:'spring-context', classifier:'any'
```

Now every dependency with `group: 'org.springframework', name:'spring-context'` gets the version applied, even if the classifier does not match.

But what blocks me most is the fact that because of this issue the plugin is not able to generate valid pom.xml files. For this issue my accetance criteria would be:

With the Input:
```
dependencyManagement {
    dependencies {
	dependency group: 'org.springframework', name: 'spring-context', version: '3.2.8.RELEASE', classifier: 'sources'
        dependency group:'org.springframework', name: 'spring-context', version: '3.2.8.RELEASE') 
    }
}
dependencies {
   compile 'org.springframework:spring-context'
   compile group: 'org.springframework', name:'spring-context', classifier:'sources'
}
```
I would expect the plugin would produce the following pom.xml:
```
<?xml version="1.0" encoding="UTF-8"?> 
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> 
  <modelVersion>4.0.0</modelVersion> 
  <groupId>org.any.experiments</groupId> 
  <artifactId>publisher</artifactId> 
  <version>1.0-SNAPSHOT</version> 
  <dependencies> 
    <dependency> 
      <groupId>org.springframework</groupId> 
      <artifactId>spring-context</artifactId> 
      <scope>runtime</scope> 
    </dependency> 
    <dependency> 
      <groupId>org.springframework</groupId> 
      <artifactId>spring-context</artifactId> 
      <classifier>sources</classifier> 
      <scope>runtime</scope> 
    </dependency> 
  </dependencies> 
  <dependencyManagement> 
    <dependencies> 
      <dependency> 
        <groupId>org.springframework</groupId> 
        <artifactId>spring-context</artifactId> 
        <version>3.2.8.RELEASE</version> 
      </dependency> 
      <dependency> 
        <groupId>org.springframework</groupId> 
        <artifactId>spring-context</artifactId> 
        <version>3.2.8.RELEASE</version> 
        <classifier>sources</classifier>
      </dependency> 
    </dependencies> 
  </dependencyManagement> 
</project> 
```
Here is the produced pom.xml by now, it is invalid for maven or gradle:
```
<?xml version="1.0" encoding="UTF-8"?> 
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> 
  <modelVersion>4.0.0</modelVersion> 
  <groupId>org.any.experiments</groupId> 
  <artifactId>publisher</artifactId> 
  <version>1.0-SNAPSHOT</version> 
  <dependencies> 
    <dependency> 
      <groupId>org.springframework</groupId> 
      <artifactId>spring-context</artifactId> 
      <scope>runtime</scope> 
    </dependency> 
    <dependency> 
      <groupId>org.springframework</groupId> 
      <artifactId>spring-context</artifactId> 
      <classifier>sources</classifier> 
      <scope>runtime</scope> 
    </dependency> 
  </dependencies> 
  <dependencyManagement> 
    <dependencies> 
      <dependency> 
        <groupId>org.springframework</groupId> 
        <artifactId>spring-context</artifactId> 
        <version>3.2.8.RELEASE</version> 
      </dependency> 
    </dependencies> 
  </dependencyManagement> 
</project> 
```
The version for the dependency 'org.springframework:spring-context:sources' cannot be found by gradle or maven, because there is no dependency that matches the properties {groupId,artifactId,type,classifier}

**Comment by Fredericson** [comment]
The expected output:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt; 
&lt;project xmlns=&quot;http://maven.apache.org/POM/4.0.0&quot; xsi:schemaLocation=&quot;http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt; 
  &lt;modelVersion&gt;4.0.0&lt;/modelVersion&gt; 
  &lt;groupId&gt;org.any.experiments&lt;/groupId&gt; 
  &lt;artifactId&gt;publisher&lt;/artifactId&gt; 
  &lt;version&gt;1.0-SNAPSHOT&lt;/version&gt; 
  &lt;dependencies&gt; 
    &lt;dependency&gt; 
      &lt;groupId&gt;org.springframework&lt;/groupId&gt; 
      &lt;artifactId&gt;spring-context&lt;/artifactId&gt; 
      &lt;scope&gt;runtime&lt;/scope&gt; 
    &lt;/dependency&gt; 
    &lt;dependency&gt; 
      &lt;groupId&gt;org.springframework&lt;/groupId&gt; 
      &lt;artifactId&gt;spring-context&lt;/artifactId&gt; 
      &lt;classifier&gt;sources&lt;/classifier&gt; 
      &lt;scope&gt;runtime&lt;/scope&gt; 
    &lt;/dependency&gt; 
  &lt;/dependencies&gt; 
  &lt;dependencyManagement&gt; 
    &lt;dependencies&gt; 
      &lt;dependency&gt; 
        &lt;groupId&gt;org.springframework&lt;/groupId&gt; 
        &lt;artifactId&gt;spring-context&lt;/artifactId&gt; 
        &lt;version&gt;3.2.8.RELEASE&lt;/version&gt; 
      &lt;/dependency&gt; 
      &lt;dependency&gt; 
        &lt;groupId&gt;org.springframework&lt;/groupId&gt; 
        &lt;artifactId&gt;spring-context&lt;/artifactId&gt; 
        &lt;version&gt;3.2.8.RELEASE&lt;/version&gt; 
        &lt;classifier&gt;sources&lt;/classifier&gt;
      &lt;/dependency&gt; 
    &lt;/dependencies&gt; 
  &lt;/dependencyManagement&gt; 
&lt;/project&gt;

**Comment by Fredericson** [comment]
the invalid produced pom.xml:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt; 
&lt;project xmlns=&quot;http://maven.apache.org/POM/4.0.0&quot; xsi:schemaLocation=&quot;http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt; 
  &lt;modelVersion&gt;4.0.0&lt;/modelVersion&gt; 
  &lt;groupId&gt;org.any.experiments&lt;/groupId&gt; 
  &lt;artifactId&gt;publisher&lt;/artifactId&gt; 
  &lt;version&gt;1.0-SNAPSHOT&lt;/version&gt; 
  &lt;dependencies&gt; 
    &lt;dependency&gt; 
      &lt;groupId&gt;org.springframework&lt;/groupId&gt; 
      &lt;artifactId&gt;spring-context&lt;/artifactId&gt; 
      &lt;scope&gt;runtime&lt;/scope&gt; 
    &lt;/dependency&gt; 
    &lt;dependency&gt; 
      &lt;groupId&gt;org.springframework&lt;/groupId&gt; 
      &lt;artifactId&gt;spring-context&lt;/artifactId&gt; 
      &lt;classifier&gt;sources&lt;/classifier&gt; 
      &lt;scope&gt;runtime&lt;/scope&gt; 
    &lt;/dependency&gt; 
  &lt;/dependencies&gt; 
  &lt;dependencyManagement&gt; 
    &lt;dependencies&gt; 
      &lt;dependency&gt; 
        &lt;groupId&gt;org.springframework&lt;/groupId&gt; 
        &lt;artifactId&gt;spring-context&lt;/artifactId&gt; 
        &lt;version&gt;3.2.8.RELEASE&lt;/version&gt; 
      &lt;/dependency&gt; 
    &lt;/dependencies&gt; 
  &lt;/dependencyManagement&gt; 
&lt;/project&gt;

**Comment by wilkinsona** [comment]
With apologies for the delay, I've found some time to look at this in detail.

> In maven a version from the dependency management section is only used if it exactly matches the properties {groupId, artifactId,type,classifier}. I would expect the same behaviour for the version plugin.

That's an entirely reasonable expectation. Unfortunately, classifiers are something of a second-class citizen in Gradle that means it isn't possible to implement.

Gradle's mechanism for changing the version of a dependency is its [`ResolutionStrategy`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ResolutionStrategy.html) interface. During dependency resolution each dependency that will be resolved is passed to the resolution strategy in the form of a [`DependencyResolveDetails`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/DependencyResolveDetails.html). Unfortunately, these details don't include the classifier so it's impossible to look up and apply any classifier-specific dependency management.

The supported syntax, as [described in the README](https://github.com/spring-gradle-plugins/dependency-management-plugin#dependency-management-dsl), is `dependency 'groupId:artifactId:version'` or `dependency group:'group', name:'name', version:version'`.
When you declare dependency management with a classifier it only works because the `dependency` method is being called with a map and the plugin just ignores the `classifier` entry. While the use of classifiers remains unsupported, it might be reasonable to reject a map with a classifier entry so that it's clear that it won't work as one might expect.

> But what blocks me most is the fact that because of this issue the plugin is not able to generate valid pom.xml files

As demonstrated by the pull request from @fpape, it's possible to fix this part of the problem. However, I'm reluctant to do so while dependency management with a classifier can't also be supported during dependency resolution in a Gradle build.

**Comment by wilkinsona** [comment]
It's impossible to implement this while classifiers remain a second class citizen in Gradle. I don't expect that will change any time soon (things haven't improved in Gradle 3.0) so, with some regret, I'm going to close this.

**Comment by prismec** [comment]
Can this issue revisited, now that Gradle 4 and 5 ar out ?

**Comment by wilkinsona** [comment]
AFAIK, Gradle 4 and 5 haven't made any changes in this area and the classifier is still unavailable from [`DependencyResolveDetails`](https://docs.gradle.org/5.2.1/javadoc/org/gradle/api/artifacts/DependencyResolveDetails.html). If you're aware of a change the makes the classifier available, please share the details and this can be revisited.

**Comment by alexeyOnGitHub** [comment]
I just ran into this issue with Gradle 5.6 and io.spring.dependency-management 1.0.5.RELEASE (also tried 1.0.9.RELEASE). were there any relevant changes in Gradle 6.x that could help here?

**Comment by wilkinsona** [comment]
I don't believe so. The classifier continues to be unavailable from `DependencyResolveDetails` and various classifier-related Gradle issues are still open such as https://github.com/gradle/gradle/issues/1947.

**Comment by alexeyOnGitHub** [comment]
side note - I see Gradle 6.x started supporting parent poms (BOMs) natively - https://docs.gradle.org/6.0.1/userguide/platforms.html#sub:bom_import
