### ISSUE TITLE
Is compileOnly supported? Available since Gradle 2.12-rc-1

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-gradle-plugins/dependency-management-plugin#75]
Gradle 2.12-rc-1 supports the new `compileOnly` configuration https://docs.gradle.org/2.12-rc-1/release-notes. Is it possible to use `compileOnly` together with the `dependency-management-plugin`?

**Comment by wilkinsona** [comment]
Have you tried it?

Reading the release notes, I believe it should work. From this plugin's perspective, it's just another configuration.

**Comment by dalewking** [comment]
Don't know about compileOnly, but I know it doesn't work with apt configuration from https://bitbucket.org/hvisser/android-apt

**Comment by wilkinsona** [comment]
@dalewking Interesting. Can you provide some more information please? In what way doesn't it work?

**Comment by dalewking** [comment]
I have attached a project which can be opened in Android Studio that shows the issue. It tries to use the dependency management plugin for specifying the dependency for annotation processing using the apt configuration.

When you try to sync the gradle files it cannot satisfy the dependency

[MyApplication.zip](https://github.com/spring-gradle-plugins/dependency-management-plugin/files/186241/MyApplication.zip)

**Comment by wilkinsona** [comment]
@dalewking Your Gradle configuration is incorrect. You've only applied and configured the plugin in the root project, so `app` has no dependency management at all. You should move the configuration into the `allprojects` section, like so:

```
allprojects {
    apply plugin: 'io.spring.dependency-management'
    repositories {
        jcenter()
    }
    dependencyManagement {
        dependencies {
            dependencySet(group:'com.google.dagger', version: '2.0.1') {
                entry 'dagger-compiler'
                entry 'dagger'
            }
        }
    }
}
```

**Comment by wilkinsona** [comment]
@juergenzimmermann This script demonstrates the plugin working with `compileOnly`:

```groovy
buildscript {
	repositories {
		mavenCentral()
	}

	dependencies {
		classpath 'io.spring.gradle:dependency-management-plugin:0.5.6.RELEASE'
	}
}

apply plugin: 'io.spring.dependency-management'
apply plugin: 'java'

repositories {
	mavenCentral()
}

dependencyManagement {
	compileOnly {
		dependencies {
			dependency 'commons-logging:commons-logging:1.1.3'
		}
	}
	imports {
		mavenBom 'org.springframework.boot:spring-boot-dependencies:1.3.3.RELEASE'
	}
}

dependencies {
	compileOnly 'org.springframework:spring-core'
}

task wrapper(type: Wrapper) {
	gradleVersion = '2.12'
}
```

You can see the global and compileOnly-specific dependency management being applied:

```
$ ./gradlew dependencies
:dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

archives - Configuration for archive artifacts.
No dependencies

compile - Dependencies for source set 'main'.
No dependencies

compileClasspath - Compile classpath for source set 'main'.
\--- org.springframework:spring-core: -> 4.2.5.RELEASE
     \--- commons-logging:commons-logging:1.2 -> 1.1.3

compileOnly - Compile dependencies for source set 'main'.
\--- org.springframework:spring-core: -> 4.2.5.RELEASE
     \--- commons-logging:commons-logging:1.2 -> 1.1.3

default - Configuration for default artifacts.
No dependencies

runtime - Runtime dependencies for source set 'main'.
No dependencies

testCompile - Dependencies for source set 'test'.
No dependencies

testCompileClasspath - Compile classpath for source set 'test'.
No dependencies

testCompileOnly - Compile dependencies for source set 'test'.
No dependencies

testRuntime - Runtime dependencies for source set 'test'.
No dependencies

BUILD SUCCESSFUL

Total time: 3.928 secs
```

**Comment by dalewking** [comment]
Thanks that worked for me!
