### ISSUE TITLE
Dependency resolution seems to be delegated to Maven

### ISSUE THREAD

**Issue by c410-f3r** [spring-gradle-plugins/dependency-management-plugin#76]
Looks like Gradle dependency resolution seems to be delegated to Maven dependency resolution because i got several Maven-like errors after implementing the plugin.
Most of the new erros are gone but there is a odd behavior that I can't understand. A project "X" depends on several other projects and its transients dependencies to compile:

```
dependencies {
    compile(
        project(':projectA'),
        project(':projectB'),
        project(':projectC'),
        project(':projectD'),
        project(':projectE')
    )
}
```

**Sometimes** the "X" compile classpath includes the projects transients dependencies and **sometimes** it doesn't, which means that **sometimes** I can't compile project "X"! I don't know nothing about maven but is it related to maven DAG?

**Comment by wilkinsona** [comment]
The plugin does use some Maven APIs, but that's purely for resolving dependencies' poms and applying Maven's exclusion semantics ([which can be disabled](https://github.com/spring-gradle-plugins/dependency-management-plugin#disabling-maven-exclusions)). All dependency resolution is performed using the standard Gradle mechanisms.

>  i got several Maven-like errors after implementing the plugin.

What are those errors?

> Sometimes the "X" compile classpath includes the projects transients dependencies and sometimes it doesn't, which means that sometimes I can't compile project "X"! I don't know nothing about maven but is it related to maven DAG?

It sounds very unlikely, but it's impossible to say from the information that you have provided. Can you share a sample project the shows the behaviour you're seeing?

**Comment by c410-f3r** [comment]
I couldn't isolate the problem because the dependency tree was way too complex. Instead, I disabled the maven exclusion and now everything is working! Thanks!
