### ISSUE TITLE
Failed to notify dependency resolution listener. > GC overhead limit exceeded" when running "gradle shadowJar" on a large project with imported BOM file

### ISSUE THREAD

**Issue by alexeyOnGitHub** [spring-gradle-plugins/dependency-management-plugin#79]
* tried with Gradle 2.12 and 2.10 
* io.spring.gradle:dependency-management-plugin:0.5.6.RELEASE  (also tried 0.5.4.RELEASE)
* com.github.johnrengelman.shadow 1.2.3
* Windows 7 64bit
* JDK 1.8 64bit

the build downloads a bunch of jars and poms and then fails with 

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Failed to notify dependency resolution listener.
> > GC overhead limit exceeded
> 

I see the java process has 98% CPU and 4.5Gb "working set" memory shown in Windows Task Manager right before the crash.

don't know if that's important, but the project uses Maven-style BOM file via Spring's "dependency-management-plugin" plugin:

```
dependencyManagement {
  imports {
    mavenBom 'companygroup:companyartifact:1.xxxxx-SNAPSHOT'
  }
}



buildscript {
    // for Maven BOM import
    repositories {
        jcenter()
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:0.5.6.RELEASE"
    }

    // for building self-contained jar
    repositories {
        maven {
            name 'Shadow'
            url 'https://plugins.gradle.org/m2/'
        }
    }
    dependencies {
        classpath 'com.github.jengelman.gradle.plugins:shadow:1.2.3'
    }
}


```

I ran the same command with debug info enabled. I see io.spring.dependency-management going into seemingly endless loops:

> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-sca-api
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                         org.apache.tuscany.sca:tuscany-interface-wsdl
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                             org.apache.tuscany.sca:tuscany-xsd
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-assembly
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-monitor
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.ws.commons.schema:XmlSchema
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-contribution
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-assembly
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                         org.apache.tuscany.sca:tuscany-monitor
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                         org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-assembly-xsd
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-common-xml
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                         org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-common-java
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                         org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                         org.apache.tuscany.sca:tuscany-sca-api
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                             org.apache.tuscany.sca:tuscany-contribution
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-assembly
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-monitor
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-assembly-xsd
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-common-xml
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-common-java
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-sca-api
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                             org.apache.ws.commons.schema:XmlSchema
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                             wsdl4j:wsdl4j
> 16:48:59.019 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                             org.apache.tuscany.sca:tuscany-assembly-xml
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-assembly
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-monitor
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                 org.apache.tuscany.sca:tuscany-contribution
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-assembly
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                         org.apache.tuscany.sca:tuscany-monitor
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                         org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-assembly-xsd
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-common-xml
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                         org.apache.tuscany.sca:tuscany-extensibility
> 16:48:59.020 [DEBUG] [io.spring.gradle.dependencymanagement.exclusions.ExclusionConfiguringAction]                                                                     org.apache.tuscany.sca:tuscany-common-java

**Comment by wilkinsona** [comment]
Seems similar to #33, albeit with a different symptom

**Comment by wilkinsona** [comment]
@alexeyOnGitHub I can't reproduce this with the little bit of information that you have provided. I can see that the Tuscany dependencies are very deeply nested, but that's about it. Can you please provide a `build.gradle` that reproduces the problem?

**Comment by alexeyOnGitHub** [comment]
I suspect the circular dependencies are somewhere inside that massive load of stuff coming from the imported BOM file. :( not in the build.gradle file  itself. I posted it to https://gist.github.com/alexeyOnGitHub/c16f619028a2ba2285af2dcde4aaac8b (stripped the company name in it).

**Comment by wilkinsona** [comment]
Thanks. That looks like it's just the `build.gradle`. Can you share the bom too?

**Comment by wilkinsona** [comment]
@alexeyOnGitHub If you'd like me to investigate any further, I'm going to need a bom that triggers the problem.

**Comment by alexeyOnGitHub** [comment]
Hi! I appreciate your willingness to help! I'm currently traveling. I'll check if I can share the file when I'm back. It probably contains a lot of company's proprietary dependencies...

**Comment by wilkinsona** [comment]
@alexeyOnGitHub Any joy?

**Comment by alexeyOnGitHub** [comment]
hi! let's just close this. stripping the company's pom file of proprietary info would most likely remove the problem.

**Comment by wilkinsona** [comment]
Courtesy of @lhotari, I can now reproduce this problem (see #88 for details).
