### ISSUE TITLE
Add project metadata to JAR manifest

### ISSUE THREAD

**Issue by aalmiray** [spring-gradle-plugins/dependency-management-plugin#85]
It would be great if JAR manifests contained additional information related to the project such as

    Manifest-Version: 1.0
    Built-By: ${user.name}
    Created-By: 1.8.0_92 (Oracle Corporation 25.92-b14)
    Build-Date: 2016-05-05
    Build-Time: 18:44:48.377+0200
    Build-Revision: 0ca4beaa67bd484f98fd46e776e31c89adfea234
    Specification-Title: ${project.name}
    Specification-Version: ${project.version}
    Specification-Vendor: spring.io

**Comment by chochos** [comment]
Here's what I did to add git branch and hash:

```groovy
def getLastGitCommit() {
    def p = Runtime.runtime.exec('git show')
    def s = new BufferedReader(new InputStreamReader((p.inputStream)))
    def l1 = s.readLine()
    s.close()
    return l1.substring(l1.indexOf(' ') + 1)
}

def getGitBranch() {
    def p = Runtime.runtime.exec('git branch')
    return p.inputStream.readLines().find { s -> s.startsWith('* ') }.substring(2)
}

jar {
    manifest {
        attributes(
            'git-last-commit': getLastGitCommit(),
            'git-branch': getGitBranch()
        }
    }
}
```
