### ISSUE TITLE
Remove Reference to StyledTextOutputFactory

### ISSUE THREAD

**Issue by rwinch** [spring-gradle-plugins/dependency-management-plugin#87]
We should remove the reference to [StyledTextOutputFactory](https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/07d1006853e2b65f48c89c7c15394921233bbc60/src/main/groovy/io/spring/gradle/dependencymanagement/report/DependencyManagementReportTask.groovy#L23) as this is considered an internal API. This was removed in Gradle 2.14-rc-1 (but will be fixed in 2.14-rc-2). However, it is considered deprecated and will be removed.

The way to determine if an API is public (not internal) is to see if the API is in the Javadoc.

See [Bug in Gradle 2.14-rc1 - No service of type StyledTextOutputFactory](https://discuss.gradle.org/t/bug-in-gradle-2-14-rc1-no-service-of-type-styledtextoutputfactory/17638) for details.

**Comment by wilkinsona** [comment]
Thanks, @rwinch.

I've commented on the forum thread that you started. It's going to be difficult to maintain the plugin's current functionality without `StyledTextOutputFactory` and `StyledTextOutput`. Given that a fix, albeit a temporary one, is coming in RC2, the best option at the moment may be to not do anything until the plugin supports Gradle 3.

**Comment by juergenzimmermann** [comment]
@wilkinsona, @rwinch: The release 2.14-rc-5 still works fine. However, 3.0-milestone-1 produces this stacktrace:
```
Caused by: org.gradle.internal.service.UnknownServiceException: No service of type StyledTextOutputFactory available in ProjectScopeServices.
        at org.gradle.internal.service.DefaultServiceRegistry.getServiceProvider(DefaultServiceRegistry.java:436)
        at org.gradle.internal.service.DefaultServiceRegistry.doGet(DefaultServiceRegistry.java:426)
        at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:414)
        at org.gradle.api.internal.DependencyInjectingInstantiator.convertParameters(DependencyInjectingInstantiator.java:81)
        at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:54)
        at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:121)
        ... 77 more
```

**Comment by wilkinsona** [comment]
@juergenzimmermann Unfortunately, that's to be expected as this plugin doesn't support Gradle 3.0 at the moment.

**Comment by eddumelendez** [comment]
@wilkinsona there is still a reference in [DependencyManagementReportTask](https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/60e325b4face8e6ea62945892f9d6c5c6172e3ef/src/main/groovy/io/spring/gradle/dependencymanagement/report/DependencyManagementReportTask.groovy#L23)

Waiting for it and test spring-boot in jdk9

**Comment by wilkinsona** [comment]
Oops. Thanks, @eddumelendez

**Comment by huxi** [comment]
I'm using this plugin indirectly via `'org.springframework.boot:spring-boot-gradle-plugin:1.3.5.RELEASE'` (see [Spring-boot plugin still broken in M2](https://discuss.gradle.org/t/spring-boot-plugin-still-broken-in-m2/18166/2)).

Any rough guesstimate about when a new spring-boot version including 0.6.0 can be expected?

**Comment by wilkinsona** [comment]
I'm planning to release 0.6.0 in time for it to be included in Spring Boot 1.4.0.RC1.

**Comment by huxi** [comment]
OK, thanks.

**Comment by eddumelendez** [comment]
@huxi you can use this:

```
buildscript {
	ext {
		springBootVersion = '1.4.0.BUILD-SNAPSHOT'
	}
	repositories {
		mavenCentral()
		maven { url "https://repo.spring.io/plugins-snapshot" }
		maven { url "https://repo.spring.io/snapshot" }
		maven { url "https://repo.spring.io/milestone" }
	}
	dependencies {
		classpath "io.spring.gradle:dependency-management-plugin:0.6.0.BUILD-SNAPSHOT"
		classpath "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}"
	}
}
```

Hope this help.

**Comment by wilkinsona** [comment]
Thanks, @eddumelendez 

@huxi Please note that you don't need to use Boot 1.4.0 snapshots. Eddu's suggestion will also work with 1.3.x releases.

**Comment by huxi** [comment]
Thanks a lot. 👍

**Comment by jamesbassett** [comment]
FYI you can use the release version of the dep mgt plugin now: 

    "io.spring.gradle:dependency-management-plugin:0.6.0.RELEASE"

I'm using Boot 1.3.7.RELEASE and Gradle 3 and all seems good so far :)
