### ISSUE TITLE
Module version foo:bar:1.0-SNAPSHOT, configuration 'detachedConfiguration5' declares a dependency on configuration 'default' which is not declared in the module descriptor for foo:bar:1.0-SNAPSHOT

### ISSUE THREAD

**Issue by brianpreuss** [spring-gradle-plugins/dependency-management-plugin#91]
Hi,

I've got a problem when using the dependency-managament-plugin with the gradle-jnlp-plug:

Module version foo:bar:1.0-SNAPSHOT, configuration 'detachedConfiguration5' declares a dependency on configuration 'default' which is not declared in the module descriptor for foo:bar:1.0-SNAPSHOT

Please see also: https://github.com/tschulte/gradle-jnlp-plugin/issues/32

**Comment by wilkinsona** [comment]
Having a project depend on itself, as I believe the JNLP plugin is doing, is rather unusual. Unfortunately, it's effectively a circular dependency [which Gradle can't resolve](https://issues.gradle.org/browse/GRADLE-3280). For more information, including a possible workaround, please see #46.
