### ISSUE TITLE
Plugin incompatible with Gradle 3.0M1

### ISSUE THREAD

**Issue by knacht** [spring-gradle-plugins/dependency-management-plugin#92]
Hello, 

i just want to inform you, that the current version is not compatible with Gradle 3.0 M1 (as stated in the documention)

Error description: 
* What went wrong:
A problem occurred evaluating root project 'de.hswt.fi'.
> Failed to apply plugin [id 'io.spring.dependency-management']
   > Could not create task of type 'DependencyManagementReportTask'.

If you need additional information please let me know

**Comment by wilkinsona** [comment]
Where does the documentation state that the plugin is compatible with 3.0 M1? The README says:

> Gradle 1.x or 2.x (the plugin is tested against 1.12, and 2.4 to 2.13 inclusive).

**Comment by knacht** [comment]
That is what I wanted to say ;)
The README.md say that the plugin is compatible 
> Gradle 1.x or 2.x (the plugin is tested against 1.12, and 2.4 to 2.13 inclusive).

and therefore not compatible with version 3.0 M1

**Comment by wilkinsona** [comment]
As, I see. Sorry for the misunderstanding. The incompatibility it a known issue (see #87). It's fixed in the latest 0.6.0 snapshots which are available from https://repo.spring.io/plugins-snapshot.
