### ISSUE TITLE
dependency resolution fails with muti-project cross-project dependencies

### ISSUE THREAD

**Issue by rgenna** [spring-gradle-plugins/dependency-management-plugin#94]
In a muti-project gradle build lets say you have projectB which has a dependency on projectA and projectA defines dependencies which are resolved via dependencyManagement mavenBom import.   When running the build the dependency resolution will fail when trying to resolve them from projectB but will succeed if resolved from projectA which defines the dependencies.

For instance, in projectA lets say you have:

```
dependencyManagement {
  compile {
    imports {
      mavenBom "some.maven.bom:bom:1.0.0"
    }
  }
}
```

```
dependencies 
{
  compile group: 'resolved.from.maven.bom', name: 'artifact'
}
```

Then in projectB you have:

```
dependencies 
{
  compile project(':projectA')
}
```

If you go to projectA and run the build or  "gradle dependencies" the versions will all be resolved as expected.

However if you go to projectB and run the build or  "gradle dependencies" it will fail to resolve the version of the dependency in projectA.   

I have found this can be worked around by defining an additional dependencyMangement section in projectB which also imports the same bom as projectA, but since projectB doesn't have a direct dependency on that artifact why should projectB need to define this?    For instance if I let gradle resolve the latest version of the dependency in projectA it wouldn't require I define the same dependency in projectB in order for it to be resolved successfully:

```
  compile group: 'resolved.from.maven.bom', name: 'artifact', version '1.0.0+'
```

Is this by design?

**Comment by wilkinsona** [comment]
A resolution strategy is used to set dependency versions based on the configured dependency management. If project A is configured with a resolution strategy and project B depends on project A, project A's resolution strategy isn't run as part of project B being built. Unfortunately there's nothing I can do about this, it's just the way that Gradle works.

The approach that I would recommend is to use a `subprojects` or `allprojects` block to consistently define dependency management across multiple projects.
