### ISSUE TITLE
plugin doesn't work with scala projects

### ISSUE THREAD

**Issue by eprst** [spring-gradle-plugins/dependency-management-plugin#96]
I'm trying to use dependency-management-plugin on a small scala project:

    plugins {
      id "io.spring.dependency-management" version "0.5.7.RELEASE"
    }
    
    apply plugin: 'scala'
    apply plugin: "io.spring.dependency-management"
    
    repositories {
      mavenCentral()
    }
    
    dependencyManagement {
      dependencies {
        // dependency "org.scala-lang:scala-library:2.11.8" // <-- (*)
      }
    }
    
    dependencies {
      compile "org.scala-lang:scala-library:2.11.8"
    }

which works fine while (*) line is commented out, but compilation breaks when I uncomment it:

    * What went wrong:
    Execution failed for task ':xxx:compileScala'.
    > scala.collection.immutable.$colon$colon.hd$1()Ljava/lang/Object;

It fails somewhere inside scalac/zinc internals. Searching the web suggests there's versioning conflict in scala libraries somewhere but I have no clue what exactly is the reason

`gradle dependencies --configuration compile` output looks the same in both cases

any ideas?

**Comment by wilkinsona** [comment]
Can you please share a small project that reproduces the problem?

**Comment by eprst** [comment]
Attached
[spring-bug.tar.gz](https://github.com/spring-gradle-plugins/dependency-management-plugin/files/330583/spring-bug.tar.gz)

**Comment by wilkinsona** [comment]
Your dependency management setup controls the version of `org.scala-lang:scala-library` for every configuration. It Looks like the Scala plugin (I guess) is using another configuration with a different version and when the dependency management plugin changes it, the `NoSuchMethodError` occurs.

It looks like you can avoid the problem by only apply the dependency management to the compile configuration:

```groovy
plugins {
  id "io.spring.dependency-management" version "0.5.7.RELEASE"
}

repositories {
  mavenCentral()
}

apply plugin: 'scala'

dependencyManagement {
  compile {
    dependencies {
      dependency "org.scala-lang:scala-library:2.11.8"
    }
  }
}

dependencies {
  compile "org.scala-lang:scala-library"
}
```

**Comment by eprst** [comment]
Any idea how to make it work with multi-module projects, so that they can share `dependencyManagement` settings (after all that's why we need BOMs in the first place)?

I'm trying to do something like this in the top-level `build.gradle`:

```
subprojects {
  repositories {
    jcenter()
    mavenCentral()
  }

  dependencyManagement {
    compile {
      dependencies {
        dependency "org.scala-lang:scala-library:$scalaVersion"
        // ...
      }
    }

    testCompile {
      // ...
    }
}
```

But it fails on `compile` with

```
* What went wrong:
A problem occurred evaluating root project 'xxx'.
> Configuration with name 'compile' not found.
```

Which is true because there's no `scala` or `java` plugin applied at this point, they only get applied in specific subproject's `build.gradle`.

**Comment by wilkinsona** [comment]
I think there's room for improvement in the plugin there so I've opened https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/97. In the meantime, configuring the dependency management in `afterEvaluate` should work:

```
afterEvaluate {
    dependencyManagement {
        compile {
            dependencies {
                dependency "org.scala-lang:scala-library:$scalaVersion"
            }
        }

        // …
    }
}
```
